--------------------------------------------------------
--  DDL for Sequence CHM_ENLIGHTEN_SITE_MASTER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHM_ENLIGHTEN_SITE_MASTER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 82779 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
