--------------------------------------------------------
--  DDL for Sequence CHM_MSI_SPA_UNIT_ACTIVATION_INCENTIVES_AUDIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHM_MSI_SPA_UNIT_ACTIVATION_INCENTIVES_AUDIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1959 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
