--------------------------------------------------------
--  DDL for Sequence CHM_ENLIGHTEN_DEVICE_DETAILS_AUDIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHM_ENLIGHTEN_DEVICE_DETAILS_AUDIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 263134 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
