--------------------------------------------------------
--  DDL for Sequence CHM_MSI_SPA_GEO_DETAILS_AUDIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHM_MSI_SPA_GEO_DETAILS_AUDIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 379 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
