--------------------------------------------------------
--  DDL for Sequence CHM_MSI_SPA_SYSTEM_SIZE_INCENTIVES_DETAIL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHM_MSI_SPA_SYSTEM_SIZE_INCENTIVES_DETAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 33335 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
