--------------------------------------------------------
--  DDL for Sequence CHM_MSI_SPA_SYSTEM_ATTACHMENT_INCENTIVES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHM_MSI_SPA_SYSTEM_ATTACHMENT_INCENTIVES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 62899 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
