--------------------------------------------------------
--  DDL for Sequence CHM_MSI_CLAIM_BATCH_EXCEPTIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHM_MSI_CLAIM_BATCH_EXCEPTIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 621 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
