CREATE SEQUENCE CHM_LOOKUP_TYPE_SEQ             INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_LOOKUP_TYPES(
     CHM_LOOKUP_TYPE_ID   		NUMBER    		DEFAULT CHM_LOOKUP_TYPE_SEQ.NEXTVAL PRIMARY KEY
    ,CHM_SOURCE_SYSTEM_ID       NUMBER    		NOT NULL
    ,SOURCE_APPLICATION_ID      NUMBER    		NOT NULL
    ,ENTERPRISE_ID              NUMBER    		DEFAULT 1
    ,LANGUAGE         		    VARCHAR2(4000)  DEFAULT 'US' 
    ,LOOKUP_TYPE         		VARCHAR2(4000)  NOT NULL 
    ,MEANING         		    VARCHAR2(4000)  NOT NULL 
	,DESCRIPTION				VARCHAR2(4000)
    ,IS_SEEDED          		CHAR(1)         DEFAULT 'Y'
    ,ENABLED_FLAG        		CHAR(1)         DEFAULT 'Y'
    ,START_DATE_ACTIVE  		DATE            DEFAULT SYSDATE
    ,END_DATE_ACTIVE    		DATE         
    ,ATTRIBUTE1         		VARCHAR2(4000)   
    ,ATTRIBUTE2         		VARCHAR2(4000)   
    ,ATTRIBUTE3         		VARCHAR2(4000)   
    ,ATTRIBUTE4         		VARCHAR2(4000)   
    ,ATTRIBUTE5         		VARCHAR2(4000)   
    ,ATTRIBUTE6         		VARCHAR2(4000)   
    ,ATTRIBUTE7         		VARCHAR2(4000)   
    ,ATTRIBUTE8         		VARCHAR2(4000)   
    ,ATTRIBUTE9         		VARCHAR2(4000)   
    ,ATTRIBUTE10        		VARCHAR2(4000)   
    ,CREATED_BY         		VARCHAR2(4000)  DEFAULT 'SEED_DATA'
    ,CREATION_DATE      		DATE            DEFAULT SYSDATE
    ,LAST_UPDATED_BY    		VARCHAR2(4000)  DEFAULT 'SEED_DATA'
    ,LAST_UPDATE_DATE   		DATE            DEFAULT SYSDATE
	,UNIQUE(CHM_SOURCE_SYSTEM_ID,SOURCE_APPLICATION_ID,ENTERPRISE_ID,LANGUAGE,LOOKUP_TYPE)
);