CREATE SEQUENCE CHM_STATE_PROVINCE_SEQ INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_STATE_PROVINCE (
    CHM_STATE_PROVINCE_ID NUMBER DEFAULT CHM_STATE_PROVINCE_SEQ.NEXTVAL PRIMARY KEY,
    GEOGRAPHY_TYPE        VARCHAR2(4000),
    GEOGRAPHY_NAME        VARCHAR2(4000),
    TERRITORY_CODE        VARCHAR2(4000),
    TERRITORY_SHORT_NAME  VARCHAR2(4000),
    DESCRIPTION           VARCHAR2(4000),
    ATTRIBUTE1            VARCHAR2(4000),
    ATTRIBUTE2            VARCHAR2(4000),
    ATTRIBUTE3            VARCHAR2(4000),
    ATTRIBUTE4            VARCHAR2(4000),
    ATTRIBUTE5            VARCHAR2(4000),
    ATTRIBUTE6            VARCHAR2(4000),
    ATTRIBUTE7            VARCHAR2(4000),
    ATTRIBUTE8            VARCHAR2(4000),
    ATTRIBUTE9            VARCHAR2(4000),
    ATTRIBUTE10           VARCHAR2(4000),
    ATTRIBUTE11           VARCHAR2(4000),
    ATTRIBUTE12           VARCHAR2(4000),
    ATTRIBUTE13           VARCHAR2(4000),
    ATTRIBUTE14           VARCHAR2(4000),
    ATTRIBUTE15           VARCHAR2(4000),
    OIC_RUN_ID            VARCHAR2(4000),
    IS_SEEDED             CHAR(1) DEFAULT 'N',
    ENABLED_FLAG          CHAR(1) DEFAULT 'Y',
    START_DATE_ACTIVE     DATE DEFAULT SYSDATE,
    END_DATE_ACTIVE       DATE,
    CREATED_BY            VARCHAR2(4000) DEFAULT 'INTEGRATIONS',
    CREATION_DATE         DATE DEFAULT SYSDATE,
    LAST_UPDATED_BY       VARCHAR2(4000) DEFAULT 'INTEGRATIONS',
    LAST_UPDATE_DATE      DATE DEFAULT SYSDATE,
    UNIQUE ( GEOGRAPHY_TYPE,GEOGRAPHY_NAME,TERRITORY_SHORT_NAME )
);

/