CREATE SEQUENCE CHM_CALENDAR_SEQ INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_CALENDARS(
	 CHM_CALENDAR_ID					NUMBER  DEFAULT  CHM_CALENDAR_SEQ.NEXTVAL   PRIMARY KEY
	,SOURCE_CALENDAR_ID					NUMBER			NOT NULL
	,PERIOD_SET_NAME					VARCHAR2(4000)		
	,PERIOD_TYPE						VARCHAR2(4000)	
	,USER_PERIOD_SET_NAME				VARCHAR2(4000)	NOT NULL
	,DESCRIPTION						VARCHAR2(4000)		
	,PERIOD_SET_ID						NUMBER			NOT NULL
	,PERIOD_TYPE_ID						NUMBER			NOT NULL
	,NON_ADJ_PERIOD_FREQ_CODE			VARCHAR2(4000)		
	,ADJ_PERIOD_FREQ_CODE				VARCHAR2(4000)		
	,ADJ_PERIODS_NUM					NUMBER		
	,LEGACY_RULES_ENABLED_FLAG			CHAR(1)			NOT NULL
	,NON_ADJ_PERIODS_NUM				NUMBER			NOT NULL
	,USER_PERIOD_NAME_PREFIX			VARCHAR2(4000)		
	,PERIOD_NAME_FORMAT_CODE			VARCHAR2(4000)		
	,PERIOD_NAME_SEPARATOR_CODE			VARCHAR2(4000)		
	,LATEST_YEAR_START_DATE				DATE			NOT NULL
	,CALENDAR_START_DATE				DATE			NOT NULL
	,CALENDAR_TYPE_CODE					VARCHAR2(4000)	NOT NULL
	,LEGACY_CALENDAR_FLAG				CHAR(1)			NOT NULL
	,DEFAULT_PARTITION_GROUP_CODE		VARCHAR2(4000)		
	,IS_SEEDED          				CHAR(1)         DEFAULT 'Y'
    ,ENABLED_FLAG       				CHAR(1)         DEFAULT 'Y'
    ,START_DATE_ACTIVE  				DATE            DEFAULT SYSDATE
    ,END_DATE_ACTIVE    				DATE         
    ,ATTRIBUTE1         				VARCHAR2(4000)   
    ,ATTRIBUTE2         				VARCHAR2(4000)   
    ,ATTRIBUTE3         				VARCHAR2(4000)   
    ,ATTRIBUTE4         				VARCHAR2(4000)   
    ,ATTRIBUTE5         				VARCHAR2(4000)   
    ,ATTRIBUTE6         				VARCHAR2(4000)   
    ,ATTRIBUTE7         				VARCHAR2(4000)   
    ,ATTRIBUTE8         				VARCHAR2(4000)   
    ,ATTRIBUTE9         				VARCHAR2(4000)   
    ,ATTRIBUTE10        				VARCHAR2(4000)
    ,OIC_INSTANCE_ID 	                NUMBER
    ,CREATED_BY         				VARCHAR2(4000)   DEFAULT 'INTEGRATIONS'
    ,CREATION_DATE      				DATE             DEFAULT SYSDATE
    ,LAST_UPDATED_BY    				VARCHAR2(4000)   DEFAULT 'INTEGRATIONS'
    ,LAST_UPDATE_DATE   				DATE             DEFAULT SYSDATE
	,UNIQUE(PERIOD_SET_NAME,PERIOD_TYPE)
);
