CREATE SEQUENCE CHM_CURRENCY_SEQ INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_CURRENCIES(
     CHM_CURRENCY_ID   		NUMBER          DEFAULT  CHM_CURRENCY_SEQ.NEXTVAL     PRIMARY KEY
    ,CURRENCY_CODE   		VARCHAR2(4000)  UNIQUE
    ,NAME         			VARCHAR2(4000)  NOT NULL UNIQUE
    ,DESCRIPTION        	VARCHAR2(4000)	NOT NULL
	,ISSUING_TERRITORY_CODE	VARCHAR2(4000)
    ,SYMBOL          		VARCHAR2(4000)  
    ,CURRENCY_FLAG      	CHAR(1)   		NOT NULL
    ,ISO_FLAG          		CHAR(1)         NOT NULL
    ,LANGUAGE          		VARCHAR2(4000)	DEFAULT 'US'
    ,IS_SEEDED          	CHAR(1)         DEFAULT 'Y'
    ,ENABLED_FLAG        	CHAR(1)         DEFAULT 'Y'
    ,START_DATE_ACTIVE  	DATE            DEFAULT SYSDATE
    ,END_DATE_ACTIVE    	DATE         
    ,ATTRIBUTE1         	VARCHAR2(4000)  
    ,ATTRIBUTE2         	VARCHAR2(4000)  
    ,ATTRIBUTE3         	VARCHAR2(4000)  
    ,ATTRIBUTE4         	VARCHAR2(4000)  
    ,ATTRIBUTE5         	VARCHAR2(4000)  
    ,ATTRIBUTE6         	VARCHAR2(4000)  
    ,ATTRIBUTE7         	VARCHAR2(4000)  
    ,ATTRIBUTE8         	VARCHAR2(4000)  
    ,ATTRIBUTE9         	VARCHAR2(4000)  
    ,ATTRIBUTE10        	VARCHAR2(4000) 
    ,OIC_INSTANCE_ID 	    NUMBER    
    ,CREATED_BY         	VARCHAR2(4000)  DEFAULT 'INTEGRATIONS'
    ,CREATION_DATE      	DATE            DEFAULT SYSDATE
    ,LAST_UPDATED_BY    	VARCHAR2(4000)  DEFAULT 'INTEGRATIONS'
    ,LAST_UPDATE_DATE   	DATE            DEFAULT SYSDATE
    ,UNIQUE(CURRENCY_CODE,LANGUAGE)
);
