CREATE SEQUENCE CHM_EXCHANGE_RATE_SEQ INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_EXCHANGE_RATES(
     CHM_EXCHANGE_RATE_ID   NUMBER  DEFAULT  CHM_EXCHANGE_RATE_SEQ.NEXTVAL     PRIMARY KEY
    ,FROM_CURRENCY			VARCHAR2(4000)
	,TO_CURRENCY			VARCHAR2(4000)
	,CONVERSION_DATE		DATE
	,CONVERSION_TYPE		VARCHAR2(4000)
	,USER_CONVERSION_TYPE	VARCHAR2(4000)	NOT NULL
	,CONVERSION_RATE		NUMBER			NOT NULL
	,STATUS_CODE			CHAR(1)			NOT NULL
    ,IS_SEEDED          	CHAR(1)         DEFAULT 'Y'
    ,ENABLED_FLAG        	CHAR(1)         DEFAULT 'Y'
    ,START_DATE_ACTIVE  	DATE            DEFAULT SYSDATE
    ,END_DATE_ACTIVE    	DATE         
    ,ATTRIBUTE1         	VARCHAR2(4000)   
    ,ATTRIBUTE2         	VARCHAR2(4000)   
    ,ATTRIBUTE3         	VARCHAR2(4000)   
    ,ATTRIBUTE4         	VARCHAR2(4000)   
    ,ATTRIBUTE5         	VARCHAR2(4000)   
    ,ATTRIBUTE6         	VARCHAR2(4000)   
    ,ATTRIBUTE7         	VARCHAR2(4000)   
    ,ATTRIBUTE8         	VARCHAR2(4000)   
    ,ATTRIBUTE9         	VARCHAR2(4000)   
    ,ATTRIBUTE10        	VARCHAR2(4000)   
    ,OIC_INSTANCE_ID 	    NUMBER  
    ,CREATED_BY         	VARCHAR2(4000)   DEFAULT 'INTEGRATIONS'
    ,CREATION_DATE      	DATE            DEFAULT SYSDATE
    ,LAST_UPDATED_BY    	VARCHAR2(4000)   DEFAULT 'INTEGRATIONS'
    ,LAST_UPDATE_DATE   	DATE            DEFAULT SYSDATE
	,UNIQUE (FROM_CURRENCY,TO_CURRENCY,CONVERSION_DATE,CONVERSION_TYPE)
);
