CREATE SEQUENCE CHM_LEDGER_SEQ INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_LEDGERS(
     CHM_LEDGER_ID   				NUMBER  DEFAULT  CHM_LEDGER_SEQ.NEXTVAL PRIMARY KEY 
    ,SOURCE_LEDGER_ID   			NUMBER              UNIQUE
    ,NAME							VARCHAR2(4000)	    NOT NULL	UNIQUE
	,SHORT_NAME						VARCHAR2(4000)	    NOT NULL	UNIQUE
	,DESCRIPTION					VARCHAR2(4000)	    
	,LEDGER_CATEGORY_CODE			VARCHAR2(4000)	    NOT NULL
	,ALC_LEDGER_TYPE_CODE			VARCHAR2(4000)	    NOT NULL
	,OBJECT_TYPE_CODE				CHAR(1)			    NOT NULL
	,LE_LEDGER_TYPE_CODE			CHAR(1)			    NOT NULL
	,COMPLETION_STATUS_CODE			VARCHAR2(4000)	    
	,CHART_OF_ACCOUNTS_ID			NUMBER              NOT NULL
	,CURRENCY_CODE					VARCHAR2(4000)      NOT NULL
	,PERIOD_SET_NAME				VARCHAR2(4000)      NOT NULL
	,SUSPENSE_ALLOWED_FLAG			CHAR(1)             NOT NULL
	,ALLOW_INTERCOMPANY_POST_FLAG	CHAR(1)             NOT NULL
	,ENABLE_AVERAGE_BALANCES_FLAG	CHAR(1)             NOT NULL
	,IS_SEEDED          			CHAR(1)             DEFAULT 'Y'
    ,ENABLED_FLAG       			CHAR(1)             DEFAULT 'Y'
    ,START_DATE_ACTIVE  			DATE                DEFAULT SYSDATE
    ,END_DATE_ACTIVE    			DATE            
    ,ATTRIBUTE1         			VARCHAR2(4000)       
    ,ATTRIBUTE2         			VARCHAR2(4000)       
    ,ATTRIBUTE3         			VARCHAR2(4000)       
    ,ATTRIBUTE4         			VARCHAR2(4000)       
    ,ATTRIBUTE5         			VARCHAR2(4000)       
    ,ATTRIBUTE6         			VARCHAR2(4000)       
    ,ATTRIBUTE7         			VARCHAR2(4000)       
    ,ATTRIBUTE8         			VARCHAR2(4000)       
    ,ATTRIBUTE9         			VARCHAR2(4000)       
    ,ATTRIBUTE10        			VARCHAR2(4000)
    ,OIC_INSTANCE_ID    	        NUMBER
    ,CREATED_BY         			VARCHAR2(4000)      DEFAULT 'INTEGRATIONS'
    ,CREATION_DATE      			DATE                DEFAULT SYSDATE
    ,LAST_UPDATED_BY    			VARCHAR2(4000)      DEFAULT 'INTEGRATIONS'
    ,LAST_UPDATE_DATE   			DATE                DEFAULT SYSDATE
);
