CREATE SEQUENCE CHM_ORGANIZATION_UNIT_SEQ INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_ORGANIZATION_UNITS(
     CHM_ORG_ID   				NUMBER   DEFAULT  CHM_ORGANIZATION_UNIT_SEQ.NEXTVAL		    PRIMARY KEY
    ,SOURCE_ORG_ID   			NUMBER    		    UNIQUE
    ,NAME         				VARCHAR2(4000)      NOT NULL UNIQUE
    ,SHORT_CODE         		VARCHAR2(4000)      NOT NULL UNIQUE
    ,SET_OF_BOOKS_ID        	NUMBER			    NOT NULL
    ,DEFAULT_LEGAL_CONTEXT_ID   NUMBER			    NOT NULL
    ,DATE_FROM        			DATE			    NOT NULL
    ,DATE_TO        			DATE			    NOT NULL
    ,IS_SEEDED          		CHAR(1)             DEFAULT 'Y'
    ,ENABLED_FLAG        		CHAR(1)             DEFAULT 'Y'
    ,START_DATE_ACTIVE  		DATE                DEFAULT SYSDATE
    ,END_DATE_ACTIVE    		DATE         
    ,ATTRIBUTE1         		VARCHAR2(4000)   
    ,ATTRIBUTE2         		VARCHAR2(4000)   
    ,ATTRIBUTE3         		VARCHAR2(4000)   
    ,ATTRIBUTE4         		VARCHAR2(4000)   
    ,ATTRIBUTE5         		VARCHAR2(4000)   
    ,ATTRIBUTE6         		VARCHAR2(4000)   
    ,ATTRIBUTE7         		VARCHAR2(4000)   
    ,ATTRIBUTE8         		VARCHAR2(4000)   
    ,ATTRIBUTE9         		VARCHAR2(4000)   
    ,ATTRIBUTE10        		VARCHAR2(4000)
    ,OIC_INSTANCE_ID    	    NUMBER
    ,CREATED_BY         		VARCHAR2(4000)      DEFAULT 'INTEGRATIONS'
    ,CREATION_DATE      		DATE                DEFAULT SYSDATE
    ,LAST_UPDATED_BY    		VARCHAR2(4000)      DEFAULT 'INTEGRATIONS'
    ,LAST_UPDATE_DATE   		DATE                DEFAULT SYSDATE
);
