CREATE SEQUENCE CHM_TERRITORY_SEQ INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_TERRITORIES(
     CHM_TERRITORY_ID           NUMBER    DEFAULT CHM_TERRITORY_SEQ.NEXTVAL PRIMARY KEY
    ,ENTERPRISE_ID              NUMBER          NOT NULL
    ,LANGUAGE                   VARCHAR2(4000)  NOT NULL
    ,TERRITORY_CODE             VARCHAR2(4000)  NOT NULL
    ,TERRITORY_SHORT_NAME       VARCHAR2(4000)
    ,NLS_TERRITORY              VARCHAR2(4000)
    ,DESCRIPTION                VARCHAR2(4000)
    ,ALTERNATE_TERRITORY_CODE   VARCHAR2(4000)
    ,ISO_TERRITORY_CODE         VARCHAR2(4000)
    ,CURRENCY_CODE              VARCHAR2(4000)
    ,EU_CODE                    VARCHAR2(4000)
    ,ISO_NUMERIC_CODE           VARCHAR2(4000)
    ,OBSOLETE_FLAG              CHAR(1)
    ,ENABLED_FLAG               CHAR(1)
    ,IS_SEEDED          	    CHAR(1)         DEFAULT 'Y'
    ,ATTRIBUTE1                 VARCHAR2(4000)   
    ,ATTRIBUTE2                 VARCHAR2(4000)   
    ,ATTRIBUTE3                 VARCHAR2(4000)   
    ,ATTRIBUTE4                 VARCHAR2(4000)   
    ,ATTRIBUTE5                 VARCHAR2(4000)   
    ,ATTRIBUTE6                 VARCHAR2(4000)   
    ,ATTRIBUTE7                 VARCHAR2(4000)   
    ,ATTRIBUTE8                 VARCHAR2(4000)   
    ,ATTRIBUTE9                 VARCHAR2(4000)   
    ,ATTRIBUTE10                VARCHAR2(4000)
    ,OIC_INSTANCE_ID    	    NUMBER
    ,CREATED_BY                 VARCHAR2(4000)  DEFAULT 'INTEGRATIONS'
    ,CREATION_DATE              DATE            DEFAULT SYSDATE
    ,LAST_UPDATED_BY            VARCHAR2(4000)  DEFAULT 'INTEGRATIONS'
    ,LAST_UPDATE_DATE           DATE            DEFAULT SYSDATE
    ,UNIQUE(ENTERPRISE_ID,LANGUAGE,TERRITORY_CODE)
);
