CREATE SEQUENCE CHM_PRICE_LIST_ITEM_SEQ INCREMENT BY 1 MINVALUE 1;


CREATE TABLE CHM_PRICE_LIST_ITEMS(
     CHM_PRICE_LIST_ITEM_ID   	NUMBER  DEFAULT  CHM_PRICE_LIST_ITEM_SEQ.NEXTVAL PRIMARY KEY 
    ,PRICE_LIST_ITEM_ID   			NUMBER
    ,PRICE_LIST_ID   			    NUMBER
    ,PRICE_LIST_CHARGE_ID   		NUMBER
    ,ITEM_ID   		                NUMBER
    ,BASE_PRICE   		            NUMBER
    ,START_DATE  			        DATE
    ,END_DATE    			        DATE        
	,IS_SEEDED          			CHAR(1) DEFAULT 'Y'
    ,OIC_INSTANCE_ID    	        NUMBER
    ,CREATED_BY         			VARCHAR2(4000)      DEFAULT 'INTEGRATIONS'
    ,CREATION_DATE      			DATE                DEFAULT SYSDATE
    ,LAST_UPDATED_BY    			VARCHAR2(4000)      DEFAULT 'INTEGRATIONS'
    ,LAST_UPDATE_DATE   			DATE                DEFAULT SYSDATE
    ,UNIQUE (PRICE_LIST_ITEM_ID,PRICE_LIST_ID,PRICE_LIST_CHARGE_ID,ITEM_ID)
);
