CREATE SEQUENCE CHM_SPA_STAGING_SEQ INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_SPA_STAGING(
 CHM_STAGE_ID                            NUMBER DEFAULT CHM_SPA_STAGING_SEQ.NEXTVAL
,ID                                      VARCHAR2(4000)
,SPA_NUMBER                              VARCHAR2(4000)
,SPA_NAME                                VARCHAR2(4000)
,OPPORTUNITY_NAME                        VARCHAR2(4000)
,OPPORTUNITY_OWNER                       VARCHAR2(4000)
,OPPORTUNITY_OWNER_ID                    VARCHAR2(4000)
,SPA_OPPORTUNITY_ID                      VARCHAR2(4000)
,INSTALLER_ACCOUNT_NAME                  VARCHAR2(4000)
,ACCOUNT_ID                              VARCHAR2(4000)
,INSTALLER_CUSTOMER_KEY                  VARCHAR2(4000)
,GEOGRAPHY                               VARCHAR2(4000)
,STAGE                                   VARCHAR2(4000)
,STATUS                                  VARCHAR2(4000)
,SPECIAL_PRICING_TYPE                    VARCHAR2(4000)
,DEAL_CATEGORY                           VARCHAR2(4000)
,QUOTE_TO_BUY_BUDGETARY                  VARCHAR2(4000)
,SPA_BACK_DATED                          VARCHAR2(4000)
,NEW_RENEWAL                             VARCHAR2(4000)
,DISTRIBUTOR_ACCOUNT_NAME                VARCHAR2(4000)
,DISTRIBUTOR_SFDC_ID                     VARCHAR2(4000)
,DISTRIBUTOR_SFDC_CUSTOMER_KEY           VARCHAR2(4000)
,SPA_START_DATE                          VARCHAR2(4000)
,SPA_EXPIRATION_DATE                     VARCHAR2(4000)
,SPA_CREATED_DATE                        VARCHAR2(4000)
,SPA_LAST_UPDATE_DATE                    VARCHAR2(4000)
,SPA_CREATED_BY                          VARCHAR2(4000)
,SPA_LAST_UPDATED_BY                     VARCHAR2(4000)
,FINAL_APPROVAL_TIME                     VARCHAR2(4000)
,SPA_TOTAL_PRICE                         VARCHAR2(4000)
,SPA_TOTAL_PRICE_CURRENCY                VARCHAR2(4000)
,DEAL_LOGISTICS                          VARCHAR2(4000)
,DISTRIBUTOR_ORACLE_ACCOUNT_ID           VARCHAR2(4000)
,LINE_ITEM_NUMBER                        VARCHAR2(4000)
,QUANTITY                                VARCHAR2(4000)
,UNIT_PRICE                              VARCHAR2(4000)
,REBATE                                  VARCHAR2(4000)
,FINAL_LIST_PRICE                        VARCHAR2(4000)
,TOTAL_PRICE                             VARCHAR2(4000)
,RECOMMENDED_INSTALLER_PRICE             VARCHAR2(4000)
,DISTRIBUTOR_MARGIN                      VARCHAR2(4000)
,SALES_PRICE_CURRENCY                    VARCHAR2(4000)
,APPROVED_LIST_PRICE                     VARCHAR2(4000)
,SPA_LINE_CREATION_DATE                  VARCHAR2(4000)
,SPA_LINE_CREATED_BY                     VARCHAR2(4000)
,SPA_LINE_LAST_UPDATED_BY                VARCHAR2(4000)
,SPA_LINE_LAST_MODIFIED_DATE             VARCHAR2(4000)
,PRODUCT_NAME                            VARCHAR2(4000)
,PRODUCT_NUMBER                          VARCHAR2(4000)
);