CREATE SEQUENCE CHM_ACCOUNT_KEY_ID_SEQ INCREMENT BY 1 MINVALUE 1;

CREATE TABLE CHM_SFDC_ACCOUNT_MASTER_KEYS (
	CHM_ACCOUNT_KEY_ID          NUMBER DEFAULT CHM_ACCOUNT_KEY_ID_SEQ.NEXTVAL PRIMARY KEY 
	,SFDC_ACCOUNT_ID            VARCHAR2(4000)
    ,SFDC_CREATED_BY            VARCHAR2(4000)      
    ,SFDC_CREATION_DATE         TIMESTAMP(6) WITH TIME ZONE
    ,SFDC_LAST_UPDATED_BY       VARCHAR2(4000)             
    ,SFDC_LAST_UPDATE_DATE      TIMESTAMP(6) WITH TIME ZONE    
	,ATTRIBUTE_CONTEXT          VARCHAR2(4000)
	,ATTRIBUTE1                 VARCHAR2(4000)
	,ATTRIBUTE2                 VARCHAR2(4000)
	,ATTRIBUTE3                 VARCHAR2(4000)
	,ATTRIBUTE4                 VARCHAR2(4000)
	,ATTRIBUTE5                 VARCHAR2(4000)
	,ATTRIBUTE6                 VARCHAR2(4000)
	,ATTRIBUTE7                 VARCHAR2(4000)
	,ATTRIBUTE8                 VARCHAR2(4000)
	,ATTRIBUTE9                 VARCHAR2(4000)
	,ATTRIBUTE10                VARCHAR2(4000)
	,ATTRIBUTE11                VARCHAR2(4000)
	,ATTRIBUTE12                VARCHAR2(4000)
	,ATTRIBUTE13                VARCHAR2(4000)
	,ATTRIBUTE14                VARCHAR2(4000)
	,ATTRIBUTE15                VARCHAR2(4000)
	,OIC_INSTANCE_ID            VARCHAR2(4000)
	,CREATED_BY                 VARCHAR2(4000)
	,CREATION_DATE              TIMESTAMP(6) WITH TIME ZONE
	,LAST_UPDATED_BY            VARCHAR2(4000)
	,LAST_UPDATE_DATE           TIMESTAMP(6) WITH TIME ZONE
	);


CREATE INDEX CHM_SFDC_ACCOUNT_MASTER_KEYS_IDX1 ON CHM_SFDC_ACCOUNT_MASTER_KEYS(SFDC_ACCOUNT_ID);