CREATE SEQUENCE  "CHM"."CHM_SHIP_DETAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 119909 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE TABLE "CHM"."CHM_SHIP_DETAILS_TBL" (
	"CIE_SHIP_DETAIL_ID" NUMBER DEFAULT "CHM"."CHM_SHIP_DETAIL_SEQ"."NEXTVAL"
	,"FULFILL_LINE_ID" NUMBER
    ,"HEADER_ID" NUMBER
    ,"LINE_ID" NUMBER
    ,"DELIVERY_ID" NUMBER
    ,"DELIVERY_DETAIL_ID" NUMBER
    ,"DELIVERY_ASSIGNMENT_ID" NUMBER
	,"ORGANIZATION_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SHIPMENT_NO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"STATUS_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"WAYBILL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"FOB_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"CONFIRMED_BY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"NET_WEIGHT" NUMBER
	,"UOM" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SHIP_CONFIRM_ACK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SHIP_METHOD" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SHIP_METHOD_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SERVICE_LEVEL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SHIPPING_STATUS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SOURCE_HEADER_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"WSH_DESC" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ITEM_DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"WSH_SHIPQTY" NUMBER
	,"SALESPERSON" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"REQUESTED_QUANTITY" NUMBER
	,"PRIMARY_UOM_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SKU" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"FREIGHT_AMT" NUMBER
	,"ORIG_FREIGHT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"FREIGHT_ADDER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"FREIGHT_COST_TYPE_MEANING" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"CUST_REQ_OTD_REASON" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ESTIMATED_TIME_OF_ARRIVAL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ORDER_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"LINE_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"LINE_STATUS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ORDER_TYPE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"CUST_PO_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SCHEDULED_SHIP_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ACTUAL_SHIPMENT_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"WEEK" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SHIP_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ACTUAL_SHIP_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ORDER_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"UNIT_SELLING_PRICE" NUMBER
	,"EXTENDED_AMOUNT" NUMBER
	,"CURRENCY_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SHIPPING_INSTRUCTIONS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SUBINVENTORY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"WAREHOUSE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"REQUEST_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"PROMISE_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"CUST_REQUEST_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SITE_USE_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SHIPTO_LOCATION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"SHIP_TO_CUSTOMER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ADDRESS1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ADDRESS2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ADDRESS3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"CITY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"STATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ZIP_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"COUNTRY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"PARTY_ID" NUMBER
	,"PARTY_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"CUST_ACCOUNT_ID" NUMBER
	,"CUSTOMER_NUMBER" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"CUSTOMER_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ITEM_COST" NUMBER
	,"PRODUCT_TYPE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"PRODUCT_FAMILY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"DESTINATION_SUBINVENTORY_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"DESTINATION_ORG_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"DESTINATION_LOC_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"BOOKED_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"BOOKED_BY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"IS_BOOKED_BY_CREATOR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE6" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE7" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE8" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE9" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"ATTRIBUTE10" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
	,"OIC_INSTANCE_ID" NUMBER
	,"CREATED_BY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'INTEGRATIONS'
	,"CREATION_DATE" DATE DEFAULT SYSDATE
	,"LAST_UPDATED_BY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'INTEGRATIONS'
	,"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE
	,CONSTRAINT "CIE_SHIP_DETAIL_PK" PRIMARY KEY ("CIE_SHIP_DETAIL_ID") USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "DATA" ENABLE
	,CONSTRAINT "CHM_SHIP_DETAILS_TBL_UNQ1" UNIQUE(HEADER_ID,LINE_ID,DELIVERY_ID,DELIVERY_DETAIL_ID,DELIVERY_ASSIGNMENT_ID,FULFILL_LINE_ID)
    ) DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "DATA";

