--CHM_INTEGRATIONS
BEGIN
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMMSISHIPMENTDETAILSYNCERPTOCHM','CHMMsiShipmentDetailSyncERPtoCHM','MSI Shipment Detail Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    
    dbms_output.put_line('Data inserted for CHM_INTEGRATIONS');
    
	INSERT INTO CHM_LOOKUP_TYPES (CHM_SOURCE_SYSTEM_ID, SOURCE_APPLICATION_ID, LOOKUP_TYPE, MEANING, DESCRIPTION,USER_ROLES) VALUES ('1', '-1', 'CHM_MSI_SHIPMENT_SYNC_COUNTRY_RESTRICTION', 'Country Restriction for MSI Shipment Sync', 'Country Restriction for MSI Shipment Sync','SUPER_ADMIN:IT_SYS_ADMIN');
    
    dbms_output.put_line('Data inserted for CHM_LOOKUP_VALUES');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_MSI_SHIPMENT_SYNC_COUNTRY_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 100, 'DE','Germany', 'Germany');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_MSI_SHIPMENT_SYNC_COUNTRY_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 200, 'IT','Italy', 'Italy');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_MSI_SHIPMENT_SYNC_COUNTRY_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 300, 'NL','Netherlands', 'Netherlands');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_MSI_SHIPMENT_SYNC_COUNTRY_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 400, 'ES','Spain', 'Spain');
    
    COMMIT;
    
END;
/

