
  CREATE TABLE "CHM_SPA_CONTACTS" 
   (	"CHM_SPA_CONTACTS_ID" NUMBER DEFAULT "CHM"."CHM_SPA_CONTACTS_ID_SEQ"."NEXTVAL", 
	"ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_DELETED" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CURRENCY_ISO_CODE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SFDC_CREATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SFDC_CREATED_BY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SFDC_LAST_MODIFIED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SFDC_LAST_MODIFIED_BY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SYSTEM_MOD_STAMP" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_ACTIVITY_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_VIEWED_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_REFERENCED_DATE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTACT_NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"SPA" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE_CONTEXT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE1" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE2" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE3" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE4" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE5" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE6" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE7" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE8" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE9" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE10" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE11" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE12" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE13" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE14" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ATTRIBUTE15" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_BY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_UPDATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SOURCE_APP_ID" NUMBER, 
	"ENTERPRISE_ID" NUMBER, 
	"IP_ADDRESS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_AGENT" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"OIC_INSTANCE_ID" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "AIU_CHM_SPA_CONTACTS" AFTER
    INSERT OR UPDATE OR DELETE ON chm_spa_contacts
    FOR EACH ROW
BEGIN
    IF inserting THEN
        INSERT INTO chm_spa_contacts_audit (
            chm_spa_contacts_audit_id,
            chm_spa_contacts_id,
            new_id,
            new_is_deleted,
            new_name,
            new_currency_iso_code,
            new_sfdc_created_date,
            new_sfdc_created_by,
            new_sfdc_last_modified_date,
            new_sfdc_last_modified_by,
            new_system_mod_stamp,
            new_last_activity_date,
            new_last_viewed_date,
            new_last_referenced_date,
            new_contact_id,
            new_contact_name,
            new_spa,
            new_email,
            new_attribute_context,
            new_attribute1,
            new_attribute2,
            new_attribute3,
            new_attribute4,
            new_attribute5,
            new_attribute6,
            new_attribute7,
            new_attribute8,
            new_attribute9,
            new_attribute10,
            new_attribute11,
            new_attribute12,
            new_attribute13,
            new_attribute14,
            new_attribute15,
            new_created_by,
            new_creation_date,
            new_last_updated_by,
            new_last_updated_date,
            new_source_app_id,
            new_enterprise_id,
            new_ip_address,
            new_user_agent,
            new_oic_instance_id,
            action,
            CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,
			IP_ADDRESS,       
			USER_AGENT
        ) VALUES (
            chm_spa_contacts_audit_id_seq.NEXTVAL,
            :new.chm_spa_contacts_id,
            :new.id,
            :new.is_deleted,
            :new.name,
            :new.currency_iso_code,
            :new.sfdc_created_date,
            :new.sfdc_created_by,
            :new.sfdc_last_modified_date,
            :new.sfdc_last_modified_by,
            :new.system_mod_stamp,
            :new.last_activity_date,
            :new.last_viewed_date,
            :new.last_referenced_date,
            :new.contact_id,
            :new.contact_name,
            :new.spa,
            :new.email,
            :new.attribute_context,
            :new.attribute1,
            :new.attribute2,
            :new.attribute3,
            :new.attribute4,
            :new.attribute5,
            :new.attribute6,
            :new.attribute7,
            :new.attribute8,
            :new.attribute9,
            :new.attribute10,
            :new.attribute11,
            :new.attribute12,
            :new.attribute13,
            :new.attribute14,
            :new.attribute15,
            :new.created_by,
            :new.creation_date,
            :new.last_updated_by,
            :new.last_updated_date,
            :new.source_app_id,
            :new.enterprise_id,
            :new.ip_address,
            :new.user_agent,
            :new.oic_instance_id,
            'INSERT',
            NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    ELSIF updating THEN
        INSERT INTO chm_spa_contacts_audit (
            chm_spa_contacts_audit_id,
            chm_spa_contacts_id,
            old_id,
            old_is_deleted,
            old_name,
            old_currency_iso_code,
            old_sfdc_created_date,
            old_sfdc_created_by,
            old_sfdc_last_modified_date,
            old_sfdc_last_modified_by,
            old_system_mod_stamp,
            old_last_activity_date,
            old_last_viewed_date,
            old_last_referenced_date,
            old_contact_id,
            old_contact_name,
            old_spa,
            old_email,
            old_attribute_context,
            old_attribute1,
            old_attribute2,
            old_attribute3,
            old_attribute4,
            old_attribute5,
            old_attribute6,
            old_attribute7,
            old_attribute8,
            old_attribute9,
            old_attribute10,
            old_attribute11,
            old_attribute12,
            old_attribute13,
            old_attribute14,
            old_attribute15,
            old_created_by,
            old_creation_date,
            old_last_updated_by,
            old_last_updated_date,
            old_source_app_id,
            old_enterprise_id,
            old_ip_address,
            old_user_agent,
            old_oic_instance_id,
            new_id,
            new_is_deleted,
            new_name,
            new_currency_iso_code,
            new_sfdc_created_date,
            new_sfdc_created_by,
            new_sfdc_last_modified_date,
            new_sfdc_last_modified_by,
            new_system_mod_stamp,
            new_last_activity_date,
            new_last_viewed_date,
            new_last_referenced_date,
            new_contact_id,
            new_contact_name,
            new_spa,
            new_email,
            new_attribute_context,
            new_attribute1,
            new_attribute2,
            new_attribute3,
            new_attribute4,
            new_attribute5,
            new_attribute6,
            new_attribute7,
            new_attribute8,
            new_attribute9,
            new_attribute10,
            new_attribute11,
            new_attribute12,
            new_attribute13,
            new_attribute14,
            new_attribute15,
            new_created_by,
            new_creation_date,
            new_last_updated_by,
            new_last_updated_date,
            new_source_app_id,
            new_enterprise_id,
            new_ip_address,
            new_user_agent,
            new_oic_instance_id,
            action,
            CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,
			IP_ADDRESS,       
			USER_AGENT
        ) VALUES (
            chm_spa_contacts_audit_id_seq.NEXTVAL,
            :new.chm_spa_contacts_id,
            :old.id,
            :old.is_deleted,
            :old.name,
            :old.currency_iso_code,
            :old.sfdc_created_date,
            :old.sfdc_created_by,
            :old.sfdc_last_modified_date,
            :old.sfdc_last_modified_by,
            :old.system_mod_stamp,
            :old.last_activity_date,
            :old.last_viewed_date,
            :old.last_referenced_date,
            :old.contact_id,
            :old.contact_name,
            :old.spa,
            :old.email,
            :old.attribute_context,
            :old.attribute1,
            :old.attribute2,
            :old.attribute3,
            :old.attribute4,
            :old.attribute5,
            :old.attribute6,
            :old.attribute7,
            :old.attribute8,
            :old.attribute9,
            :old.attribute10,
            :old.attribute11,
            :old.attribute12,
            :old.attribute13,
            :old.attribute14,
            :old.attribute15,
            :old.created_by,
            :old.creation_date,
            :old.last_updated_by,
            :old.last_updated_date,
            :old.source_app_id,
            :old.enterprise_id,
            :old.ip_address,
            :old.user_agent,
            :old.oic_instance_id,
            :new.id,
            :new.is_deleted,
            :new.name,
            :new.currency_iso_code,
            :new.sfdc_created_date,
            :new.sfdc_created_by,
            :new.sfdc_last_modified_date,
            :new.sfdc_last_modified_by,
            :new.system_mod_stamp,
            :new.last_activity_date,
            :new.last_viewed_date,
            :new.last_referenced_date,
            :new.contact_id,
            :new.contact_name,
            :new.spa,
            :new.email,
            :new.attribute_context,
            :new.attribute1,
            :new.attribute2,
            :new.attribute3,
            :new.attribute4,
            :new.attribute5,
            :new.attribute6,
            :new.attribute7,
            :new.attribute8,
            :new.attribute9,
            :new.attribute10,
            :new.attribute11,
            :new.attribute12,
            :new.attribute13,
            :new.attribute14,
            :new.attribute15,
            :new.created_by,
            :new.creation_date,
            :new.last_updated_by,
            :new.last_updated_date,
            :new.source_app_id,
            :new.enterprise_id,
            :new.ip_address,
            :new.user_agent,
            :new.oic_instance_id,
            'UPDATE',
            NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    ELSIF deleting THEN
        INSERT INTO chm_spa_contacts_audit (
            chm_spa_contacts_audit_id,
            chm_spa_contacts_id,
            old_id,
            old_is_deleted,
            old_name,
            old_currency_iso_code,
            old_sfdc_created_date,
            old_sfdc_created_by,
            old_sfdc_last_modified_date,
            old_sfdc_last_modified_by,
            old_system_mod_stamp,
            old_last_activity_date,
            old_last_viewed_date,
            old_last_referenced_date,
            old_contact_id,
            old_contact_name,
            old_spa,
            old_email,
            old_attribute_context,
            old_attribute1,
            old_attribute2,
            old_attribute3,
            old_attribute4,
            old_attribute5,
            old_attribute6,
            old_attribute7,
            old_attribute8,
            old_attribute9,
            old_attribute10,
            old_attribute11,
            old_attribute12,
            old_attribute13,
            old_attribute14,
            old_attribute15,
            old_created_by,
            old_creation_date,
            old_last_updated_by,
            old_last_updated_date,
            old_source_app_id,
            old_enterprise_id,
            old_ip_address,
            old_user_agent,
            old_oic_instance_id,
            action,
            CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,
			IP_ADDRESS,       
			USER_AGENT
        ) VALUES (
            chm_spa_contacts_audit_id_seq.NEXTVAL,
            :old.chm_spa_contacts_id,
            :old.id,
            :old.is_deleted,
            :old.name,
            :old.currency_iso_code,
            :old.sfdc_created_date,
            :old.sfdc_created_by,
            :old.sfdc_last_modified_date,
            :old.sfdc_last_modified_by,
            :old.system_mod_stamp,
            :old.last_activity_date,
            :old.last_viewed_date,
            :old.last_referenced_date,
            :old.contact_id,
            :old.contact_name,
            :old.spa,
            :old.email,
            :old.attribute_context,
            :old.attribute1,
            :old.attribute2,
            :old.attribute3,
            :old.attribute4,
            :old.attribute5,
            :old.attribute6,
            :old.attribute7,
            :old.attribute8,
            :old.attribute9,
            :old.attribute10,
            :old.attribute11,
            :old.attribute12,
            :old.attribute13,
            :old.attribute14,
            :old.attribute15,
            :old.created_by,
            :old.creation_date,
            :old.last_updated_by,
            :old.last_updated_date,
            :old.source_app_id,
            :old.enterprise_id,
            :old.ip_address,
            :old.user_agent,
            :old.oic_instance_id,
            'DELETE',
            NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    END IF;
END;
/
ALTER TRIGGER "AIU_CHM_SPA_CONTACTS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_MSI_SPA_CONTACTS_TRG" 
  BEFORE INSERT OR UPDATE ON CHM_SPA_CONTACTS
  FOR EACH ROW
   BEGIN
      IF INSERTING THEN
        IF :new.CHM_SPA_CONTACTS_ID  IS NULL THEN
            :new.CHM_SPA_CONTACTS_ID   := CHM_SPA_CONTACTS_ID_SEQ.NEXTVAL;
        END IF;

       -- :NEW.attribute10 := chm_util_pkg.removespecialwords(:NEW.NAME);

        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATED_DATE   := NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP) ;
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());

      ELSIF updating THEN

        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATED_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATED_DATE != :NEW.LAST_UPDATED_DATE THEN
                    :NEW.LAST_UPDATED_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;
              END IF;
       EXCEPTION
  WHEN OTHERS THEN
    chm_msi_debug_api.log_msg(:new.CHM_SPA_CONTACTS_ID || ', ' || :new.ID, 'BIU_CHM_MSI_SPA_CONTACTS_TRG', SQLERRM);
    END;
/
ALTER TRIGGER "BIU_CHM_MSI_SPA_CONTACTS_TRG" ENABLE;
