SELECT SUPP.PARTY_ID
	,SUPP.VENDOR_ID
	,SUPP.SEGMENT1
	,SUPP.VENDOR_NAME
	,SUPP.ATTRIBUTE1
	,SITE.VENDOR_SITE_ID
	,SITE.PARTY_SITE_ID
	,SITE.PRC_BU_ID
	,SITE.LOCATION_ID
	,SITE.VENDOR_SITE_CODE
	,SITE.PARTY_SITE_NAME
	,IEP.EXT_PAYEE_ID
	,IEP.PAYMENT_FUNCTION
	,IEP.SUPPLIER_SITE_ID
	,IPU.INSTRUMENT_PAYMENT_USE_ID
	,IPU.PAYMENT_FLOW
	,IPU.EXT_PMT_PARTY_ID
	,IPU.INSTRUMENT_ID
	,BANK.EXT_BANK_ACCOUNT_ID
	,BANK.BRANCH_ID
	,BANK.BANK_ID
	,BANK.BANK_ACCOUNT_NAME
	,BANK.CURRENCY_CODE
	,BANK.IBAN
	,BANK.BANK_ACCOUNT_NUM
	,BRANCH.COUNTRY_NAME
	,BRANCH.BANK_NAME
	,BRANCH.BANK_BRANCH_NAME
	,BRANCH.EFT_SWIFT_CODE
FROM POZ_SUPPLIERS_V SUPP
	,POZ_SUPPLIER_SITES_V SITE
	,IBY_EXTERNAL_PAYEES_ALL IEP
	,IBY_PMT_INSTR_USES_ALL IPU
	,IBY_EXT_BANK_ACCOUNTS BANK
	,POZ_SITE_ASSIGNMENTS_ALL_X SITEA
	,CE_BANK_BRANCHES_V BRANCH
WHERE
	SUPP.VENDOR_ID = SITE.VENDOR_ID
	AND SUPP.PARTY_ID = IEP.PAYEE_PARTY_ID
	AND IEP.EXT_PAYEE_ID = IPU.EXT_PMT_PARTY_ID
	AND IPU.PAYMENT_FUNCTION = IEP.PAYMENT_FUNCTION
	AND IPU.PAYMENT_FUNCTION = 'PAYABLES_DISB'
	AND BANK.EXT_BANK_ACCOUNT_ID = IPU.INSTRUMENT_ID
	AND BRANCH.BANK_PARTY_ID = BANK.BANK_ID
	AND BRANCH.BRANCH_PARTY_ID = BANK.BRANCH_ID
	AND SITEA.VENDOR_SITE_ID = SITE.VENDOR_SITE_ID
	AND SUPP.VENDOR_NAME = 'SOLERTEM'
