
  CREATE TABLE "CHM_MSI_CLAIM_AP_INVOICES" 
   (	"CHM_TRANSACTION_ID" NUMBER, 
	"CLAIM_BATCH_ID" NUMBER, 
	"TRANSACTION_DATE" DATE, 
	"ACCOUNTING_DATE" DATE, 
	"PAYEE_NUMBER" VARCHAR2(4000), 
	"PAYEE_NAME" VARCHAR2(4000), 
	"PAYEE_ENLIGHTEN_ID" VARCHAR2(4000), 
	"INSTALLER_NUMBER" VARCHAR2(4000), 
	"INSTALLER_NAME" VARCHAR2(4000), 
	"INSTALLER_ENLIGHTEN_ID" VARCHAR2(4000), 
	"SPA_NUMBER" VARCHAR2(4000), 
	"SPA_START_DATE" DATE, 
	"SPA_EXPIRATION_DATE" DATE, 
	"REBATE_TYPE" VARCHAR2(4000), 
	"REBATE_TIER" VARCHAR2(4000), 
	"REBATE_ITEM_NUMBER" VARCHAR2(4000), 
	"DEVICE_ITEM_NUMBER" VARCHAR2(4000), 
	"TRANSACTION_LINE_DESCRIPTION" VARCHAR2(2000), 
	"SITE_ID" VARCHAR2(4000), 
	"SITE_NAME" VARCHAR2(4000), 
	"CURRENCY_CODE" VARCHAR2(100), 
	"QUANTITY" NUMBER, 
	"TOTAL_AMOUNT" NUMBER, 
	"ORACLE_AP_INTERFACE_STATUS" VARCHAR2(4000), 
	"ORACLE_AP_INVOICE_NUMBER" VARCHAR2(4000), 
	"ORACLE_AP_INVOICE_ID" VARCHAR2(4000), 
	"ATTRIBUTE_CONTEXT" VARCHAR2(4000), 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"ATTRIBUTE11" VARCHAR2(4000), 
	"ATTRIBUTE12" VARCHAR2(4000), 
	"ATTRIBUTE13" VARCHAR2(4000), 
	"ATTRIBUTE14" VARCHAR2(4000), 
	"ATTRIBUTE15" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(250), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(250), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SOURCE_APP_ID" NUMBER, 
	"ENTERPRISE_ID" NUMBER, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000), 
	"INVOICE_LINE_NUMBER" NUMBER, 
	"INVOICE_SOURCE" VARCHAR2(4000), 
	"INVOICE_DESCRIPTION" VARCHAR2(4000), 
	"INVOICE_TYPE" VARCHAR2(4000), 
	"CALCULATE_TAX" VARCHAR2(4000), 
	"ADD_TAX" VARCHAR2(4000), 
	"LINE_TYPE" VARCHAR2(4000), 
	"PRODUCT_TYPE" VARCHAR2(4000), 
	"LINE_GROUP_NUMBER" VARCHAR2(4000), 
	"COUNTRY" VARCHAR2(4000), 
	"REPORT_REQUEST_ID" NUMBER, 
	"REFERENCE_NAME" VARCHAR2(4000), 
	"SFDC_ACCOUNT_ID" VARCHAR2(4000), 
	"LOAD_REQUEST_ID" NUMBER, 
	"LOAD_REQUEST_STATUS" VARCHAR2(4000), 
	"IMPORT_REQUEST_ID" NUMBER, 
	"IMPORT_REQUEST_STATUS" VARCHAR2(4000), 
	"OIC_INSTANCE_ID" VARCHAR2(4000), 
	"DIST_CODE_COMBINATION" VARCHAR2(4000), 
	"IMPORT_SET" VARCHAR2(4000), 
	"BU_NAME" VARCHAR2(4000), 
	 PRIMARY KEY ("CHM_TRANSACTION_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_DEVICE_ITEM_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("DEVICE_ITEM_NUMBER") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_IMPORT_STATUS_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("IMPORT_REQUEST_STATUS") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_ACCT_DATE_ID_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("ACCOUNTING_DATE") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_CLAIM_BATCH_ID_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("CLAIM_BATCH_ID") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_NUM_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("ORACLE_AP_INVOICE_NUMBER") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_PAYEE_NUM_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("PAYEE_NUMBER") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_REBATE_TYPE_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("REBATE_TYPE") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_SITE_ID_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("SITE_ID") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_SPA_NUMBER_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("SPA_NUMBER") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_TRX_DATE_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("TRANSACTION_DATE") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_LOAD_STATUS_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("IMPORT_REQUEST_ID") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_PAYEE_ENLIGHTEN_ID_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("PAYEE_ENLIGHTEN_ID") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_REBATE_ITEM_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("REBATE_ITEM_NUMBER") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_IMPORT_ID_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("LOAD_REQUEST_STATUS") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_LOAD_ID_IDX" ON "CHM_MSI_CLAIM_AP_INVOICES" ("LOAD_REQUEST_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_MSI_CLAIM_AP_INVOICES" BEFORE
    INSERT OR UPDATE ON CHM_MSI_CLAIM_AP_INVOICES
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.CHM_TRANSACTION_ID IS NULL THEN
            :NEW.CHM_TRANSACTION_ID := chm_claim_credit_memo_transactions_seq.NEXTVAL;
        END IF;
       :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATED_DATE  := NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP) ;
        :NEW.SOURCE_APP_ID      := NVL(:NEW.SOURCE_APP_ID, CHM_UTIL_PKG.GETSOURCEAPP('CHM'));
        :NEW.ENTERPRISE_ID      := NVL(:NEW.ENTERPRISE_ID, CHM_CONST_PKG.GETENTERPRISEID());
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());

      ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATED_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATED_DATE != :NEW.LAST_UPDATED_DATE THEN
                    :NEW.LAST_UPDATED_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

      END IF;
   END;






/
ALTER TRIGGER "BIU_CHM_MSI_CLAIM_AP_INVOICES" ENABLE;