
  CREATE TABLE "CHM_MSI_SHIP_DETAILS_TBL" 
   (	"CHM_MSI_SHIP_DETAIL_ID" NUMBER DEFAULT CHM.CHM_MSI_SHIP_DETAILS_SEQ.NEXTVAL, 
	"CUSTOMER_NAME" VARCHAR2(4000), 
	"DELIVERY_DETAIL_ID" NUMBER, 
	"SERIAL_NUMBER" VARCHAR2(4000), 
	"ACTUAL_SHIP_DATE" DATE, 
	"ENPHASE_PRODUCT_NAME" VARCHAR2(4000), 
	"SHIPPING_ORG_NAME" VARCHAR2(4000), 
	"SHIPPING_LOCATION" VARCHAR2(4000), 
	"CUST_ACCOUNT_ID" NUMBER, 
	"CUST_ACCOUNT_NUMBER" VARCHAR2(4000), 
	"SHIPPING_ORG_ID" NUMBER, 
	"SALES_ORDER_ORG_ID" NUMBER, 
	"SALES_ORDER_TYPE" VARCHAR2(4000), 
	"SALES_ORDER_LINE_TYPE" VARCHAR2(4000), 
	"ATTRIBUTE_CONTEXT" VARCHAR2(4000), 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"ATTRIBUTE11" VARCHAR2(4000), 
	"ATTRIBUTE12" VARCHAR2(4000), 
	"ATTRIBUTE13" VARCHAR2(4000), 
	"ATTRIBUTE14" VARCHAR2(4000), 
	"ATTRIBUTE15" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(4000), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(4000), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SOURCE_APP_ID" NUMBER, 
	"ENTERPRISE_ID" NUMBER, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000), 
	"OIC_INSTANCE_ID" VARCHAR2(4000), 
	"INVENTORY_ITEM_ID" NUMBER, 
	"SHIPPING_ADDRESS" VARCHAR2(4000), 
	"COUNTRY" VARCHAR2(4000), 
	"HEADER_ID" NUMBER, 
	"LINE_ID" NUMBER, 
	"FULFILL_LINE_ID" NUMBER, 
	"ORDER_NUMBER" VARCHAR2(4000), 
	"DELIVERY_ID" NUMBER, 
	"SALES_ORDER_ORG_NAME" VARCHAR2(4000), 
	"WAREHOUSE" VARCHAR2(4000), 
	"SUBINVENTORY" VARCHAR2(4000), 
	"SHIPMENT_NO" VARCHAR2(4000), 
	"LINE_NUMBER" VARCHAR2(4000), 
	"DELIVERY_ASSIGNMENT_ID" NUMBER, 
	"SYNC_FOR_DATE" DATE
   ) ;

  CREATE INDEX "CHM_MSI_SHIP_DETAILS_IDX" ON "CHM_MSI_SHIP_DETAILS_TBL" ("HEADER_ID", "LINE_ID", "FULFILL_LINE_ID", "DELIVERY_ID", "DELIVERY_DETAIL_ID", "DELIVERY_ASSIGNMENT_ID", "SERIAL_NUMBER") 
  ;

  CREATE INDEX "CHM_MSI_SHIP_DETAILS_TBL_ENPHASE_PRODUCT_NAME_IDX" ON "CHM_MSI_SHIP_DETAILS_TBL" ("ENPHASE_PRODUCT_NAME") 
  ;

  CREATE INDEX "CHM_MSI_SHIP_DETAILS_TBL_SERIAL_NUM_IDX" ON "CHM_MSI_SHIP_DETAILS_TBL" ("SERIAL_NUMBER") 
  ;

  CREATE INDEX "CHM_MSI_SHIP_DETAILS_TBL_SKU_SERIAL_IDX" ON "CHM_MSI_SHIP_DETAILS_TBL" ("ENPHASE_PRODUCT_NAME", "SERIAL_NUMBER") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "AIU_CHM_MSI_SHIP_DETAILS_TBL_TRG" AFTER
    INSERT OR UPDATE OR DELETE ON chm_msi_ship_details_tbl
    FOR EACH ROW
BEGIN
    IF inserting THEN
        INSERT INTO chm_msi_ship_details_tbl_audit (
            chm_msi_ship_details_tbl_audit_id,
            chm_msi_ship_detail_id,
            new_customer_name,
            new_delivery_detail_id,
            new_serial_number,
            new_actual_ship_date,
            new_enphase_product_name,
            new_shipping_org_name,
            new_shipping_location,
            new_cust_account_id,
            new_cust_account_number,
            new_shipping_org_id,
            new_sales_order_org_id,
            new_sales_order_type,
            new_sales_order_line_type,
            new_attribute_context,
            new_attribute1,
            new_attribute2,
            new_attribute3,
            new_attribute4,
            new_attribute5,
            new_attribute6,
            new_attribute7,
            new_attribute8,
            new_attribute9,
            new_attribute10,
            new_attribute11,
            new_attribute12,
            new_attribute13,
            new_attribute14,
            new_attribute15,
            new_created_by,
            new_creation_date,
            new_last_updated_by,
            new_last_updated_date,
            new_source_app_id,
            new_enterprise_id,
            new_ip_address,
            new_user_agent,
            new_oic_instance_id,
            new_inventory_item_id,
            new_shipping_address,
            new_country,
            new_header_id,
            new_line_id,
            new_fulfill_line_id,
            new_order_number,
            new_delivery_id,
            new_sales_order_org_name,
            new_warehouse,
            new_subinventory,
            new_shipment_no,
            new_line_number,
            new_delivery_assignment_id,
            new_sync_for_date,
            action,
            CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,
			SOURCE_APP_ID ,   
			ENTERPRISE_ID,    
			IP_ADDRESS,       
			USER_AGENT
        ) VALUES (
            chm_msi_ship_details_seq.NEXTVAL,
            :new.chm_msi_ship_detail_id,
            :new.customer_name,
            :new.delivery_detail_id,
            :new.serial_number,
            :new.actual_ship_date,
            :new.enphase_product_name,
            :new.shipping_org_name,
            :new.shipping_location,
            :new.cust_account_id,
            :new.cust_account_number,
            :new.shipping_org_id,
            :new.sales_order_org_id,
            :new.sales_order_type,
            :new.sales_order_line_type,
            :new.attribute_context,
            :new.attribute1,
            :new.attribute2,
            :new.attribute3,
            :new.attribute4,
            :new.attribute5,
            :new.attribute6,
            :new.attribute7,
            :new.attribute8,
            :new.attribute9,
            :new.attribute10,
            :new.attribute11,
            :new.attribute12,
            :new.attribute13,
            :new.attribute14,
            :new.attribute15,
            :new.created_by,
            :new.creation_date,
            :new.last_updated_by,
            :new.last_updated_date,
            :new.source_app_id,
            :new.enterprise_id,
            :new.ip_address,
            :new.user_agent,
            :new.oic_instance_id,
            :new.inventory_item_id,
            :new.shipping_address,
            :new.country,
            :new.header_id,
            :new.line_id,
            :new.fulfill_line_id,
            :new.order_number,
            :new.delivery_id,
            :new.sales_order_org_name,
            :new.warehouse,
            :new.subinventory,
            :new.shipment_no,
            :new.line_number,
            :new.delivery_assignment_id,
            :new.sync_for_date,
            'INSERT',
            NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP),
			NVL(:NEW.SOURCE_APP_ID, CHM_UTIL_PKG.GETSOURCEAPP('CHM')),
			NVL(:NEW.ENTERPRISE_ID, CHM_CONST_PKG.GETENTERPRISEID()),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    ELSIF updating THEN
        INSERT INTO chm_msi_ship_details_tbl_audit (
            chm_msi_ship_details_tbl_audit_id,
            chm_msi_ship_detail_id,
            old_customer_name,
            old_delivery_detail_id,
            old_serial_number,
            old_actual_ship_date,
            old_enphase_product_name,
            old_shipping_org_name,
            old_shipping_location,
            old_cust_account_id,
            old_cust_account_number,
            old_shipping_org_id,
            old_sales_order_org_id,
            old_sales_order_type,
            old_sales_order_line_type,
            old_attribute_context,
            old_attribute1,
            old_attribute2,
            old_attribute3,
            old_attribute4,
            old_attribute5,
            old_attribute6,
            old_attribute7,
            old_attribute8,
            old_attribute9,
            old_attribute10,
            old_attribute11,
            old_attribute12,
            old_attribute13,
            old_attribute14,
            old_attribute15,
            old_created_by,
            old_creation_date,
            old_last_updated_by,
            old_last_updated_date,
            old_source_app_id,
            old_enterprise_id,
            old_ip_address,
            old_user_agent,
            old_oic_instance_id,
            old_inventory_item_id,
            old_shipping_address,
            old_country,
            old_header_id,
            old_line_id,
            old_fulfill_line_id,
            old_order_number,
            old_delivery_id,
            old_sales_order_org_name,
            old_warehouse,
            old_subinventory,
            old_shipment_no,
            old_line_number,
            old_delivery_assignment_id,
            old_sync_for_date,
            new_customer_name,
            new_delivery_detail_id,
            new_serial_number,
            new_actual_ship_date,
            new_enphase_product_name,
            new_shipping_org_name,
            new_shipping_location,
            new_cust_account_id,
            new_cust_account_number,
            new_shipping_org_id,
            new_sales_order_org_id,
            new_sales_order_type,
            new_sales_order_line_type,
            new_attribute_context,
            new_attribute1,
            new_attribute2,
            new_attribute3,
            new_attribute4,
            new_attribute5,
            new_attribute6,
            new_attribute7,
            new_attribute8,
            new_attribute9,
            new_attribute10,
            new_attribute11,
            new_attribute12,
            new_attribute13,
            new_attribute14,
            new_attribute15,
            new_created_by,
            new_creation_date,
            new_last_updated_by,
            new_last_updated_date,
            new_source_app_id,
            new_enterprise_id,
            new_ip_address,
            new_user_agent,
            new_oic_instance_id,
            new_inventory_item_id,
            new_shipping_address,
            new_country,
            new_header_id,
            new_line_id,
            new_fulfill_line_id,
            new_order_number,
            new_delivery_id,
            new_sales_order_org_name,
            new_warehouse,
            new_subinventory,
            new_shipment_no,
            new_line_number,
            new_delivery_assignment_id,
            new_sync_for_date,
            action,
            CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,
			SOURCE_APP_ID ,   
			ENTERPRISE_ID,    
			IP_ADDRESS,       
			USER_AGENT
        ) VALUES (
            chm_msi_ship_details_seq.NEXTVAL,
            :NEW.chm_msi_ship_detail_id,
            :old.customer_name,
            :old.delivery_detail_id,
            :old.serial_number,
            :old.actual_ship_date,
            :old.enphase_product_name,
            :old.shipping_org_name,
            :old.shipping_location,
            :old.cust_account_id,
            :old.cust_account_number,
            :old.shipping_org_id,
            :old.sales_order_org_id,
            :old.sales_order_type,
            :old.sales_order_line_type,
            :old.attribute_context,
            :old.attribute1,
            :old.attribute2,
            :old.attribute3,
            :old.attribute4,
            :old.attribute5,
            :old.attribute6,
            :old.attribute7,
            :old.attribute8,
            :old.attribute9,
            :old.attribute10,
            :old.attribute11,
            :old.attribute12,
            :old.attribute13,
            :old.attribute14,
            :old.attribute15,
            :old.created_by,
            :old.creation_date,
            :old.last_updated_by,
            :old.last_updated_date,
            :old.source_app_id,
            :old.enterprise_id,
            :old.ip_address,
            :old.user_agent,
            :old.oic_instance_id,
            :old.inventory_item_id,
            :old.shipping_address,
            :old.country,
            :old.header_id,
            :old.line_id,
            :old.fulfill_line_id,
            :old.order_number,
            :old.delivery_id,
            :old.sales_order_org_name,
            :old.warehouse,
            :old.subinventory,
            :old.shipment_no,
            :old.line_number,
            :old.delivery_assignment_id,
            :old.sync_for_date,
            :new.customer_name,
            :new.delivery_detail_id,
            :new.serial_number,
            :new.actual_ship_date,
            :new.enphase_product_name,
            :new.shipping_org_name,
            :new.shipping_location,
            :new.cust_account_id,
            :new.cust_account_number,
            :new.shipping_org_id,
            :new.sales_order_org_id,
            :new.sales_order_type,
            :new.sales_order_line_type,
            :new.attribute_context,
            :new.attribute1,
            :new.attribute2,
            :new.attribute3,
            :new.attribute4,
            :new.attribute5,
            :new.attribute6,
            :new.attribute7,
            :new.attribute8,
            :new.attribute9,
            :new.attribute10,
            :new.attribute11,
            :new.attribute12,
            :new.attribute13,
            :new.attribute14,
            :new.attribute15,
            :new.created_by,
            :new.creation_date,
            :new.last_updated_by,
            :new.last_updated_date,
            :new.source_app_id,
            :new.enterprise_id,
            :new.ip_address,
            :new.user_agent,
            :new.oic_instance_id,
            :new.inventory_item_id,
            :new.shipping_address,
            :new.country,
            :new.header_id,
            :new.line_id,
            :new.fulfill_line_id,
            :new.order_number,
            :new.delivery_id,
            :new.sales_order_org_name,
            :new.warehouse,
            :new.subinventory,
            :new.shipment_no,
            :new.line_number,
            :new.delivery_assignment_id,
            :new.sync_for_date,
            'UPDATE',
            NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP),
			NVL(:NEW.SOURCE_APP_ID, CHM_UTIL_PKG.GETSOURCEAPP('CHM')),
			NVL(:NEW.ENTERPRISE_ID, CHM_CONST_PKG.GETENTERPRISEID()),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    ELSIF deleting THEN
        INSERT INTO chm_msi_ship_details_tbl_audit (
            chm_msi_ship_details_tbl_audit_id,
            chm_msi_ship_detail_id,
            old_customer_name,
            old_delivery_detail_id,
            old_serial_number,
            old_actual_ship_date,
            old_enphase_product_name,
            old_shipping_org_name,
            old_shipping_location,
            old_cust_account_id,
            old_cust_account_number,
            old_shipping_org_id,
            old_sales_order_org_id,
            old_sales_order_type,
            old_sales_order_line_type,
            old_attribute_context,
            old_attribute1,
            old_attribute2,
            old_attribute3,
            old_attribute4,
            old_attribute5,
            old_attribute6,
            old_attribute7,
            old_attribute8,
            old_attribute9,
            old_attribute10,
            old_attribute11,
            old_attribute12,
            old_attribute13,
            old_attribute14,
            old_attribute15,
            old_created_by,
            old_creation_date,
            old_last_updated_by,
            old_last_updated_date,
            old_source_app_id,
            old_enterprise_id,
            old_ip_address,
            old_user_agent,
            old_oic_instance_id,
            old_inventory_item_id,
            old_shipping_address,
            old_country,
            old_header_id,
            old_line_id,
            old_fulfill_line_id,
            old_order_number,
            old_delivery_id,
            old_sales_order_org_name,
            old_warehouse,
            old_subinventory,
            old_shipment_no,
            old_line_number,
            old_delivery_assignment_id,
            old_sync_for_date,
            action,
            CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,
			SOURCE_APP_ID ,   
			ENTERPRISE_ID,    
			IP_ADDRESS,       
			USER_AGENT
        ) VALUES (
            chm_msi_ship_details_seq.NEXTVAL,
            :old.chm_msi_ship_detail_id,
            :old.customer_name,
            :old.delivery_detail_id,
            :old.serial_number,
            :old.actual_ship_date,
            :old.enphase_product_name,
            :old.shipping_org_name,
            :old.shipping_location,
            :old.cust_account_id,
            :old.cust_account_number,
            :old.shipping_org_id,
            :old.sales_order_org_id,
            :old.sales_order_type,
            :old.sales_order_line_type,
            :old.attribute_context,
            :old.attribute1,
            :old.attribute2,
            :old.attribute3,
            :old.attribute4,
            :old.attribute5,
            :old.attribute6,
            :old.attribute7,
            :old.attribute8,
            :old.attribute9,
            :old.attribute10,
            :old.attribute11,
            :old.attribute12,
            :old.attribute13,
            :old.attribute14,
            :old.attribute15,
            :old.created_by,
            :old.creation_date,
            :old.last_updated_by,
            :old.last_updated_date,
            :old.source_app_id,
            :old.enterprise_id,
            :old.ip_address,
            :old.user_agent,
            :old.oic_instance_id,
            :old.inventory_item_id,
            :old.shipping_address,
            :old.country,
            :old.header_id,
            :old.line_id,
            :old.fulfill_line_id,
            :old.order_number,
            :old.delivery_id,
            :old.sales_order_org_name,
            :old.warehouse,
            :old.subinventory,
            :old.shipment_no,
            :old.line_number,
            :old.delivery_assignment_id,
            :old.sync_for_date,
            'DELETE',
            NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP),
			NVL(:NEW.SOURCE_APP_ID, CHM_UTIL_PKG.GETSOURCEAPP('CHM')),
			NVL(:NEW.ENTERPRISE_ID, CHM_CONST_PKG.GETENTERPRISEID()),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    END IF;
END;
/
ALTER TRIGGER "AIU_CHM_MSI_SHIP_DETAILS_TBL_TRG" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_MSI_SHIP_DETAILS_TBL_TRG" 
  BEFORE INSERT OR UPDATE ON CHM_MSI_SHIP_DETAILS_TBL
  FOR EACH ROW
   BEGIN
      IF INSERTING THEN
        IF :new.CHM_MSI_SHIP_DETAIL_ID  IS NULL THEN
            :new.CHM_MSI_SHIP_DETAIL_ID   := CHM_MSI_SHIP_DETAILS_SEQ.NEXTVAL;
        END IF;


        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATED_DATE   := NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP) ;
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());


      ELSIF updating THEN

        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATED_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATED_DATE != :NEW.LAST_UPDATED_DATE THEN
                    :NEW.LAST_UPDATED_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

              END IF;
       EXCEPTION
  WHEN OTHERS THEN
    chm_msi_debug_api.log_msg(:new.CHM_MSI_SHIP_DETAIL_ID, 'BIU_CHM_MSI_SHIP_DETAILS_TBL_TRG', SQLERRM);
    END;

/
ALTER TRIGGER "BIU_CHM_MSI_SHIP_DETAILS_TBL_TRG" ENABLE;