
  CREATE TABLE "CHM_MSI_CLAIM_LOGS" 
   (	"REPORT_REQUEST_ID" NUMBER, 
	"BATCH_LOG_ID" NUMBER, 
	"FILE_ID" NUMBER, 
	"BATCH_ID" NUMBER, 
	"LINE_ID" NUMBER, 
	"RUN_ID" NUMBER, 
	"LOG_TYPE" VARCHAR2(240), 
	"LOG_STATUS" VARCHAR2(240), 
	"LOG_CODE" VARCHAR2(240), 
	"LOG_MSG" VARCHAR2(4000), 
	"CURRENT_FLAG" VARCHAR2(1), 
	"ATTRIBUTE_CONTEXT" VARCHAR2(4000), 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"ATTRIBUTE11" VARCHAR2(4000), 
	"ATTRIBUTE12" VARCHAR2(4000), 
	"ATTRIBUTE13" VARCHAR2(4000), 
	"ATTRIBUTE14" VARCHAR2(4000), 
	"ATTRIBUTE15" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(250), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(250), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SOURCE_APP_ID" NUMBER, 
	"ENTERPRISE_ID" NUMBER, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000), 
	 CONSTRAINT "CHM_MSI_CLAIM_LOGS_PK" PRIMARY KEY ("BATCH_LOG_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "CHM_MSI_CLAIM_LOGS_BATCH_ID_IDX1" ON "CHM_MSI_CLAIM_LOGS" ("BATCH_ID") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_LOGS_LINE_ID_ID_IDX1" ON "CHM_MSI_CLAIM_LOGS" ("LINE_ID") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_LOGS_REPORT_REQUEST_ID_IDX1" ON "CHM_MSI_CLAIM_LOGS" ("REPORT_REQUEST_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_MSI_CLAIM_LOGS" 
BEFORE INSERT OR UPDATE ON CHM_MSI_CLAIM_LOGS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.BATCH_LOG_ID IS NULL THEN
            :NEW.BATCH_LOG_ID := CHM_MSI_CLAIM_LOGS_SEQ.NEXTVAL;
        END IF;
        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATED_DATE  := NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP) ;
        :NEW.SOURCE_APP_ID      := NVL(:NEW.SOURCE_APP_ID, CHM_UTIL_PKG.GETSOURCEAPP('CHM'));
        :NEW.ENTERPRISE_ID      := NVL(:NEW.ENTERPRISE_ID, CHM_CONST_PKG.GETENTERPRISEID());
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());

      ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATED_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATED_DATE != :NEW.LAST_UPDATED_DATE THEN
                    :NEW.LAST_UPDATED_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

      END IF;
   END;



/
ALTER TRIGGER "BIU_CHM_MSI_CLAIM_LOGS" ENABLE;