
  CREATE TABLE "CHM_MSI_SPA_HEADER" 
   (	"CHM_SPA_ID" NUMBER DEFAULT CHM.CHM_MSI_SPA_HEADERS_SEQ.NEXTVAL, 
	"SPA_NUMBER" VARCHAR2(4000), 
	"OPPORTUNITY_OWNER" VARCHAR2(4000), 
	"INSTALLER_ACCOUNT_NAME" VARCHAR2(4000), 
	"INSTALLER_CUSTOMER_KEY" VARCHAR2(4000), 
	"PRIMARY_PARTNER" VARCHAR2(4000), 
	"SPA_NAME" VARCHAR2(4000), 
	"GEOGRAPHY" VARCHAR2(4000), 
	"STAGE" VARCHAR2(4000), 
	"OPPORTUNITY_NAME" VARCHAR2(4000), 
	"DEAL_LOGISTICS" VARCHAR2(4000), 
	"STATUS" VARCHAR2(4000), 
	"SPECIAL_PRICING_TYPE" VARCHAR2(4000), 
	"FINAL_APPROVAL_TIME" VARCHAR2(4000), 
	"SPA_START_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SPA_EXPIRATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"DEAL_CATEGORY" VARCHAR2(4000), 
	"SPA_TOTAL_PRICE_CURRENCY" VARCHAR2(4000), 
	"SPA_TOTAL_PRICE" NUMBER, 
	"SPA_CREATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SPA_TYPE" VARCHAR2(4000), 
	"SPA_BACK_DATED" VARCHAR2(4000), 
	"ID" VARCHAR2(4000), 
	"OPPORTUNITY_OWNER_ID" VARCHAR2(4000), 
	"SPA_OPPORTUNITY_ID" VARCHAR2(4000), 
	"ACCOUNT_ID" VARCHAR2(4000), 
	"NEW_RENEWAL" VARCHAR2(4000), 
	"DISTRIBUTOR_ACCOUNT_NAME" VARCHAR2(4000), 
	"DISTRIBUTOR_SFDC_ID" VARCHAR2(4000), 
	"DISTRIBUTOR_ORACLE_ACCOUNT_ID" VARCHAR2(4000), 
	"DISTRIBUTOR_SFDC_CUSTOMER_KEY" VARCHAR2(4000), 
	"SPA_LAST_UPDATE_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SPA_CREATED_BY" VARCHAR2(4000), 
	"SPA_LAST_UPDATED_BY" VARCHAR2(4000), 
	"SPA_FINAL_APPROVAL_DATE_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"SPA_CONTACT" VARCHAR2(4000), 
	"SPA_TIERS" NUMBER, 
	"TIER1_MIN" NUMBER, 
	"TIER2_MIN" NUMBER, 
	"TIER3_MIN" NUMBER, 
	"TIER4_MIN" NUMBER, 
	"TIER5_MIN" NUMBER, 
	"TIER1_MAX" NUMBER, 
	"TIER2_MAX" NUMBER, 
	"TIER3_MAX" NUMBER, 
	"TIER4_MAX" NUMBER, 
	"TIER5_MAX" NUMBER, 
	"ATTRIBUTE_CONTEXT" VARCHAR2(4000), 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"ATTRIBUTE11" VARCHAR2(4000), 
	"ATTRIBUTE12" VARCHAR2(4000), 
	"ATTRIBUTE13" VARCHAR2(4000), 
	"ATTRIBUTE14" VARCHAR2(4000), 
	"ATTRIBUTE15" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(4000), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(4000), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SOURCE_APP_ID" NUMBER, 
	"ENTERPRISE_ID" NUMBER, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000), 
	"OIC_INSTANCE_ID" VARCHAR2(4000), 
	 CONSTRAINT "CHM_MSI_SPA_HEADER_PK" PRIMARY KEY ("CHM_SPA_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "CHM_MSI_SPA_HEADER_ID_IDX" ON "CHM_MSI_SPA_HEADER" ("ID") 
  ;

  CREATE INDEX "CHM_MSI_SPA_HEADER_SPA_NUMBER_IDX" ON "CHM_MSI_SPA_HEADER" ("SPA_NUMBER") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_MSI_SPA_HEADER_TRG" 
  BEFORE INSERT OR UPDATE ON CHM_MSI_SPA_HEADER
  FOR EACH ROW
   BEGIN
      IF INSERTING THEN
        IF :new.CHM_SPA_ID  IS NULL THEN
            :new.CHM_SPA_ID   := CHM_MSI_SPA_HEADERS_SEQ.NEXTVAL;
        END IF;

       -- :NEW.attribute10 := chm_util_pkg.removespecialwords(:NEW.NAME);

        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATED_DATE   := NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP) ;
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());

        --We need to capture SYSDATE when CHM gets an update on Site 
        --where the stage crosses 3
        --Attribute 1 stores the date we captured that site crossed stage 3

       /* IF NVL(:NEW.STAGE,0) >=3 THEN
          :NEW.ATTRIBUTE1 := TO_CHAR(SYSTIMESTAMP);
        END IF; */


      ELSIF updating THEN
        --We need to capture SYSDATE when CHM gets an update on Site 
        --where the stage crosses 3
        -- We dont wnat to update if ATTRIBUTE1 already cpatured this date earlier
        --so checking that OLD value is NULL and OLD stage is < 3 and new stage >=3

        --Attribute 1 stores the date we captured that site crossed stage 3

      /*  IF :OLD.ATTRIBUTE1 IS NULL AND NVL(:OLD.STAGE,0)< 3 AND NVL(:NEW.STAGE,0) >=3 THEN
          :NEW.ATTRIBUTE1 := TO_CHAR(SYSTIMESTAMP);
        END IF; */

        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATED_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATED_DATE != :NEW.LAST_UPDATED_DATE THEN
                    :NEW.LAST_UPDATED_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

        --:NEW.attribute10 := chm_util_pkg.removespecialwords(:NEW.NAME);
              END IF;
       EXCEPTION
  WHEN OTHERS THEN
    chm_msi_debug_api.log_msg(:new.CHM_SPA_ID || ', ' || :new.SPA_NUMBER, 'BIU_CHM_MSI_SPA_HEADER_TRG', SQLERRM);
    END;
/
ALTER TRIGGER "BIU_CHM_MSI_SPA_HEADER_TRG" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "AIU_CHM_MSI_SPA_HEADER_TRG" AFTER
    INSERT OR UPDATE OR DELETE ON chm_msi_spa_header
    FOR EACH ROW
BEGIN
    IF inserting THEN
        INSERT INTO chm_msi_spa_header_audit (
            chm_spa_audit_id,
            chm_spa_id,
            old_spa_number,
            new_spa_number,
            old_opportunity_owner,
            new_opportunity_owner,
            old_installer_account_name,
            new_installer_account_name,
            old_installer_customer_key,
            new_installer_customer_key,
            old_primary_partner,
            new_primary_partner,
            old_spa_name,
            new_spa_name,
            old_geography,
            new_geography,
            old_stage,
            new_stage,
            old_opportunity_name,
            new_opportunity_name,
            old_deal_logistics,
            new_deal_logistics,
            old_status,
            new_status,
            old_special_pricing_type,
            new_special_pricing_type,
            old_final_approval_time,
            new_final_approval_time,
            old_spa_start_date,
            new_spa_start_date,
            old_spa_expiration_date,
            new_spa_expiration_date,
            old_deal_category,
            new_deal_category,
            old_spa_total_price_currency,
            new_spa_total_price_currency,
            old_spa_total_price,
            new_spa_total_price,
            old_spa_created_date,
            new_spa_created_date,
            old_spa_type,
            new_spa_type,
            old_spa_back_dated,
            new_spa_back_dated,
            old_id,
            new_id,
            old_opportunity_owner_id,
            new_opportunity_owner_id,
            old_spa_opportunity_id,
            new_spa_opportunity_id,
            old_account_id,
            new_account_id,
            old_new_renewal,
            new_new_renewal,
            old_distributor_account_name,
            new_distributor_account_name,
            old_distributor_sfdc_id,
            new_distributor_sfdc_id,
            old_distributor_oracle_account_id,
            new_distributor_oracle_account_id,
            old_distributor_sfdc_customer_key,
            new_distributor_sfdc_customer_key,
            old_spa_last_update_date,
            new_spa_last_update_date,
            old_spa_created_by,
            new_spa_created_by,
            old_spa_last_updated_by,
            new_spa_last_updated_by,
            old_spa_final_approval_date_time,
            new_spa_final_approval_date_time,
            old_spa_contact,
            new_spa_contact,
            old_spa_tiers,
            new_spa_tiers,
            old_tier1_min,
            new_tier1_min,
            old_tier2_min,
            new_tier2_min,
            old_tier3_min,
            new_tier3_min,
            old_tier4_min,
            new_tier4_min,
            old_tier5_min,
            new_tier5_min,
            old_tier1_max,
            new_tier1_max,
            old_tier2_max,
            new_tier2_max,
            old_tier3_max,
            new_tier3_max,
            old_tier4_max,
            new_tier4_max,
            old_tier5_max,
            new_tier5_max,
            new_attribute_context,
            new_attribute1,
            new_attribute2,
            new_attribute3,
            new_attribute4,
            new_attribute5,
            new_attribute6,
            new_attribute7,
            new_attribute8,
            new_attribute9,
            new_attribute10,
            new_attribute11,
            new_attribute12,
            new_attribute13,
            new_attribute14,
            new_attribute15,
            new_created_by,
            new_creation_date,
            new_last_updated_by,
            new_last_updated_date,
            new_source_app_id,
            new_enterprise_id,
            new_ip_address,
            new_user_agent,
			CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,
			SOURCE_APP_ID ,   
			ENTERPRISE_ID,    
			IP_ADDRESS,       
			USER_AGENT       
        ) VALUES (
            chm_msi_spa_header_audit_seq.NEXTVAL,
            :new.chm_spa_id,
            :old.spa_number,
            :new.spa_number,
            :old.opportunity_owner,
            :new.opportunity_owner,
            :old.installer_account_name,
            :new.installer_account_name,
            :old.installer_customer_key,
            :new.installer_customer_key,
            :old.primary_partner,
            :new.primary_partner,
            :old.spa_name,
            :new.spa_name,
            :old.geography,
            :new.geography,
            :old.stage,
            :new.stage,
            :old.opportunity_name,
            :new.opportunity_name,
            :old.deal_logistics,
            :new.deal_logistics,
            :old.status,
            :new.status,
            :old.special_pricing_type,
            :new.special_pricing_type,
            :old.final_approval_time,
            :new.final_approval_time,
            :old.spa_start_date,
            :new.spa_start_date,
            :old.spa_expiration_date,
            :new.spa_expiration_date,
            :old.deal_category,
            :new.deal_category,
            :old.spa_total_price_currency,
            :new.spa_total_price_currency,
            :old.spa_total_price,
            :new.spa_total_price,
            :old.spa_created_date,
            :new.spa_created_date,
            :old.spa_type,
            :new.spa_type,
            :old.spa_back_dated,
            :new.spa_back_dated,
            :old.id,
            :new.id,
            :old.opportunity_owner_id,
            :new.opportunity_owner_id,
            :old.spa_opportunity_id,
            :new.spa_opportunity_id,
            :old.account_id,
            :new.account_id,
            :old.new_renewal,
            :new.new_renewal,
            :old.distributor_account_name,
            :new.distributor_account_name,
            :old.distributor_sfdc_id,
            :new.distributor_sfdc_id,
            :old.distributor_oracle_account_id,
            :new.distributor_oracle_account_id,
            :old.distributor_sfdc_customer_key,
            :new.distributor_sfdc_customer_key,
            :old.spa_last_update_date,
            :new.spa_last_update_date,
            :old.spa_created_by,
            :new.spa_created_by,
            :old.spa_last_updated_by,
            :new.spa_last_updated_by,
            :old.spa_final_approval_date_time,
            :new.spa_final_approval_date_time,
            :old.spa_contact,
            :new.spa_contact,
            :old.spa_tiers,
            :new.spa_tiers,
            :old.tier1_min,
            :new.tier1_min,
            :old.tier2_min,
            :new.tier2_min,
            :old.tier3_min,
            :new.tier3_min,
            :old.tier4_min,
            :new.tier4_min,
            :old.tier5_min,
            :new.tier5_min,
            :old.tier1_max,
            :new.tier1_max,
            :old.tier2_max,
            :new.tier2_max,
            :old.tier3_max,
            :new.tier3_max,
            :old.tier4_max,
            :new.tier4_max,
            :old.tier5_max,
            :new.tier5_max,
            :new.attribute_context,
            :new.attribute1,
            :new.attribute2,
            :new.attribute3,
            :new.attribute4,
            :new.attribute5,
            :new.attribute6,
            :new.attribute7,
            :new.attribute8,
            :new.attribute9,
            :new.attribute10,
            :new.attribute11,
            :new.attribute12,
            :new.attribute13,
            :new.attribute14,
            :new.attribute15,
            :new.created_by,
            :new.creation_date,
            :new.last_updated_by,
            :new.last_updated_date,
            :new.source_app_id,
            :new.enterprise_id,
            :new.ip_address,
            :new.user_agent,
			NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP),
			NVL(:NEW.SOURCE_APP_ID, CHM_UTIL_PKG.GETSOURCEAPP('CHM')),
			NVL(:NEW.ENTERPRISE_ID, CHM_CONST_PKG.GETENTERPRISEID()),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())	
        );
        END IF;

    IF updating THEN
        INSERT INTO chm_msi_spa_header_audit (
            chm_spa_audit_id,
            chm_spa_id,
            old_spa_number,
            new_spa_number,
            old_opportunity_owner,
            new_opportunity_owner,
            old_installer_account_name,
            new_installer_account_name,
            old_installer_customer_key,
            new_installer_customer_key,
            old_primary_partner,
            new_primary_partner,
            old_spa_name,
            new_spa_name,
            old_geography,
            new_geography,
            old_stage,
            new_stage,
            old_opportunity_name,
            new_opportunity_name,
            old_deal_logistics,
            new_deal_logistics,
            old_status,
            new_status,
            old_special_pricing_type,
            new_special_pricing_type,
            old_final_approval_time,
            new_final_approval_time,
            old_spa_start_date,
            new_spa_start_date,
            old_spa_expiration_date,
            new_spa_expiration_date,
            old_deal_category,
            new_deal_category,
            old_spa_total_price_currency,
            new_spa_total_price_currency,
            old_spa_total_price,
            new_spa_total_price,
            old_spa_created_date,
            new_spa_created_date,
            old_spa_type,
            new_spa_type,
            old_spa_back_dated,
            new_spa_back_dated,
            old_id,
            new_id,
            old_opportunity_owner_id,
            new_opportunity_owner_id,
            old_spa_opportunity_id,
            new_spa_opportunity_id,
            old_account_id,
            new_account_id,
            old_new_renewal,
            new_new_renewal,
            old_distributor_account_name,
            new_distributor_account_name,
            old_distributor_sfdc_id,
            new_distributor_sfdc_id,
            old_distributor_oracle_account_id,
            new_distributor_oracle_account_id,
            old_distributor_sfdc_customer_key,
            new_distributor_sfdc_customer_key,
            old_spa_last_update_date,
            new_spa_last_update_date,
            old_spa_created_by,
            new_spa_created_by,
            old_spa_last_updated_by,
            new_spa_last_updated_by,
            old_spa_final_approval_date_time,
            new_spa_final_approval_date_time,
            old_spa_contact,
            new_spa_contact,
            old_spa_tiers,
            new_spa_tiers,
            old_tier1_min,
            new_tier1_min,
            old_tier2_min,
            new_tier2_min,
            old_tier3_min,
            new_tier3_min,
            old_tier4_min,
            new_tier4_min,
            old_tier5_min,
            new_tier5_min,
            old_tier1_max,
            new_tier1_max,
            old_tier2_max,
            new_tier2_max,
            old_tier3_max,
            new_tier3_max,
            old_tier4_max,
            new_tier4_max,
            old_tier5_max,
            new_tier5_max,
            new_attribute_context,
            new_attribute1,
            new_attribute2,
            new_attribute3,
            new_attribute4,
            new_attribute5,
            new_attribute6,
            new_attribute7,
            new_attribute8,
            new_attribute9,
            new_attribute10,
            new_attribute11,
            new_attribute12,
            new_attribute13,
            new_attribute14,
            new_attribute15,
            new_created_by,
            new_creation_date,
            new_last_updated_by,
            new_last_updated_date,
            new_source_app_id,
            new_enterprise_id,
            new_ip_address,
            new_user_agent,
			old_attribute_context,
            old_attribute1,
            old_attribute2,
            old_attribute3,
            old_attribute4,
            old_attribute5,
            old_attribute6,
            old_attribute7,
            old_attribute8,
            old_attribute9,
            old_attribute10,
            old_attribute11,
            old_attribute12,
            old_attribute13,
            old_attribute14,
            old_attribute15,
            old_created_by,
            old_creation_date,
            old_last_updated_by,
            old_last_updated_date,
            old_source_app_id,
            old_enterprise_id,
            old_ip_address,
            old_user_agent,
			CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,
			SOURCE_APP_ID ,   
			ENTERPRISE_ID,    
			IP_ADDRESS,       
			USER_AGENT 
        ) VALUES (
            chm_msi_spa_header_audit_seq.NEXTVAL,
            :old.chm_spa_id,
            :old.spa_number,
            :new.spa_number,
            :old.opportunity_owner,
            :new.opportunity_owner,
            :old.installer_account_name,
            :new.installer_account_name,
            :old.installer_customer_key,
            :new.installer_customer_key,
            :old.primary_partner,
            :new.primary_partner,
            :old.spa_name,
            :new.spa_name,
            :old.geography,
            :new.geography,
            :old.stage,
            :new.stage,
            :old.opportunity_name,
            :new.opportunity_name,
            :old.deal_logistics,
            :new.deal_logistics,
            :old.status,
            :new.status,
            :old.special_pricing_type,
            :new.special_pricing_type,
            :old.final_approval_time,
            :new.final_approval_time,
            :old.spa_start_date,
            :new.spa_start_date,
            :old.spa_expiration_date,
            :new.spa_expiration_date,
            :old.deal_category,
            :new.deal_category,
            :old.spa_total_price_currency,
            :new.spa_total_price_currency,
            :old.spa_total_price,
            :new.spa_total_price,
            :old.spa_created_date,
            :new.spa_created_date,
            :old.spa_type,
            :new.spa_type,
            :old.spa_back_dated,
            :new.spa_back_dated,
            :old.id,
            :new.id,
            :old.opportunity_owner_id,
            :new.opportunity_owner_id,
            :old.spa_opportunity_id,
            :new.spa_opportunity_id,
            :old.account_id,
            :new.account_id,
            :old.new_renewal,
            :new.new_renewal,
            :old.distributor_account_name,
            :new.distributor_account_name,
            :old.distributor_sfdc_id,
            :new.distributor_sfdc_id,
            :old.distributor_oracle_account_id,
            :new.distributor_oracle_account_id,
            :old.distributor_sfdc_customer_key,
            :new.distributor_sfdc_customer_key,
            :old.spa_last_update_date,
            :new.spa_last_update_date,
            :old.spa_created_by,
            :new.spa_created_by,
            :old.spa_last_updated_by,
            :new.spa_last_updated_by,
            :old.spa_final_approval_date_time,
            :new.spa_final_approval_date_time,
            :old.spa_contact,
            :new.spa_contact,
            :old.spa_tiers,
            :new.spa_tiers,
            :old.tier1_min,
            :new.tier1_min,
            :old.tier2_min,
            :new.tier2_min,
            :old.tier3_min,
            :new.tier3_min,
            :old.tier4_min,
            :new.tier4_min,
            :old.tier5_min,
            :new.tier5_min,
            :old.tier1_max,
            :new.tier1_max,
            :old.tier2_max,
            :new.tier2_max,
            :old.tier3_max,
            :new.tier3_max,
            :old.tier4_max,
            :new.tier4_max,
            :old.tier5_max,
            :new.tier5_max,
            :new.attribute_context,
            :new.attribute1,
            :new.attribute2,
            :new.attribute3,
            :new.attribute4,
            :new.attribute5,
            :new.attribute6,
            :new.attribute7,
            :new.attribute8,
            :new.attribute9,
            :new.attribute10,
            :new.attribute11,
            :new.attribute12,
            :new.attribute13,
            :new.attribute14,
            :new.attribute15,
            :new.created_by,
            :new.creation_date,
            :new.last_updated_by,
            :new.last_updated_date,
            :new.source_app_id,
            :new.enterprise_id,
            :new.ip_address,
            :new.user_agent,
			:old.attribute_context,
            :old.attribute1,
            :old.attribute2,
            :old.attribute3,
            :old.attribute4,
            :old.attribute5,
            :old.attribute6,
            :old.attribute7,
            :old.attribute8,
            :old.attribute9,
            :old.attribute10,
            :old.attribute11,
            :old.attribute12,
            :old.attribute13,
            :old.attribute14,
            :old.attribute15,
            :old.created_by,
            :old.creation_date,
            :old.last_updated_by,
            :old.last_updated_date,
            :old.source_app_id,
            :old.enterprise_id,
            :old.ip_address,
            :old.user_agent,
			NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP),
			NVL(:NEW.SOURCE_APP_ID, CHM_UTIL_PKG.GETSOURCEAPP('CHM')),
			NVL(:NEW.ENTERPRISE_ID, CHM_CONST_PKG.GETENTERPRISEID()),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );
        END IF;
    IF deleting THEN
        INSERT INTO chm_msi_spa_header_audit (
            chm_spa_audit_id,
            chm_spa_id,
            old_spa_number,
            new_spa_number,
            old_opportunity_owner,
            new_opportunity_owner,
            old_installer_account_name,
            new_installer_account_name,
            old_installer_customer_key,
            new_installer_customer_key,
            old_primary_partner,
            new_primary_partner,
            old_spa_name,
            new_spa_name,
            old_geography,
            new_geography,
            old_stage,
            new_stage,
            old_opportunity_name,
            new_opportunity_name,
            old_deal_logistics,
            new_deal_logistics,
            old_status,
            new_status,
            old_special_pricing_type,
            new_special_pricing_type,
            old_final_approval_time,
            new_final_approval_time,
            old_spa_start_date,
            new_spa_start_date,
            old_spa_expiration_date,
            new_spa_expiration_date,
            old_deal_category,
            new_deal_category,
            old_spa_total_price_currency,
            new_spa_total_price_currency,
            old_spa_total_price,
            new_spa_total_price,
            old_spa_created_date,
            new_spa_created_date,
            old_spa_type,
            new_spa_type,
            old_spa_back_dated,
            new_spa_back_dated,
            old_id,
            new_id,
            old_opportunity_owner_id,
            new_opportunity_owner_id,
            old_spa_opportunity_id,
            new_spa_opportunity_id,
            old_account_id,
            new_account_id,
            old_new_renewal,
            new_new_renewal,
            old_distributor_account_name,
            new_distributor_account_name,
            old_distributor_sfdc_id,
            new_distributor_sfdc_id,
            old_distributor_oracle_account_id,
            new_distributor_oracle_account_id,
            old_distributor_sfdc_customer_key,
            new_distributor_sfdc_customer_key,
            old_spa_last_update_date,
            new_spa_last_update_date,
            old_spa_created_by,
            new_spa_created_by,
            old_spa_last_updated_by,
            new_spa_last_updated_by,
            old_spa_final_approval_date_time,
            new_spa_final_approval_date_time,
            old_spa_contact,
            new_spa_contact,
            old_spa_tiers,
            new_spa_tiers,
            old_tier1_min,
            new_tier1_min,
            old_tier2_min,
            new_tier2_min,
            old_tier3_min,
            new_tier3_min,
            old_tier4_min,
            new_tier4_min,
            old_tier5_min,
            new_tier5_min,
            old_tier1_max,
            new_tier1_max,
            old_tier2_max,
            new_tier2_max,
            old_tier3_max,
            new_tier3_max,
            old_tier4_max,
            new_tier4_max,
            old_tier5_max,
            new_tier5_max,
            old_attribute_context,
            old_attribute1,
            old_attribute2,
            old_attribute3,
            old_attribute4,
            old_attribute5,
            old_attribute6,
            old_attribute7,
            old_attribute8,
            old_attribute9,
            old_attribute10,
            old_attribute11,
            old_attribute12,
            old_attribute13,
            old_attribute14,
            old_attribute15,
            old_created_by,
            old_creation_date,
            old_last_updated_by,
            old_last_updated_date,
            old_source_app_id,
            old_enterprise_id,
            old_ip_address,
            old_user_agent,
			CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,
			SOURCE_APP_ID ,   
			ENTERPRISE_ID,    
			IP_ADDRESS,       
			USER_AGENT 
        ) VALUES (
            chm_msi_spa_header_audit_seq.NEXTVAL,
            :old.chm_spa_id,
            :old.spa_number,
            :new.spa_number,
            :old.opportunity_owner,
            :new.opportunity_owner,
            :old.installer_account_name,
            :new.installer_account_name,
            :old.installer_customer_key,
            :new.installer_customer_key,
            :old.primary_partner,
            :new.primary_partner,
            :old.spa_name,
            :new.spa_name,
            :old.geography,
            :new.geography,
            :old.stage,
            :new.stage,
            :old.opportunity_name,
            :new.opportunity_name,
            :old.deal_logistics,
            :new.deal_logistics,
            :old.status,
            :new.status,
            :old.special_pricing_type,
            :new.special_pricing_type,
            :old.final_approval_time,
            :new.final_approval_time,
            :old.spa_start_date,
            :new.spa_start_date,
            :old.spa_expiration_date,
            :new.spa_expiration_date,
            :old.deal_category,
            :new.deal_category,
            :old.spa_total_price_currency,
            :new.spa_total_price_currency,
            :old.spa_total_price,
            :new.spa_total_price,
            :old.spa_created_date,
            :new.spa_created_date,
            :old.spa_type,
            :new.spa_type,
            :old.spa_back_dated,
            :new.spa_back_dated,
            :old.id,
            :new.id,
            :old.opportunity_owner_id,
            :new.opportunity_owner_id,
            :old.spa_opportunity_id,
            :new.spa_opportunity_id,
            :old.account_id,
            :new.account_id,
            :old.new_renewal,
            :new.new_renewal,
            :old.distributor_account_name,
            :new.distributor_account_name,
            :old.distributor_sfdc_id,
            :new.distributor_sfdc_id,
            :old.distributor_oracle_account_id,
            :new.distributor_oracle_account_id,
            :old.distributor_sfdc_customer_key,
            :new.distributor_sfdc_customer_key,
            :old.spa_last_update_date,
            :new.spa_last_update_date,
            :old.spa_created_by,
            :new.spa_created_by,
            :old.spa_last_updated_by,
            :new.spa_last_updated_by,
            :old.spa_final_approval_date_time,
            :new.spa_final_approval_date_time,
            :old.spa_contact,
            :new.spa_contact,
            :old.spa_tiers,
            :new.spa_tiers,
            :old.tier1_min,
            :new.tier1_min,
            :old.tier2_min,
            :new.tier2_min,
            :old.tier3_min,
            :new.tier3_min,
            :old.tier4_min,
            :new.tier4_min,
            :old.tier5_min,
            :new.tier5_min,
            :old.tier1_max,
            :new.tier1_max,
            :old.tier2_max,
            :new.tier2_max,
            :old.tier3_max,
            :new.tier3_max,
            :old.tier4_max,
            :new.tier4_max,
            :old.tier5_max,
            :new.tier5_max,
            :old.attribute_context,
            :old.attribute1,
            :old.attribute2,
            :old.attribute3,
            :old.attribute4,
            :old.attribute5,
            :old.attribute6,
            :old.attribute7,
            :old.attribute8,
            :old.attribute9,
            :old.attribute10,
            :old.attribute11,
            :old.attribute12,
            :old.attribute13,
            :old.attribute14,
            :old.attribute15,
            :old.created_by,
            :old.creation_date,
            :old.last_updated_by,
            :old.last_updated_date,
            :old.source_app_id,
            :old.enterprise_id,
            :old.ip_address,
            :old.user_agent,
			NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP),
			NVL(:NEW.SOURCE_APP_ID, CHM_UTIL_PKG.GETSOURCEAPP('CHM')),
			NVL(:NEW.ENTERPRISE_ID, CHM_CONST_PKG.GETENTERPRISEID()),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    END IF;
END;
/
ALTER TRIGGER "AIU_CHM_MSI_SPA_HEADER_TRG" ENABLE;