
  CREATE TABLE "CHM_MSI_CLAIM_REBATES_REPORT" 
   (	"REPORT_ID" NUMBER, 
	"REPORT_REQUEST_ID" NUMBER, 
	"CHM_DEVICE_REBATE_ID" NUMBER, 
	"CHM_ENLIGHTEN_DEVICE_ID" NUMBER NOT NULL ENABLE, 
	"SPA_NUMBER" VARCHAR2(4000) NOT NULL ENABLE, 
	"SPA_LINE_ID" NUMBER NOT NULL ENABLE, 
	"SERIAL_NUMBER" NUMBER, 
	"HW_PART_NUM" VARCHAR2(4000), 
	"DEVICE_CREATED_DATE" VARCHAR2(4000), 
	"DEVICE_FIRST_INTERVAL_END_DATE" VARCHAR2(4000), 
	"PRODUCT_TYPE" VARCHAR2(4000), 
	"PRODUCT_FAMILY" VARCHAR2(4000), 
	"DEVICE_ITEM_NUMBER" VARCHAR2(4000) NOT NULL ENABLE, 
	"REBATE_ITEM_NUMBER" VARCHAR2(4000) NOT NULL ENABLE, 
	"REBATE_TYPE" VARCHAR2(4000) NOT NULL ENABLE, 
	"REBATE_TIER" VARCHAR2(4000), 
	"SPA_ORIGINAL_AMOUNT" NUMBER, 
	"CLAIM_DATE" DATE NOT NULL ENABLE, 
	"REBATE_CURRENCY" VARCHAR2(4000) NOT NULL ENABLE, 
	"REBATE_AMOUNT" NUMBER NOT NULL ENABLE, 
	"REBATE_SOURCE" VARCHAR2(4000) NOT NULL ENABLE, 
	"REBATE_STATUS" VARCHAR2(4000) NOT NULL ENABLE, 
	"CLAIM_BATCH_ID" NUMBER, 
	"CLAIM_LINE_ID" NUMBER, 
	"REBATE_PAYEE_TYPE" VARCHAR2(4000) NOT NULL ENABLE, 
	"REBATE_PAYEE_ID" NUMBER NOT NULL ENABLE, 
	"REBATE_PAYEE_NAME" VARCHAR2(4000), 
	"REBATE_PAYEE_CUSTOMER_KEY" VARCHAR2(4000), 
	"REBATE_PAYEE_COUNTRY" VARCHAR2(4000), 
	"REBATE_PAYEE_GEOGRAPHY" VARCHAR2(4000), 
	"REBATE_PAYEE_ACCOUNT_OWNER" VARCHAR2(4000), 
	"REBATE_PAYEE_ENLIGHTEN_INSTALLER_ID" NUMBER, 
	"DISTI_ORACLE_ACCOUNT_NUMBER" VARCHAR2(4000), 
	"DISTI_SFDC_KEY" VARCHAR2(4000), 
	"DISTI_ORACLE_NAME" VARCHAR2(4000), 
	"ORACLE_ORDER_TYPE" VARCHAR2(4000), 
	"ENLIGHTEN_SITE_ID" NUMBER, 
	"ENLIGHTEN_SITE_NAME" VARCHAR2(4000), 
	"ENLIGHTEN_SITE_TYPE" VARCHAR2(4000), 
	"OWNER_ID" NUMBER, 
	"INSTALLER_ID" NUMBER, 
	"MAINTAINER_ID" NUMBER, 
	"SITE_FIRST_INTERVAL_END_DATE" VARCHAR2(4000), 
	"PCU_CHANNEL_COUNT" NUMBER, 
	"ENVOY_COUNT" NUMBER, 
	"ACB_COUNT" NUMBER, 
	"NSR_COUNT" NUMBER, 
	"ENCHARGE_COUNT" NUMBER, 
	"ENPOWER_COUNT" NUMBER, 
	"PCU_TYPES" VARCHAR2(4000), 
	"STATUS_CODE" VARCHAR2(4000), 
	"AC_VOLTAGE" VARCHAR2(4000), 
	"SITE_CREATED_DATE" VARCHAR2(4000), 
	"MEASURED_ACV" VARCHAR2(4000), 
	"IS_LEASE" VARCHAR2(4000), 
	"PARTNER_ID" NUMBER, 
	"SYSTEM_HOST_ID" NUMBER, 
	"ENLIGHTEN_SITE_URL" VARCHAR2(4000), 
	"SITE_CURRENT_STAGE" NUMBER, 
	"STAGE_3_STATUS_DATE" DATE, 
	"SYSTEM_START_DATE" VARCHAR2(4000), 
	"ZERO_TOUCH" VARCHAR2(4000), 
	"ALLOW_API_ACCESS" VARCHAR2(4000), 
	"LOCATION_ACCESS" VARCHAR2(4000), 
	"RATE_SCHEDULE" VARCHAR2(4000), 
	"DESCRIPTION" VARCHAR2(4000), 
	"OPERATIONAL" VARCHAR2(4000), 
	"INTERCONNECT_DATE" VARCHAR2(4000), 
	"INTERNET_CONNECTION_TYPE" VARCHAR2(4000), 
	"PCU_ATTACHMENT_TYPE" VARCHAR2(4000), 
	"CONNECTION_TYPE" VARCHAR2(4000), 
	"SFDC_DRIP_CAMPAIGN_FLAG" VARCHAR2(4000), 
	"IQEVC_COUNT" NUMBER, 
	"CONSUMPTION_CT" VARCHAR2(4000), 
	"HEMS" VARCHAR2(4000), 
	"ADDRESS_ID" VARCHAR2(4000), 
	"ADDRESS_1" VARCHAR2(4000), 
	"ADDRESS_2" VARCHAR2(4000), 
	"ADDRESS_CITY" VARCHAR2(4000), 
	"ADDRESS_STATE" VARCHAR2(4000), 
	"ADDRESS_ZIP" VARCHAR2(4000), 
	"ADDRESS_COUNTRY" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(4000), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(4000), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000), 
	"ATTRIBUTE_CONTEXT" VARCHAR2(4000), 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"ATTRIBUTE11" VARCHAR2(4000), 
	"ATTRIBUTE12" VARCHAR2(4000), 
	"ATTRIBUTE13" VARCHAR2(4000), 
	"ATTRIBUTE14" VARCHAR2(4000), 
	"ATTRIBUTE15" VARCHAR2(4000), 
	"CHM_ENLIGHTEN_SITE_ID" NUMBER, 
	"ORACLE_AP_INVOICE_NUMBER" VARCHAR2(4000), 
	"ORACLE_AP_INVOICE_ID" VARCHAR2(4000)
   ) ;

  CREATE INDEX "CHM_MSI_CLAIM_REBATES_REPORT_REQUEST_ID_IDX" ON "CHM_MSI_CLAIM_REBATES_REPORT" ("REPORT_REQUEST_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_MSI_CLAIM_REBATES_REPORT" 
  BEFORE INSERT OR UPDATE ON CHM_MSI_CLAIM_REBATES_REPORT
  FOR EACH ROW
   BEGIN
      IF INSERTING THEN
        IF :new.REPORT_ID  IS NULL THEN
            :new.REPORT_ID   := CHM_CLAIM_ACCRUAL_REPORT_SEQ.NEXTVAL;
        END IF; 

       -- :NEW.attribute10 := chm_util_pkg.removespecialwords(:NEW.TYPE);

        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATE_DATE   := NVL(:NEW.LAST_UPDATE_DATE ,SYSTIMESTAMP) ;
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());

      ELSIF updating THEN
        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATE_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATE_DATE != :NEW.LAST_UPDATE_DATE THEN
                    :NEW.LAST_UPDATE_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

        --:NEW.attribute10 := chm_util_pkg.removespecialwords(:NEW.TYPE);
              END IF;
       EXCEPTION
  WHEN OTHERS THEN
    CHM_MSI_DEBUG_API.log_msg(:new.REPORT_ID, 'BIU_CHM_MSI_CLAIM_REBATES_REPORT', SQLERRM);
    END;
/
ALTER TRIGGER "BIU_CHM_MSI_CLAIM_REBATES_REPORT" ENABLE;