
  CREATE TABLE "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" 
   (	"CHM_DEVICE_ATTRIBUTE_ID" NUMBER DEFAULT CHM.CHM_ENLIGHTEN_DEVICE_DETAILS_SEQ.NEXTVAL, 
	"CHM_ENLIGHTEN_DEVICE_ID" NUMBER NOT NULL ENABLE, 
	"SITE_ID" NUMBER NOT NULL ENABLE, 
	"DISTI_ORACLE_ACCOUNT_NUMBER" VARCHAR2(4000), 
	"DISTI_ORACLE_ACCOUNT_ID" NUMBER, 
	"DISTI_SFDC_KEY" VARCHAR2(4000), 
	"ORACLE_ORDER_TYPE" VARCHAR2(4000), 
	"ITEM_NUMBER" VARCHAR2(4000) NOT NULL ENABLE, 
	"SERIAL_NUM" VARCHAR2(4000), 
	"PRODUCT_FAMILY" VARCHAR2(4000), 
	"PRODUCT_TYPE" VARCHAR2(4000), 
	"REBATE_EFFECTIVE_DATE" DATE, 
	"DEVICE_QUANTITY" NUMBER NOT NULL ENABLE, 
	"MSI_REBATE_ELIGIBLE" VARCHAR2(4000) DEFAULT 'N' NOT NULL ENABLE, 
	"MSI_REBATE_ELIGIBILE_REASON" VARCHAR2(4000), 
	"MSI_REBATE_ELIGIBILITY_DERIVED_DATE" DATE, 
	"UNIT_ACTIVATION_SPA_NUMBER" VARCHAR2(4000), 
	"UNIT_ACTIVATION_REBATE_ITEM_NUMBER" VARCHAR2(4000), 
	"UNIT_ACTIVATION_SPA_LINE_ID" NUMBER, 
	"UNIT_ACTIVATION_REBATE_AMOUNT" NUMBER, 
	"UNIT_ACTIVATION_REBATE_ELIGIBILE_REASON" VARCHAR2(4000), 
	"UNIT_ACTIVATION_PAYEE_TYPE" VARCHAR2(4000), 
	"UNIT_ACTIVATION_PAYEE_ID" NUMBER, 
	"SYSTEM_ATTACHMENT_SPA_NUMBER" VARCHAR2(4000), 
	"SYSTEM_ATTACHMENT_REBATE_ITEM_NUMBER" VARCHAR2(4000), 
	"SYSTEM_ATTACHMENT_SPA_LINE_ID" NUMBER, 
	"SYSTEM_ATTACHMENT_REBATE_AMOUNT" NUMBER, 
	"SYSTEM_ATTACHMENT_REBATE_ELIGIBILE_REASON" VARCHAR2(4000), 
	"SYSTEM_ATTACHMENT_PAYEE_TYPE" VARCHAR2(4000), 
	"SYSTEM_ATTACHMENT_PAYEE_ID" NUMBER, 
	"SYSTEM_SIZE_SPA_NUMBER" VARCHAR2(4000), 
	"SYSTEM_SIZE_SPA_LINE_ID" NUMBER, 
	"SYSTEM_SIZE_REBATE_ITEM_NUMBER" VARCHAR2(4000), 
	"SYSTEM_SIZE_REBATE_ELIGIBILE_REASON" VARCHAR2(4000), 
	"SYSTEM_SIZE_PAYEE_TYPE" VARCHAR2(4000), 
	"SYSTEM_SIZE_PAYEE_ID" NUMBER, 
	"SYSTEM_SIZE_TIER_CALC_BATCH_ID" NUMBER, 
	"SYSTEM_SIZE_TIER_CALC_PROCESS_COUNT" NUMBER, 
	"SYSTEM_SIZE_TIER_CALC_LAST_BATCH_ID" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"ATTRIBUTE11" VARCHAR2(4000), 
	"ATTRIBUTE12" VARCHAR2(4000), 
	"ATTRIBUTE13" VARCHAR2(4000), 
	"ATTRIBUTE14" VARCHAR2(4000), 
	"ATTRIBUTE15" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(4000), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(4000), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000), 
	"BATCH_ID" NUMBER, 
	"LAST_BATCH_ID" NUMBER, 
	"BATCH_PROCESS_COUNT" NUMBER, 
	 CONSTRAINT "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_PK" PRIMARY KEY ("CHM_DEVICE_ATTRIBUTE_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("CHM_ENLIGHTEN_DEVICE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_DISTI_ORACLE_ACCOUNT_ID_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("DISTI_ORACLE_ACCOUNT_ID") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_DISTI_ORACLE_ACCOUNT_NUMBER_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("DISTI_ORACLE_ACCOUNT_NUMBER") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_ITEM_NUMBER_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("ITEM_NUMBER") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_ORDER_TYPE_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("ORACLE_ORDER_TYPE") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_REBATE_EFFECTIVE_DATE_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("REBATE_EFFECTIVE_DATE") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_REBATE_ELIGIBLE_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("MSI_REBATE_ELIGIBLE") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_SERIAL_NUM_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("SERIAL_NUM") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_SITE_ID_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("SITE_ID") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_SYSTEM_ATTACHMENT_SPA_LINE_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("SYSTEM_ATTACHMENT_SPA_LINE_ID") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_SYSTEM_ATTACHMENT_SPA_NUMBER_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("SYSTEM_ATTACHMENT_SPA_NUMBER") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_SYSTEM_SIZE_SPA_LINE_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("SYSTEM_SIZE_SPA_LINE_ID") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_SYSTEM_SIZE_SPA_NUMBER_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("SYSTEM_SIZE_SPA_NUMBER") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_SYSTEM_SIZE_TIER_CALC_BATCH_ID_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("SYSTEM_SIZE_TIER_CALC_BATCH_ID") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_UNIT_INCENTIVE_SPA_LINE_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("UNIT_ACTIVATION_SPA_LINE_ID") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_UNIT_INCENTIVE_SPA_NUMBER_IDX" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("UNIT_ACTIVATION_SPA_NUMBER") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_DEVICE_ATTR_BATCH_ID" ON "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ("BATCH_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" 
  BEFORE INSERT OR UPDATE ON CHM_ENLIGHTEN_DEVICE_ATTRIBUTES
  FOR EACH ROW
   BEGIN
      IF INSERTING THEN

        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATE_DATE   := NVL(:NEW.LAST_UPDATE_DATE ,SYSTIMESTAMP) ;
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());

      ELSIF updating THEN
        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATE_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATE_DATE != :NEW.LAST_UPDATE_DATE THEN
                    :NEW.LAST_UPDATE_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

              END IF;
       EXCEPTION
  WHEN OTHERS THEN
    chm_msi_debug_api.log_msg(:new.CHM_DEVICE_ATTRIBUTE_ID, 'BIU_CHM_ENLIGHTEN_DEVICE_ATTRIBUTES', SQLERRM);
    END;

/
ALTER TRIGGER "BIU_CHM_ENLIGHTEN_DEVICE_ATTRIBUTES" ENABLE;