
  CREATE TABLE "CHM_MSI_CLAIM_STAGING" 
   (	"FILE_RECORD_ID" NUMBER, 
	"FILE_ID" NUMBER, 
	"USER_REFERENCE" VARCHAR2(4000), 
	"PAYEE_SFDC_CUSTOMER_KEY" VARCHAR2(4000), 
	"INSTALLER_SFDC_CUSTOMER_KEY" VARCHAR2(4000), 
	"CLAIM_DATE" VARCHAR2(4000), 
	"CLAIM_TYPE" VARCHAR2(4000), 
	"SPA_NUMBER" VARCHAR2(4000), 
	"ENLIGHTEN_SITE_ID" VARCHAR2(4000), 
	"CHM_ENLIGHTEN_DEVICE_ID" VARCHAR2(4000), 
	"DEVICE_ITEM_NUMBER" VARCHAR2(4000), 
	"SERIAL_NUMBER" VARCHAR2(4000), 
	"REBATE_ITEM_NUMBER" VARCHAR2(4000), 
	"REBATE_TYPE" VARCHAR2(4000), 
	"REBATE_TIER" VARCHAR2(4000), 
	"QUANTITY" VARCHAR2(4000), 
	"UNIT_CLAIM_AMOUNT" VARCHAR2(4000), 
	"EXTENDED_CLAIM_AMOUNT" VARCHAR2(4000), 
	"CURRENCY" VARCHAR2(4000), 
	"REASON_CODE" VARCHAR2(4000), 
	"PARTNER_CLAIM_NUMBER" VARCHAR2(4000), 
	"PARTNER_CLAIM_LINE_NUMBER" VARCHAR2(4000), 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(4000), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(4000), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SOURCE_APP_ID" NUMBER, 
	"ENTERPRISE_ID" NUMBER, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000), 
	"ERROR_CODE" VARCHAR2(4000), 
	"ERROR_MESSAGE" VARCHAR2(4000), 
	"STATUS" VARCHAR2(4000)
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_MSI_CLAIM_STAGING" BEFORE
    INSERT OR UPDATE ON CHM_MSI_CLAIM_STAGING
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.FILE_RECORD_ID IS NULL THEN
            :NEW.FILE_RECORD_ID := CHM_CLAIM_STAGING_SEQ.NEXTVAL;
        END IF;
        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATED_DATE  := NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP) ;
        :NEW.SOURCE_APP_ID      := NVL(:NEW.SOURCE_APP_ID, CHM_UTIL_PKG.GETSOURCEAPP('CHM'));
        :NEW.ENTERPRISE_ID      := NVL(:NEW.ENTERPRISE_ID, CHM_CONST_PKG.GETENTERPRISEID());
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());

      ELSIF UPDATING THEN
        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATED_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATED_DATE != :NEW.LAST_UPDATED_DATE THEN
                    :NEW.LAST_UPDATED_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

      END IF;
   END;
/
ALTER TRIGGER "BIU_CHM_MSI_CLAIM_STAGING" ENABLE;