
  CREATE TABLE "CHM_ENLIGHTEN_SITE_MASTER" 
   (	"CHM_ENLIGHTEN_SITE_ID" NUMBER DEFAULT CHM.CHM_ENLIGHTEN_SITE_MASTER_SEQ.NEXTVAL, 
	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(4000), 
	"TYPE" VARCHAR2(4000), 
	"OWNER_ID" NUMBER, 
	"INSTALLER_ID" NUMBER, 
	"MAINTAINER_ID" NUMBER, 
	"FIRST_INTERVAL_END_DATE" DATE, 
	"PCU_CHANNEL_COUNT" NUMBER, 
	"ENVOY_COUNT" NUMBER, 
	"ACB_COUNT" NUMBER, 
	"NSR_COUNT" NUMBER, 
	"ENCHARGE_COUNT" NUMBER, 
	"ENPOWER_COUNT" NUMBER, 
	"PCU_TYPES" VARCHAR2(4000), 
	"STATUS_CODE" VARCHAR2(4000), 
	"AC_VOLTAGE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	"MEASURED_ACV" VARCHAR2(4000), 
	"IS_LEASE" VARCHAR2(4000), 
	"PARTNER_ID" NUMBER, 
	"SYSTEM_HOST_ID" NUMBER, 
	"ENLIGHTEN_SITE_URL" VARCHAR2(4000), 
	"STAGE" NUMBER, 
	"SYSTEM_START_DATE" VARCHAR2(4000), 
	"ZERO_TOUCH" VARCHAR2(4000), 
	"ALLOW_API_ACCESS" VARCHAR2(4000), 
	"LOCATION_ACCESS" VARCHAR2(4000), 
	"RATE_SCHEDULE" VARCHAR2(4000), 
	"DESCRIPTION" VARCHAR2(4000), 
	"OPERATIONAL" VARCHAR2(4000), 
	"INTERCONNECT_DATE" DATE, 
	"INTERNET_CONNECTION_TYPE" VARCHAR2(4000), 
	"PCU_ATTACHMENT_TYPE" VARCHAR2(4000), 
	"CONNECTION_TYPE" VARCHAR2(4000), 
	"SFDC_DRIP_CAMPAIGN_FLAG" VARCHAR2(4000), 
	"IQEVC_COUNT" NUMBER, 
	"CONSUMPTION_CT" VARCHAR2(4000), 
	"HEMS" VARCHAR2(4000), 
	"ADDRESS_ID" VARCHAR2(4000), 
	"ADDRESS_1" VARCHAR2(4000), 
	"ADDRESS_2" VARCHAR2(4000), 
	"ADDRESS_CITY" VARCHAR2(4000), 
	"ADDRESS_STATE" VARCHAR2(4000), 
	"ADDRESS_ZIP" VARCHAR2(4000), 
	"ADDRESS_COUNTRY" VARCHAR2(4000), 
	"ADDRESS_TIMEZONE" VARCHAR2(4000), 
	"ADDRESS" VARCHAR2(4000), 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"ATTRIBUTE11" VARCHAR2(4000), 
	"ATTRIBUTE12" VARCHAR2(4000), 
	"ATTRIBUTE13" VARCHAR2(4000), 
	"ATTRIBUTE14" VARCHAR2(4000), 
	"ATTRIBUTE15" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(4000), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(4000), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000), 
	"STAGE_3_STATUS_DATE" DATE, 
	 UNIQUE ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PK_CHM_ENLIGHTEN_SITE_ID" PRIMARY KEY ("CHM_ENLIGHTEN_SITE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "CHM_ENLIGHTEN_SITE_COUNTRY_IDX" ON "CHM_ENLIGHTEN_SITE_MASTER" ("ADDRESS_COUNTRY") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_SITE_INSTALLER_ID_IDX" ON "CHM_ENLIGHTEN_SITE_MASTER" ("INSTALLER_ID") 
  ;

  CREATE INDEX "CHM_ENLIGHTEN_SITE_STAGE_3_DATE_IDX" ON "CHM_ENLIGHTEN_SITE_MASTER" ("STAGE_3_STATUS_DATE") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "AIU_CHM_ENLIGHTEN_SITE_MASTER_TRG" AFTER
    INSERT OR UPDATE OR DELETE ON chm_enlighten_site_master
    FOR EACH ROW
BEGIN
    IF inserting THEN
        INSERT INTO chm_enlighten_site_master_audit (
            chm_enlighten_site_master_audit_id,
			CHM_ENLIGHTEN_SITE_ID,
            new_id,
            new_name,
            new_type,
            new_owner_id,
            new_installer_id,
            new_maintainer_id,
            new_first_interval_end_date,
            new_pcu_channel_count,
            new_envoy_count,
            new_acb_count,
            new_nsr_count,
            new_encharge_count,
            new_enpower_count,
            new_pcu_types,
            new_status_code,
            new_ac_voltage,
            new_created_date,
            new_measured_acv,
            new_is_lease,
            new_partner_id,
            new_system_host_id,
            new_enlighten_site_url,
            new_stage,
            new_system_start_date,
            new_zero_touch,
            new_allow_api_access,
            new_location_access,
            new_rate_schedule,
            new_description,
            new_operational,
            new_interconnect_date,
            new_internet_connection_type,
            new_pcu_attachment_type,
            new_connection_type,
            new_sfdc_drip_campaign_flag,
            new_iqevc_count,
            new_consumption_ct,
            new_hems,
            new_address_id,
            new_address_1,
            new_address_2,
            new_address_city,
            new_address_state,
            new_address_zip,
            new_address_country,
            new_address_timezone,
            new_address,
            new_attribute1,
            new_attribute2,
            new_attribute3,
            new_attribute4,
            new_attribute5,
            new_attribute6,
            new_attribute7,
            new_attribute8,
            new_attribute9,
            new_attribute10,
            new_attribute11,
            new_attribute12,
            new_attribute13,
            new_attribute14,
            new_attribute15,
            new_created_by,
            new_creation_date,
            new_last_updated_by,
            new_last_update_date,
            new_ip_address,
            new_user_agent,
            new_stage_3_status_date,
            action,
			CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,   
			IP_ADDRESS,       
			USER_AGENT 
        ) VALUES (
            chm_enlighten_site_master_audit_seq.NEXTVAL,
            :new.CHM_ENLIGHTEN_SITE_ID,
            :new.id,
            :new.name,
            :new.type,
            :new.owner_id,
            :new.installer_id,
            :new.maintainer_id,
            :new.first_interval_end_date,
            :new.pcu_channel_count,
            :new.envoy_count,
            :new.acb_count,
            :new.nsr_count,
            :new.encharge_count,
            :new.enpower_count,
            :new.pcu_types,
            :new.status_code,
            :new.ac_voltage,
            :new.created_date,
            :new.measured_acv,
            :new.is_lease,
            :new.partner_id,
            :new.system_host_id,
            :new.enlighten_site_url,
            :new.stage,
            :new.system_start_date,
            :new.zero_touch,
            :new.allow_api_access,
            :new.location_access,
            :new.rate_schedule,
            :new.description,
            :new.operational,
            :new.interconnect_date,
            :new.internet_connection_type,
            :new.pcu_attachment_type,
            :new.connection_type,
            :new.sfdc_drip_campaign_flag,
            :new.iqevc_count,
            :new.consumption_ct,
            :new.hems,
            :new.address_id,
            :new.address_1,
            :new.address_2,
            :new.address_city,
            :new.address_state,
            :new.address_zip,
            :new.address_country,
            :new.address_timezone,
            :new.address,
            :new.attribute1,
            :new.attribute2,
            :new.attribute3,
            :new.attribute4,
            :new.attribute5,
            :new.attribute6,
            :new.attribute7,
            :new.attribute8,
            :new.attribute9,
            :new.attribute10,
            :new.attribute11,
            :new.attribute12,
            :new.attribute13,
            :new.attribute14,
            :new.attribute15,
            :new.created_by,
            :new.creation_date,
            :new.last_updated_by,
            :new.last_update_date,
            :new.ip_address,
            :new.user_agent,
            :new.stage_3_status_date,
            'INSERT',
			NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATE_DATE ,SYSTIMESTAMP),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    ELSIF updating THEN
        INSERT INTO chm_enlighten_site_master_audit (
            chm_enlighten_site_master_audit_id,
            CHM_ENLIGHTEN_SITE_ID,
            old_id,
            new_id,
            old_name,
            new_name,
            old_type,
            new_type,
            old_owner_id,
            new_owner_id,
            old_installer_id,
            new_installer_id,
            old_maintainer_id,
            new_maintainer_id,
            old_first_interval_end_date,
            new_first_interval_end_date,
            old_pcu_channel_count,
            new_pcu_channel_count,
            old_envoy_count,
            new_envoy_count,
            old_acb_count,
            new_acb_count,
            old_nsr_count,
            new_nsr_count,
            old_encharge_count,
            new_encharge_count,
            old_enpower_count,
            new_enpower_count,
            old_pcu_types,
            new_pcu_types,
            old_status_code,
            new_status_code,
            old_ac_voltage,
            new_ac_voltage,
            old_created_date,
            new_created_date,
            old_measured_acv,
            new_measured_acv,
            old_is_lease,
            new_is_lease,
            old_partner_id,
            new_partner_id,
            old_system_host_id,
            new_system_host_id,
            old_enlighten_site_url,
            new_enlighten_site_url,
            old_stage,
            new_stage,
            old_system_start_date,
            new_system_start_date,
            old_zero_touch,
            new_zero_touch,
            old_allow_api_access,
            new_allow_api_access,
            old_location_access,
            new_location_access,
            old_rate_schedule,
            new_rate_schedule,
            old_description,
            new_description,
            old_operational,
            new_operational,
            old_interconnect_date,
            new_interconnect_date,
            old_internet_connection_type,
            new_internet_connection_type,
            old_pcu_attachment_type,
            new_pcu_attachment_type,
            old_connection_type,
            new_connection_type,
            old_sfdc_drip_campaign_flag,
            new_sfdc_drip_campaign_flag,
            old_iqevc_count,
            new_iqevc_count,
            old_consumption_ct,
            new_consumption_ct,
            old_hems,
            new_hems,
            old_address_id,
            new_address_id,
            old_address_1,
            new_address_1,
            old_address_2,
            new_address_2,
            old_address_city,
            new_address_city,
            old_address_state,
            new_address_state,
            old_address_zip,
            new_address_zip,
            old_address_country,
            new_address_country,
            old_address_timezone,
            new_address_timezone,
            old_address,
            new_address,
            old_attribute1,
            new_attribute1,
            old_attribute2,
            new_attribute2,
            old_attribute3,
            new_attribute3,
            old_attribute4,
            new_attribute4,
            old_attribute5,
            new_attribute5,
            old_attribute6,
            new_attribute6,
            old_attribute7,
            new_attribute7,
            old_attribute8,
            new_attribute8,
            old_attribute9,
            new_attribute9,
            old_attribute10,
            new_attribute10,
            old_attribute11,
            new_attribute11,
            old_attribute12,
            new_attribute12,
            old_attribute13,
            new_attribute13,
            old_attribute14,
            new_attribute14,
            old_attribute15,
            new_attribute15,
            old_created_by,
            new_created_by,
            old_creation_date,
            new_creation_date,
            old_last_updated_by,
            new_last_updated_by,
            old_last_update_date,
            new_last_update_date,
            old_ip_address,
            new_ip_address,
            old_user_agent,
            new_user_agent,
            old_stage_3_status_date,
            new_stage_3_status_date,
            action,
			CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,   
			IP_ADDRESS,       
			USER_AGENT 
        ) VALUES (
            chm_enlighten_site_master_audit_seq.NEXTVAL,
			:old.CHM_ENLIGHTEN_SITE_ID,
            :old.id,
			:new.id,
            :old.name,
			:new.name,
            :old.type,
			:new.type,
            :old.owner_id,
			:new.owner_id,
            :old.installer_id,
			:new.installer_id,
            :old.maintainer_id,
			:new.maintainer_id,
            :old.first_interval_end_date,
			:new.first_interval_end_date,
            :old.pcu_channel_count,
			:new.pcu_channel_count,
            :old.envoy_count,
			:new.envoy_count,
            :old.acb_count,
			:new.acb_count,
            :old.nsr_count,
			:new.nsr_count,
            :old.encharge_count,
			:new.encharge_count,
            :old.enpower_count,
			:new.enpower_count,
            :old.pcu_types,
			:new.pcu_types,
            :old.status_code,
			:new.status_code,
            :old.ac_voltage,
			:new.ac_voltage,
            :old.created_date,
			:new.created_date,
            :old.measured_acv,
			:new.measured_acv,
            :old.is_lease,
			:new.is_lease,
            :old.partner_id,
			:new.partner_id,
            :old.system_host_id,
			:new.system_host_id,
            :old.enlighten_site_url,
			:new.enlighten_site_url,
            :old.stage,
			:new.stage,
            :old.system_start_date,
			:new.system_start_date,
            :old.zero_touch,
			:new.zero_touch,
            :old.allow_api_access,
			:new.allow_api_access,
            :old.location_access,
			:new.location_access,
            :old.rate_schedule,
			:new.rate_schedule,
            :old.description,
			:new.description,
            :old.operational,
			:new.operational,
            :old.interconnect_date,
			:new.interconnect_date,
            :old.internet_connection_type,
			:new.internet_connection_type,
            :old.pcu_attachment_type,
			:new.pcu_attachment_type,
            :old.connection_type,
			:new.connection_type,
            :old.sfdc_drip_campaign_flag,
			:new.sfdc_drip_campaign_flag,
            :old.iqevc_count,
			:new.iqevc_count,
            :old.consumption_ct,
			:new.consumption_ct,
            :old.hems,
			:new.hems,
            :old.address_id,
			:new.address_id,
            :old.address_1,
			:new.address_1,
            :old.address_2,
			:new.address_2,
            :old.address_city,
			:new.address_city,
            :old.address_state,
			:new.address_state,
            :old.address_zip,
			:new.address_zip,
            :old.address_country,
			:new.address_country,
            :old.address_timezone,
			:new.address_timezone,
            :old.address,
			:new.address,
            :old.attribute1,
			:new.attribute1,
            :old.attribute2,
			:new.attribute2,
            :old.attribute3,
			:new.attribute3,
            :old.attribute4,
			:new.attribute4,
            :old.attribute5,
			:new.attribute5,
            :old.attribute6,
			:new.attribute6,
            :old.attribute7,
			:new.attribute7,
            :old.attribute8,
			:new.attribute8,
            :old.attribute9,
			:new.attribute9,
            :old.attribute10,
			:new.attribute10,
            :old.attribute11,
			:new.attribute11,
            :old.attribute12,
			:new.attribute12,
            :old.attribute13,
			:new.attribute13,
            :old.attribute14,
			:new.attribute14,
            :old.attribute15,
			:new.attribute15,
            :old.created_by,
			:new.created_by,
            :old.creation_date,
			:new.creation_date,
            :old.last_updated_by,
			:new.last_updated_by,
            :old.last_update_date,
			:new.last_update_date,
            :old.ip_address,
			:new.ip_address,
            :old.user_agent,
			:new.user_agent,
            :old.stage_3_status_date,
			:new.stage_3_status_date,
            'UPDATE',
			NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATE_DATE ,SYSTIMESTAMP),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    ELSIF deleting THEN
        INSERT INTO chm_enlighten_site_master_audit (
            chm_enlighten_site_master_audit_id,
            CHM_ENLIGHTEN_SITE_ID,
            old_id,
            old_name,
            old_type,
            old_owner_id,
            old_installer_id,
            old_maintainer_id,
            old_first_interval_end_date,
            old_pcu_channel_count,
            old_envoy_count,
            old_acb_count,
            old_nsr_count,
            old_encharge_count,
            old_enpower_count,
            old_pcu_types,
            old_status_code,
            old_ac_voltage,
            old_created_date,
            old_measured_acv,
            old_is_lease,
            old_partner_id,
            old_system_host_id,
            old_enlighten_site_url,
            old_stage,
            old_system_start_date,
            old_zero_touch,
            old_allow_api_access,
            old_location_access,
            old_rate_schedule,
            old_description,
            old_operational,
            old_interconnect_date,
            old_internet_connection_type,
            old_pcu_attachment_type,
            old_connection_type,
            old_sfdc_drip_campaign_flag,
            old_iqevc_count,
            old_consumption_ct,
            old_hems,
            old_address_id,
            old_address_1,
            old_address_2,
            old_address_city,
            old_address_state,
            old_address_zip,
            old_address_country,
            old_address_timezone,
            old_address,
            old_attribute1,
            old_attribute2,
            old_attribute3,
            old_attribute4,
            old_attribute5,
            old_attribute6,
            old_attribute7,
            old_attribute8,
            old_attribute9,
            old_attribute10,
            old_attribute11,
            old_attribute12,
            old_attribute13,
            old_attribute14,
            old_attribute15,
            old_created_by,
            old_creation_date,
            old_last_updated_by,
            old_last_update_date,
            old_ip_address,
            old_user_agent,
            old_stage_3_status_date,
            action,
			CREATED_BY,       
			CREATION_DATE,    
			LAST_UPDATED_BY,  
			LAST_UPDATED_DATE,   
			IP_ADDRESS,       
			USER_AGENT 
        ) VALUES (
            chm_enlighten_site_master_audit_seq.NEXTVAL,
            :old.CHM_ENLIGHTEN_SITE_ID,
            :old.id,
            :old.name,
            :old.type,
            :old.owner_id,
            :old.installer_id,
            :old.maintainer_id,
            :old.first_interval_end_date,
            :old.pcu_channel_count,
            :old.envoy_count,
            :old.acb_count,
            :old.nsr_count,
            :old.encharge_count,
            :old.enpower_count,
            :old.pcu_types,
            :old.status_code,
            :old.ac_voltage,
            :old.created_date,
            :old.measured_acv,
            :old.is_lease,
            :old.partner_id,
            :old.system_host_id,
            :old.enlighten_site_url,
            :old.stage,
            :old.system_start_date,
            :old.zero_touch,
            :old.allow_api_access,
            :old.location_access,
            :old.rate_schedule,
            :old.description,
            :old.operational,
            :old.interconnect_date,
            :old.internet_connection_type,
            :old.pcu_attachment_type,
            :old.connection_type,
            :old.sfdc_drip_campaign_flag,
            :old.iqevc_count,
            :old.consumption_ct,
            :old.hems,
            :old.address_id,
            :old.address_1,
            :old.address_2,
            :old.address_city,
            :old.address_state,
            :old.address_zip,
            :old.address_country,
            :old.address_timezone,
            :old.address,
            :old.attribute1,
            :old.attribute2,
            :old.attribute3,
            :old.attribute4,
            :old.attribute5,
            :old.attribute6,
            :old.attribute7,
            :old.attribute8,
            :old.attribute9,
            :old.attribute10,
            :old.attribute11,
            :old.attribute12,
            :old.attribute13,
            :old.attribute14,
            :old.attribute15,
            :old.created_by,
            :old.creation_date,
            :old.last_updated_by,
            :old.last_update_date,
            :old.ip_address,
            :old.user_agent,
            :old.stage_3_status_date,
            'DELETE',
			NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP),
			NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME()),
			NVL(:NEW.LAST_UPDATE_DATE ,SYSTIMESTAMP),
			NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS()),
			NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT())
        );

    END IF;
END;
/
ALTER TRIGGER "AIU_CHM_ENLIGHTEN_SITE_MASTER_TRG" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_ENLIGHTEN_SITE_MASTER" 
  BEFORE INSERT OR UPDATE ON CHM_ENLIGHTEN_SITE_MASTER
  FOR EACH ROW
   BEGIN
      IF INSERTING THEN
        IF :new.CHM_ENLIGHTEN_SITE_ID  IS NULL THEN
            :new.CHM_ENLIGHTEN_SITE_ID   := CHM_ENLIGHTEN_SITE_MASTER_SEQ.NEXTVAL;
        END IF;

       -- :NEW.attribute10 := chm_util_pkg.removespecialwords(:NEW.NAME);

        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATE_DATE   := NVL(:NEW.LAST_UPDATE_DATE ,SYSTIMESTAMP) ;
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());

        --We need to capture SYSDATE when CHM gets an update on Site 
        --where the stage crosses 3
        --Attribute 1 stores the date we captured that site crossed stage 3

        IF NVL(:NEW.STAGE,0) =3 THEN
		  :NEW.ATTRIBUTE2 := 'INSERT';
		  :NEW.ATTRIBUTE3 := :NEW.STAGE;
          :NEW.ATTRIBUTE1 := TO_CHAR(SYSTIMESTAMP);
          :NEW.STAGE_3_STATUS_DATE:=TRUNC(SYSDATE);
        END IF;


      ELSIF updating THEN
        --We need to capture SYSDATE when CHM gets an update on Site 
        --where the stage crosses 3
        -- We dont wnat to update if ATTRIBUTE1 already cpatured this date earlier
        --so checking that OLD value is NULL and OLD stage is < 3 and new stage >=3

        --Attribute 1 stores the date we captured that site crossed stage 3

        IF :OLD.ATTRIBUTE1 IS NULL AND NVL(:OLD.STAGE,0)<> 3 
			AND NVL(:NEW.STAGE,0) =3 THEN
		  :NEW.ATTRIBUTE2 := 'UPDATE';
		  :NEW.ATTRIBUTE3 := :NEW.STAGE;
          :NEW.ATTRIBUTE1 := TO_CHAR(SYSTIMESTAMP);
          :NEW.STAGE_3_STATUS_DATE:=TRUNC(SYSDATE);
        END IF;

        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATE_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATE_DATE != :NEW.LAST_UPDATE_DATE THEN
                    :NEW.LAST_UPDATE_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

        --:NEW.attribute10 := chm_util_pkg.removespecialwords(:NEW.NAME);
              END IF;
       EXCEPTION
  WHEN OTHERS THEN
    chm_msi_debug_api.log_msg(:new.ID, 'BIU_CHM_ENLIGHTEN_SITE_MASTER', SQLERRM);
    END;

/
ALTER TRIGGER "BIU_CHM_ENLIGHTEN_SITE_MASTER" ENABLE;