
  CREATE TABLE "CHM_MSI_ORACLE_SHIPMENT_SERIAL_NUMBER_DETAILS" 
   (	"ORACLE_SHIPMENT_SERIAL_NUMBER_DETAILS_ID" NUMBER DEFAULT CHM.CHM_MSI_ORACLE_SHIPMENT_SLNO_DETAILS_SEQ.NEXTVAL, 
	"CUSTOMER_NAME" VARCHAR2(4000), 
	"SO_NO" NUMBER, 
	"PL_NO" NUMBER, 
	"DELIVERY_DETAIL_ID" NUMBER, 
	"SERIAL_NUMBER" VARCHAR2(4000), 
	"ACT_SHIP_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"ENPHASE_PRODUCT_NAME" VARCHAR2(4000), 
	"SHIPPING_ORG_NAME" VARCHAR2(4000), 
	"SHIPPING_LOCATION" VARCHAR2(4000), 
	"CUSTOMER_ACCOUNT_ID" NUMBER, 
	"CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(4000), 
	"SHIPPING_ORG_ID" NUMBER, 
	"SALES_ORDER_ORG_ID" NUMBER, 
	"SALES_ORDER_TYPE" VARCHAR2(4000), 
	"SALES_ORDER_LINE_TYPE" VARCHAR2(4000), 
	"ATTRIBUTE_CONTEXT" VARCHAR2(4000), 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"ATTRIBUTE11" VARCHAR2(4000), 
	"ATTRIBUTE12" VARCHAR2(4000), 
	"ATTRIBUTE13" VARCHAR2(4000), 
	"ATTRIBUTE14" VARCHAR2(4000), 
	"ATTRIBUTE15" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(50), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(50), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SOURCE_APP_ID" NUMBER, 
	"ENTERPRISE_ID" NUMBER, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000)
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_MSI_ORACLE_SHIPMENT_SLNO_DETAILS_TRG" 
  BEFORE INSERT OR UPDATE ON CHM_MSI_ORACLE_SHIPMENT_SERIAL_NUMBER_DETAILS
  FOR EACH ROW
   BEGIN
      IF INSERTING THEN
        IF :new.ORACLE_SHIPMENT_SERIAL_NUMBER_DETAILS_ID  IS NULL THEN
            :new.ORACLE_SHIPMENT_SERIAL_NUMBER_DETAILS_ID   := CHM_MSI_ORACLE_SHIPMENT_SLNO_DETAILS_SEQ.NEXTVAL;
        END IF;


        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATED_DATE   := NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP) ;
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());


      ELSIF updating THEN

        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATED_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATED_DATE != :NEW.LAST_UPDATED_DATE THEN
                    :NEW.LAST_UPDATED_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

              END IF;
       EXCEPTION
  WHEN OTHERS THEN
    chm_msi_debug_api.log_msg(:new.ORACLE_SHIPMENT_SERIAL_NUMBER_DETAILS_ID, 'BIU_CHM_MSI_ORACLE_SHIPMENT_SLNO_DETAILS_TRG', SQLERRM);
    END;

/
ALTER TRIGGER "BIU_CHM_MSI_ORACLE_SHIPMENT_SLNO_DETAILS_TRG" ENABLE;