
  CREATE TABLE "CHM_MSI_CLAIM_AP_INVOICE_HEADER" 
   (	"ORACLE_AP_INVOICE_ID" NUMBER, 
	"ORACLE_AP_INVOICE_NUMBER" VARCHAR2(4000), 
	"INVOICE_AMOUNT" NUMBER, 
	"INVOICE_CURRENCY" VARCHAR2(4000), 
	"INVOICE_DATE" DATE, 
	"INSTALLER_NUMBER" VARCHAR2(4000), 
	"INSTALLER_SFDC_ACCOUNT_ID" VARCHAR2(4000), 
	"COUNTRY" VARCHAR2(4000), 
	"NO_OF_INVOICE_LINES" NUMBER, 
	"ORACLE_AP_INTERFACE_STATUS" VARCHAR2(4000), 
	"ATTRIBUTE_CONTEXT" VARCHAR2(4000), 
	"ATTRIBUTE1" VARCHAR2(4000), 
	"ATTRIBUTE2" VARCHAR2(4000), 
	"ATTRIBUTE3" VARCHAR2(4000), 
	"ATTRIBUTE4" VARCHAR2(4000), 
	"ATTRIBUTE5" VARCHAR2(4000), 
	"ATTRIBUTE6" VARCHAR2(4000), 
	"ATTRIBUTE7" VARCHAR2(4000), 
	"ATTRIBUTE8" VARCHAR2(4000), 
	"ATTRIBUTE9" VARCHAR2(4000), 
	"ATTRIBUTE10" VARCHAR2(4000), 
	"ATTRIBUTE11" VARCHAR2(4000), 
	"ATTRIBUTE12" VARCHAR2(4000), 
	"ATTRIBUTE13" VARCHAR2(4000), 
	"ATTRIBUTE14" VARCHAR2(4000), 
	"ATTRIBUTE15" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(4000), 
	"CREATION_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(4000), 
	"LAST_UPDATED_DATE" TIMESTAMP (6) WITH TIME ZONE, 
	"SOURCE_APP_ID" NUMBER, 
	"ENTERPRISE_ID" NUMBER, 
	"IP_ADDRESS" VARCHAR2(4000), 
	"USER_AGENT" VARCHAR2(4000), 
	"LOAD_REQUEST_ID" NUMBER, 
	"LOAD_REQUEST_STATUS" VARCHAR2(4000), 
	"IMPORT_REQUEST_ID" NUMBER, 
	"IMPORT_REQUEST_STATUS" VARCHAR2(4000), 
	"OIC_INSTANCE_ID" VARCHAR2(4000), 
	"BU_NAME" VARCHAR2(4000), 
	"SUPPLIER_NUMBER" VARCHAR2(4000), 
	"SUPPLIER_NAME" VARCHAR2(4000), 
	"SUPPLIER_SITE" VARCHAR2(4000), 
	"REJECTION_REASON" VARCHAR2(4000), 
	"IMPORT_SET" VARCHAR2(4000), 
	 CONSTRAINT "UNIQUE_INVOICE_ID" UNIQUE ("ORACLE_AP_INVOICE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_HDR_IMP_IDX" ON "CHM_MSI_CLAIM_AP_INVOICE_HEADER" ("IMPORT_REQUEST_STATUS") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_HDR_IMP_ID_IDX" ON "CHM_MSI_CLAIM_AP_INVOICE_HEADER" ("IMPORT_REQUEST_ID") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_HDR_INSTALLER_ID_IDX" ON "CHM_MSI_CLAIM_AP_INVOICE_HEADER" ("INSTALLER_SFDC_ACCOUNT_ID") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_HDR_INSTALLER_NUMBER_IDX" ON "CHM_MSI_CLAIM_AP_INVOICE_HEADER" ("INSTALLER_NUMBER") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_HDR_LOAD_IDX" ON "CHM_MSI_CLAIM_AP_INVOICE_HEADER" ("LOAD_REQUEST_STATUS") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_HDR_LOAD_ID_IDX" ON "CHM_MSI_CLAIM_AP_INVOICE_HEADER" ("LOAD_REQUEST_ID") 
  ;

  CREATE INDEX "CHM_MSI_CLAIM_AP_INV_HDR_SUPP_NUM_IDX" ON "CHM_MSI_CLAIM_AP_INVOICE_HEADER" ("SUPPLIER_NUMBER") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "BIU_CHM_MSI_CLAIM_AP_INVOICE_HEADER" 
  BEFORE INSERT OR UPDATE ON CHM_MSI_CLAIM_AP_INVOICE_HEADER
  FOR EACH ROW
   BEGIN
      IF INSERTING THEN


        :NEW.CREATED_BY         := NVL(:NEW.CREATED_BY , CHM_UTIL_PKG.GETUSERNAME());
        :NEW.CREATION_DATE      := NVL(:NEW.CREATION_DATE ,SYSTIMESTAMP);
        :NEW.LAST_UPDATED_BY    := NVL(:NEW.LAST_UPDATED_BY, CHM_UTIL_PKG.GETUSERNAME());
        :NEW.LAST_UPDATED_DATE   := NVL(:NEW.LAST_UPDATED_DATE ,SYSTIMESTAMP) ;
        :NEW.IP_ADDRESS         := NVL(:NEW.IP_ADDRESS,CHM_UTIL_PKG.GETIPADDRESS());
        :NEW.USER_AGENT         := NVL(:NEW.USER_AGENT,CHM_UTIL_PKG.GETUSERAGENT());



      ELSIF updating THEN


        :NEW.LAST_UPDATED_BY :=
            CASE
                WHEN :OLD.LAST_UPDATED_BY != :NEW.LAST_UPDATED_BY THEN
                    :NEW.LAST_UPDATED_BY
                ELSE CHM_UTIL_PKG.GETUSERNAME()
            END;

        :NEW.LAST_UPDATED_DATE :=
            CASE
                WHEN :OLD.LAST_UPDATED_DATE != :NEW.LAST_UPDATED_DATE THEN
                    :NEW.LAST_UPDATED_DATE
                ELSE SYSTIMESTAMP
            END;

        :NEW.IP_ADDRESS :=
            CASE
                WHEN :OLD.IP_ADDRESS != :NEW.IP_ADDRESS THEN
                    :NEW.IP_ADDRESS
                ELSE CHM_UTIL_PKG.GETIPADDRESS()
            END;

        :NEW.USER_AGENT :=
            CASE
                WHEN :OLD.USER_AGENT != :NEW.USER_AGENT THEN
                    :NEW.USER_AGENT
                ELSE CHM_UTIL_PKG.GETUSERAGENT()
            END;

              END IF;
       EXCEPTION
  WHEN OTHERS THEN
    chm_msi_debug_api.log_msg(:new.ORACLE_AP_INVOICE_ID, 'BIU_CHM_MSI_CLAIM_AP_INVOICE_HEADER', SQLERRM);
    END;
/
ALTER TRIGGER "BIU_CHM_MSI_CLAIM_AP_INVOICE_HEADER" ENABLE;