--------------------------------------------------------
--  DDL for Materialized View CHM_MSI_SPA_DETAILS_ALL_MV
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "CHM_MSI_SPA_DETAILS_ALL_MV" ("CHM_SPA_ID", "CHM_SPA_LINE_ID", "SPA_NUMBER", "DISTI_PRIORITY", "DISTI_SOURCE", "SFDC_DISTI_NAME", "SFDC_DISTI_ACCOUNT_ID", "SFDC_ORACLE_CUSTOMER_NUMBER", "SFDC_ORACLE_CUSTOMER_NUMBER_FULL", "OPPORTUNITY_OWNER", "INSTALLER_SOURCE", "INSTALLER_CHM_ACCOUNT_ID", "INSTALLER_SFDC_ACCOUNT_ID", "INSTALLER_ACCOUNT_NAME", "INSTALLER_CUSTOMER_KEY", "INSTALLER_ACCOUNT_TYPE", "INSTALLER_ACCOUNT_STATUS", "INSTALLER_ACCOUNT_OWNER", "ENLIGHTEN_INSTALLER_ID", "COUNTRY", "STATE", "ZIP", "SFDC_STATE", "SFDC_ZIP", "PRIMARY_PARTNER", "SPA_NAME", "GEOGRAPHY", "STAGE", "OPPORTUNITY_NAME", "DEAL_LOGISTICS", "STATUS", "SPECIAL_PRICING_TYPE", "FINAL_APPROVAL_TIME", "SPA_START_DATE", "SPA_EXPIRATION_DATE", "DEAL_CATEGORY", "SPA_CURRENCY", "SPA_TOTAL_PRICE_CURRENCY", "SPA_TOTAL_PRICE", "SPA_CREATED_DATE", "SPA_TYPE", "SPA_BACK_DATED", "ITEM_SOURCE", "ITEM_PRIORITY", "SPA_LINE_TYPE", "LINE_ITEM_NUMBER", "ITEM_NUMBER", "REBATE_ITEM_NUMBER", "MIN_QUANTITY", "REBATE_AMOUNT", "REBATE_TIER", "REBATE_TIER_MIN_QTY", "REBATE_TIER_MAX_QTY", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "OPPORTUNITY_OWNER_ID", "ID", "SPA_OPPORTUNITY_ID", "NEW_RENEWAL", "DISTRIBUTOR_ACCOUNT_NAME", "DISTRIBUTOR_SFDC_ID", "DISTRIBUTOR_ORACLE_ACCOUNT_ID", "DISTRIBUTOR_SFDC_CUSTOMER_KEY", "SPA_CREATED_BY", "SPA_LAST_UPDATED_BY", "SPA_FINAL_APPROVAL_DATE_TIME")
  DEFAULT COLLATION "USING_NLS_COMP"  SEGMENT CREATION IMMEDIATE
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
  BUILD DEFERRED
  USING INDEX 
  REFRESH COMPLETE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT * FROM CHM_MSI_SPA_DETAILS_ALL_V5;

   COMMENT ON MATERIALIZED VIEW "CHM_MSI_SPA_DETAILS_ALL_MV"  IS 'snapshot table for snapshot CHM.CHM_MSI_SPA_DETAILS_ALL_MV';
