--------------------------------------------------------
--  DDL for View CHM_MSI_SPA_INSTALLER_V5
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_SPA_INSTALLER_V5" ("INSTALLER_SOURCE", "SPA_NUMBER", "CHM_ACCOUNT_ID", "SFDC_ACCOUNT_ID", "ACCOUNT_NAME", "CUSTOMER_KEY", "ZONE", "ACCOUNT_TYPE", "ACCOUNT_STATUS", "ACCOUNT_OWNER", "SFDC_CREATED_BY", "SFDC_CREATION_DATE", "SFDC_LAST_UPDATED_BY", "SFDC_LAST_UPDATE_DATE", "ENLIGHTEN_INSTALLER_ID", "PARENT_ACCOUNT", "PARENT_ACCOUNT_ID", "ACCOUNT_RECORD_TYPE", "ACCOUNT_OWNER_ALIAS", "GEOGRAPHY", "TERRITORY", "SUB_TERRITORY", "ENLIGHTEN_COMPANY_ID", "ENLIGHTEN_INSTALLER_FLAG", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATE_DATE", "IP_ADDRESS", "USER_AGENT", "RELATIONSHIP", "ACCOUNT_CURRENCY", "ORACLE_CUSTOMER_NUMBER", "ACCOUNT_OWNER_ID", "COUNTRY", "CI_SYNC_FLAG", "REGION", "APPROVAL_GEOGRAPHY", "FORECASTABLE_ACCOUNT", "CHM_C", "MERGE_ID_C", "ENLIGHTEN_COMPANY_DUP_KEY_C", "BANK_DETAILS_FLAG") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT 'MAIN_INSTALLER' installer_source, 
	CSH.SPA_NUMBER,
	CSAM."CHM_ACCOUNT_ID",CSAM."SFDC_ACCOUNT_ID",CSAM."ACCOUNT_NAME",CSAM."CUSTOMER_KEY",CSAM."ZONE",CSAM."ACCOUNT_TYPE",CSAM."ACCOUNT_STATUS",CSAM."ACCOUNT_OWNER",CSAM."SFDC_CREATED_BY",CSAM."SFDC_CREATION_DATE",CSAM."SFDC_LAST_UPDATED_BY",CSAM."SFDC_LAST_UPDATE_DATE",CSAM."ENLIGHTEN_INSTALLER_ID",CSAM."PARENT_ACCOUNT",CSAM."PARENT_ACCOUNT_ID",CSAM."ACCOUNT_RECORD_TYPE",CSAM."ACCOUNT_OWNER_ALIAS",CSAM."GEOGRAPHY",CSAM."TERRITORY",CSAM."SUB_TERRITORY",CSAM."ENLIGHTEN_COMPANY_ID",CSAM."ENLIGHTEN_INSTALLER_FLAG",CSAM."ATTRIBUTE_CONTEXT",CSAM."ATTRIBUTE1",CSAM."ATTRIBUTE2",CSAM."ATTRIBUTE3",CSAM."ATTRIBUTE4",CSAM."ATTRIBUTE5",CSAM."ATTRIBUTE6",CSAM."ATTRIBUTE7",CSAM."ATTRIBUTE8",CSAM."ATTRIBUTE9",CSAM."ATTRIBUTE10",CSAM."ATTRIBUTE11",CSAM."ATTRIBUTE12",CSAM."ATTRIBUTE13",CSAM."ATTRIBUTE14",CSAM."ATTRIBUTE15",CSAM."CREATED_BY",CSAM."CREATION_DATE",CSAM."LAST_UPDATED_BY",CSAM."LAST_UPDATE_DATE",CSAM."IP_ADDRESS",CSAM."USER_AGENT",CSAM."RELATIONSHIP",CSAM."ACCOUNT_CURRENCY",CSAM."ORACLE_CUSTOMER_NUMBER",CSAM."ACCOUNT_OWNER_ID",CSAM."COUNTRY",CSAM."CI_SYNC_FLAG",CSAM."REGION",CSAM."APPROVAL_GEOGRAPHY",CSAM."FORECASTABLE_ACCOUNT",CSAM."CHM_C",CSAM."MERGE_ID_C",CSAM."ENLIGHTEN_COMPANY_DUP_KEY_C",CSAM."BANK_DETAILS_FLAG"
	 FROM 	CHM_MSI_SPA_HEADER csh
			,CHM_SFDC_ACCOUNT_MASTER csam
	 WHERE 	
			1=1
		AND	csh.installer_customer_key=csam.customer_key
		--AND UPPER(NVL(csh.is_deleted,'FALSE'))='FALSE'	
UNION ALL
	SELECT 'CHILD_INSTALLER' installer_source, 
	CSH.SPA_NUMBER,
	CSAM."CHM_ACCOUNT_ID",CSAM."SFDC_ACCOUNT_ID",CSAM."ACCOUNT_NAME",CSAM."CUSTOMER_KEY",CSAM."ZONE",CSAM."ACCOUNT_TYPE",CSAM."ACCOUNT_STATUS",CSAM."ACCOUNT_OWNER",CSAM."SFDC_CREATED_BY",CSAM."SFDC_CREATION_DATE",CSAM."SFDC_LAST_UPDATED_BY",CSAM."SFDC_LAST_UPDATE_DATE",CSAM."ENLIGHTEN_INSTALLER_ID",CSAM."PARENT_ACCOUNT",CSAM."PARENT_ACCOUNT_ID",CSAM."ACCOUNT_RECORD_TYPE",CSAM."ACCOUNT_OWNER_ALIAS",CSAM."GEOGRAPHY",CSAM."TERRITORY",CSAM."SUB_TERRITORY",CSAM."ENLIGHTEN_COMPANY_ID",CSAM."ENLIGHTEN_INSTALLER_FLAG",CSAM."ATTRIBUTE_CONTEXT",CSAM."ATTRIBUTE1",CSAM."ATTRIBUTE2",CSAM."ATTRIBUTE3",CSAM."ATTRIBUTE4",CSAM."ATTRIBUTE5",CSAM."ATTRIBUTE6",CSAM."ATTRIBUTE7",CSAM."ATTRIBUTE8",CSAM."ATTRIBUTE9",CSAM."ATTRIBUTE10",CSAM."ATTRIBUTE11",CSAM."ATTRIBUTE12",CSAM."ATTRIBUTE13",CSAM."ATTRIBUTE14",CSAM."ATTRIBUTE15",CSAM."CREATED_BY",CSAM."CREATION_DATE",CSAM."LAST_UPDATED_BY",CSAM."LAST_UPDATE_DATE",CSAM."IP_ADDRESS",CSAM."USER_AGENT",CSAM."RELATIONSHIP",CSAM."ACCOUNT_CURRENCY",CSAM."ORACLE_CUSTOMER_NUMBER",CSAM."ACCOUNT_OWNER_ID",CSAM."COUNTRY",CSAM."CI_SYNC_FLAG",CSAM."REGION",CSAM."APPROVAL_GEOGRAPHY",CSAM."FORECASTABLE_ACCOUNT",CSAM."CHM_C",CSAM."MERGE_ID_C",CSAM."ENLIGHTEN_COMPANY_DUP_KEY_C",CSAM."BANK_DETAILS_FLAG"
	 FROM 	CHM_MSI_SPA_HEADER csh
			,CHM_MSI_SPA_INSTALLERS csi
			,CHM_SFDC_ACCOUNT_MASTER csam
	 WHERE 	
			--csh.spa_number=csi.spa
			csh.id=csi.spa
		AND	csi.installer_id=csam.sfdc_account_id
		 --AND UPPER(NVL(csh.is_deleted,'FALSE'))='FALSE'
		 AND UPPER(NVL(csi.is_deleted,'FALSE'))='FALSE'
		 AND UPPER(NVL(csi.status,'xx'))='APPROVED'
;
