--------------------------------------------------------
--  DDL for View CHM_MSI_SPA_PRODUCTS_V
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_SPA_PRODUCTS_V" ("SPA_NUMBER", "CHM_PRODUCTS_ID", "ID", "MSI_ELIGIBLE", "MSI_SYSTEM_ATTACHMENT_ELIGIBLE", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT", "OIC_INSTANCE_ID", "IS_ACTIVE", "NAME", "PRODUCT_CODE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        s.spa_number,
        i."CHM_PRODUCTS_ID",i."ID",i."MSI_ELIGIBLE",i."MSI_SYSTEM_ATTACHMENT_ELIGIBLE",i."ATTRIBUTE_CONTEXT",i."ATTRIBUTE1",i."ATTRIBUTE2",i."ATTRIBUTE3",i."ATTRIBUTE4",i."ATTRIBUTE5",i."ATTRIBUTE6",i."ATTRIBUTE7",i."ATTRIBUTE8",i."ATTRIBUTE9",i."ATTRIBUTE10",i."ATTRIBUTE11",i."ATTRIBUTE12",i."ATTRIBUTE13",i."ATTRIBUTE14",i."ATTRIBUTE15",i."CREATED_BY",i."CREATION_DATE",i."LAST_UPDATED_BY",i."LAST_UPDATED_DATE",i."SOURCE_APP_ID",i."ENTERPRISE_ID",i."IP_ADDRESS",i."USER_AGENT",i."OIC_INSTANCE_ID",i."IS_ACTIVE",i."NAME",i."PRODUCT_CODE"
    FROM
        chm_msi_spa_products i,
        chm_msi_spa_header   s
    WHERE
        i.ID = s.id (+)
;
