--------------------------------------------------------
--  DDL for View CHM_MSI_DEBUG_LOG_V
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_DEBUG_LOG_V" ("DBUG_ID", "DBUG_TRANSACTION_ID", "DBUG_MODULE", "DBUG_MSG", "DBUG_SQLCODE", "DBUG_SQLERRM", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "DBUG_CREATED_BY", "DBUG_CREATED_DATE", "REPORT_TYPE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
        "DBUG_ID","DBUG_TRANSACTION_ID","DBUG_MODULE","DBUG_MSG","DBUG_SQLCODE","DBUG_SQLERRM","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4","ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9","ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14","ATTRIBUTE15","DBUG_CREATED_BY","DBUG_CREATED_DATE","REPORT_TYPE"
      FROM
        CHM_MSI_DEBUG_LOG
;
