--------------------------------------------------------
--  DDL for View CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_V1
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_ENLIGHTEN_DEVICE_ATTRIBUTES_V1" ("CHM_ENLIGHTEN_DEVICE_ID", "SITE_ID", "SERIAL_NUM", "TYPE", "HW_PART_NUM", "SKU", "RETIRED", "CREATED_DATE", "PARENT_SERIAL_NUM", "PV_MODULE_MANUFACTURER_NAME", "PV_MODULE_MODEL_NAME", "PV_MODULE_DCW", "PV_MODULE_CELL_COUNT", "SW_VERSION", "BATCH_ID", "LAST_BATCH_ID", "BATCH_PROCESS_COUNT", "CHM_DEVICE_ATTRIBUTE_ID", "DISTI_ORACLE_ACCOUNT_NUMBER", "DISTI_ORACLE_ACCOUNT_ID", "DISTI_SFDC_KEY", "ORACLE_ORDER_TYPE", "ITEM_NUMBER", "PRODUCT_FAMILY", "PRODUCT_TYPE", "REBATE_EFFECTIVE_DATE", "DEVICE_QUANTITY", "MSI_REBATE_ELIGIBLE", "MSI_REBATE_ELIGIBILE_REASON", "MSI_REBATE_ELIGIBILITY_DERIVED_DATE", "UNIT_ACTIVATION_SPA_NUMBER", "SYSTEM_ATTACHMENT_SPA_NUMBER", "SYSTEM_SIZE_SPA_NUMBER", "UNIT_ACTIVATION_SPA_LINE_ID", "SYSTEM_ATTACHMENT_SPA_LINE_ID", "SYSTEM_SIZE_SPA_LINE_ID", "UNIT_ACTIVATION_PAYEE_TYPE", "UNIT_ACTIVATION_PAYEE_ID", "SYSTEM_ATTACHMENT_PAYEE_TYPE", "SYSTEM_ATTACHMENT_PAYEE_ID", "SYSTEM_SIZE_PAYEE_TYPE", "SYSTEM_SIZE_PAYEE_ID", "SYSTEM_SIZE_TIER_CALC_BATCH_ID", "SYSTEM_SIZE_TIER_CALC_PROCESS_COUNT", "SYSTEM_SIZE_TIER_CALC_LAST_BATCH_ID", "UNIT_ACTIVATION_REBATE_ITEM_NUMBER", "SYSTEM_ATTACHMENT_REBATE_ITEM_NUMBER", "SYSTEM_SIZE_REBATE_ITEM_NUMBER", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATE_DATE", "IP_ADDRESS", "USER_AGENT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT 	chmdd.chm_enlighten_device_id,
		chmdd.site_id,
		chmdd.serial_num,
		chmdd.type,
		chmdd.hw_part_num,
		chmdd.sku,
		chmdd.retired,
		chmdd.created_date,
		chmdd.parent_serial_num,
		chmdd.pv_module_manufacturer_name,
		chmdd.pv_module_model_name,
		chmdd.pv_module_dcw,
		chmdd.pv_module_cell_count,
		chmdd.sw_version,
		--chmdd.attribute2 batch_id,
		--chmda.attribute2 batch_id,
		chmda.batch_id,
		chmda.last_batch_id,
		chmda.batch_process_count,
		chmda.chm_device_attribute_id,
		chmda.disti_oracle_account_number,
		chmda.disti_oracle_account_id,
		chmda.disti_sfdc_key,
		chmda.oracle_order_type,
		chmda.item_number,
		chmda.product_family,
		chmda.product_type,
		chmda.rebate_effective_date,
		chmda.device_quantity,
		chmda.msi_rebate_eligible,
		chmda.msi_rebate_eligibile_reason,
		chmda.msi_rebate_eligibility_derived_date,
		chmda.unit_activation_spa_number,
		chmda.system_attachment_spa_number,
		chmda.system_size_spa_number,
		chmda.unit_activation_spa_line_id,
		chmda.system_attachment_spa_line_id,
		chmda.system_size_spa_line_id,
		
		chmda.unit_activation_payee_type ,
		chmda.unit_activation_payee_id ,
		chmda.system_attachment_payee_type ,
		chmda.system_attachment_payee_id ,	
		chmda.system_size_payee_type ,
		chmda.system_size_payee_id ,

		chmda.system_size_tier_calc_batch_id,
		chmda.system_size_tier_calc_process_count,
		chmda.system_size_tier_calc_last_batch_id,		
		
		chmda.unit_activation_rebate_item_number,
		chmda.system_attachment_rebate_item_number,
		chmda.system_size_rebate_item_number,

		chmda.attribute1,
		chmda.attribute2,
		chmda.attribute3,
		chmda.attribute4,
		chmda.attribute5,
		chmda.attribute6,
		chmda.attribute7,
		chmda.attribute8,
		chmda.attribute9,
		chmda.attribute10,
		chmda.attribute11,
		chmda.attribute12,
		chmda.attribute13,
		chmda.attribute14,
		chmda.attribute15,
		chmda.created_by,
		chmda.creation_date,
		chmda.last_updated_by,
		chmda.last_update_date,
		chmda.ip_address,
		chmda.user_agent
FROM 
	chm_enlighten_device_details chmdd,
	chm_enlighten_device_attributes chmda
WHERE 	chmdd.chm_enlighten_device_id = chmda.chm_enlighten_device_id
;
