--------------------------------------------------------
--  DDL for View CHM_MSI_CLAIM_REQUEST_V
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_CLAIM_REQUEST_V" ("MSI_CLAIM_REQ_ID", "REQ_REF_NO", "BATCH_ID", "TOTAL_APPROVAL_LEVEL", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT", "SUBMITTER_COMMENTS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT "MSI_CLAIM_REQ_ID","REQ_REF_NO","BATCH_ID","TOTAL_APPROVAL_LEVEL","ATTRIBUTE_CONTEXT","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4","ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9","ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14","ATTRIBUTE15","CREATED_BY","CREATION_DATE","LAST_UPDATED_BY","LAST_UPDATED_DATE","SOURCE_APP_ID","ENTERPRISE_ID","IP_ADDRESS","USER_AGENT","SUBMITTER_COMMENTS" FROM CHM_MSI_CLAIM_REQUEST
;
