--------------------------------------------------------
--  DDL for View CHM_LOOKUP_VALUES_V1
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_LOOKUP_VALUES_V1" ("CHM_LOOKUP_TYPE_ID", "LOOKUP_TYPE", "CHM_LOOKUP_VALUE_ID", "LOOKUP_CODE", "MEANING", "DESCRIPTION", "IS_SEEDED", "ENABLED_FLAG", "START_DATE_ACTIVE", "END_DATE_ACTIVE", "CHM_SOURCE_SYSTEM_ID", "SOURCE_APPLICATION_ID", "ENTERPRISE_ID", "LANGUAGE", "LOOKUP_TYPE_MEANING", "LOOKUP_TYPE_DESCRIPTION", "LOOKUP_TYPE_IS_SEEDED", "LOOKUP_TYPE_ENABLED_FLAG", "LOOKUP_TYPE_START_DATE_ACTIVE", "LOOKUP_TYPE_END_DATE_ACTIVE", "DISPLAY_SEQUENCE", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATE_DATE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    CLV.CHM_LOOKUP_TYPE_ID 
	,CLT.LOOKUP_TYPE
	,CLV.CHM_LOOKUP_VALUE_ID   		
	,CLV.LOOKUP_CODE				
	,CLV.MEANING					
	,CLV.DESCRIPTION				
    ,CLV.IS_SEEDED          		
    ,CLV.ENABLED_FLAG        		
    ,CLV.START_DATE_ACTIVE  		
    ,CLV.END_DATE_ACTIVE,  	
	CLT.CHM_SOURCE_SYSTEM_ID,
	CLT.SOURCE_APPLICATION_ID,
	CLT.ENTERPRISE_ID,
	CLT.LANGUAGE,
	CLT.MEANING LOOKUP_TYPE_MEANING,
	CLT.DESCRIPTION LOOKUP_TYPE_DESCRIPTION,
	CLT.IS_SEEDED LOOKUP_TYPE_IS_SEEDED,
	CLT.ENABLED_FLAG LOOKUP_TYPE_ENABLED_FLAG,
	CLT.START_DATE_ACTIVE LOOKUP_TYPE_START_DATE_ACTIVE,
	CLT.END_DATE_ACTIVE LOOKUP_TYPE_END_DATE_ACTIVE
    ,CLV.DISPLAY_SEQUENCE   		
    ,CLV.ATTRIBUTE1         		
    ,CLV.ATTRIBUTE2         		  
    ,CLV.ATTRIBUTE3         		   
    ,CLV.ATTRIBUTE4         		  
    ,CLV.ATTRIBUTE5         		
    ,CLV.ATTRIBUTE6         		   
    ,CLV.ATTRIBUTE7         		   
    ,CLV.ATTRIBUTE8         		  
    ,CLV.ATTRIBUTE9         		  
    ,CLV.ATTRIBUTE10        		   
    ,CLV.CREATED_BY         		 
    ,CLV.CREATION_DATE      		       
    ,CLV.LAST_UPDATED_BY    		 
    ,CLV.LAST_UPDATE_DATE   		
FROM 	CHM_LOOKUP_VALUES CLV,
		CHM_LOOKUP_TYPES CLT
WHERE 	CLT.CHM_LOOKUP_TYPE_ID=CLV.CHM_LOOKUP_TYPE_ID
;
