--------------------------------------------------------
--  DDL for View CHM_MSI_SPA_DETAILS_ALL_V5
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_SPA_DETAILS_ALL_V5" ("CHM_SPA_ID", "CHM_SPA_LINE_ID", "SPA_NUMBER", "DISTI_PRIORITY", "DISTI_SOURCE", "SFDC_DISTI_NAME", "SFDC_DISTI_ACCOUNT_ID", "SFDC_ORACLE_CUSTOMER_NUMBER", "SFDC_ORACLE_CUSTOMER_NUMBER_FULL", "OPPORTUNITY_OWNER", "INSTALLER_SOURCE", "INSTALLER_CHM_ACCOUNT_ID", "INSTALLER_SFDC_ACCOUNT_ID", "INSTALLER_ACCOUNT_NAME", "INSTALLER_CUSTOMER_KEY", "INSTALLER_ACCOUNT_TYPE", "INSTALLER_ACCOUNT_STATUS", "INSTALLER_ACCOUNT_OWNER", "ENLIGHTEN_INSTALLER_ID", "COUNTRY", "STATE", "ZIP", "SFDC_STATE", "SFDC_ZIP", "PRIMARY_PARTNER", "SPA_NAME", "GEOGRAPHY", "STAGE", "OPPORTUNITY_NAME", "DEAL_LOGISTICS", "STATUS", "SPECIAL_PRICING_TYPE", "FINAL_APPROVAL_TIME", "SPA_START_DATE", "SPA_EXPIRATION_DATE", "DEAL_CATEGORY", "SPA_CURRENCY", "SPA_TOTAL_PRICE_CURRENCY", "SPA_TOTAL_PRICE", "SPA_CREATED_DATE", "SPA_TYPE", "SPA_BACK_DATED", "ITEM_SOURCE", "ITEM_PRIORITY", "SPA_LINE_TYPE", "LINE_ITEM_NUMBER", "ITEM_NUMBER", "REBATE_ITEM_NUMBER", "MIN_QUANTITY", "REBATE_AMOUNT", "REBATE_TIER", "REBATE_TIER_MIN_QTY", "REBATE_TIER_MAX_QTY", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "OPPORTUNITY_OWNER_ID", "ID", "SPA_OPPORTUNITY_ID", "NEW_RENEWAL", "DISTRIBUTOR_ACCOUNT_NAME", "DISTRIBUTOR_SFDC_ID", "DISTRIBUTOR_ORACLE_ACCOUNT_ID", "DISTRIBUTOR_SFDC_CUSTOMER_KEY", "SPA_CREATED_BY", "SPA_LAST_UPDATED_BY", "SPA_FINAL_APPROVAL_DATE_TIME") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH SH AS
	(
		SELECT * FROM CHM_MSI_SPA_HEADER_V5
	),
 SI AS
	(
	SELECT * FROM CHM_MSI_SPA_INSTALLER_V5
	),  
 SD AS
	(
	SELECT * FROM CHM_MSI_SPA_DISTI_V5
	), 	
SL AS (
	SELECT * FROM CHM_MSI_SPA_LINES_ALL_V5
	),
SG AS
(	SELECT 'MAIN_GEO' geo_source, csh.spa_number, 
		csg.country,csg.state,csg.zip,csg.sfdc_state,csg.sfdc_zip
	 FROM 	chm_msi_spa_header csh
			,chm_msi_spa_geo_details_v5 csg
	 WHERE 	--csh.spa_number=csg.spa_number
			csh.id=csg.spa
)	 
SELECT
	SH.CHM_SPA_ID,
	SL.CHM_SPA_LINE_ID,
	SH.SPA_NUMBER,
	SH.PRIORITY DISTI_PRIORITY,
	SD.DISTI_SOURCE,
	SD.ACCOUNT_NAME SFDC_DISTI_NAME,
	SD.SFDC_ACCOUNT_ID SFDC_DISTI_ACCOUNT_ID,
	SD.SFDC_ORACLE_CUSTOMER_NUMBER,
	SD.ORACLE_CUSTOMER_NUMBER SFDC_ORACLE_CUSTOMER_NUMBER_FULL,
	SH.OPPORTUNITY_OWNER,
	SI.INSTALLER_SOURCE,
	SI.CHM_ACCOUNT_ID INSTALLER_CHM_ACCOUNT_ID,
	SI.SFDC_ACCOUNT_ID INSTALLER_SFDC_ACCOUNT_ID,
	SI.ACCOUNT_NAME INSTALLER_ACCOUNT_NAME,
	SI.CUSTOMER_KEY INSTALLER_CUSTOMER_KEY,
	SI.ACCOUNT_RECORD_TYPE INSTALLER_ACCOUNT_TYPE,
	SI.ACCOUNT_STATUS INSTALLER_ACCOUNT_STATUS,
	SI.ACCOUNT_OWNER INSTALLER_ACCOUNT_OWNER,
	SI.ENLIGHTEN_INSTALLER_ID,
	SG.COUNTRY,
	SG.STATE,
	SG.ZIP,
	SG.SFDC_STATE,
	SG.SFDC_ZIP,
	SH.PRIMARY_PARTNER,
	SH.SPA_NAME,
	SH.GEOGRAPHY,
	SH.STAGE,
	SH.OPPORTUNITY_NAME,
	SH.DEAL_LOGISTICS,
	SH.STATUS,
	SH.SPECIAL_PRICING_TYPE,
	SH.FINAL_APPROVAL_TIME,
	SH.SPA_START_DATE,
	SH.SPA_EXPIRATION_DATE,
	SH.DEAL_CATEGORY,
	SH.SPA_TOTAL_PRICE_CURRENCY SPA_CURRENCY,
	SH.SPA_TOTAL_PRICE_CURRENCY,
	SH.SPA_TOTAL_PRICE,
	SH.SPA_CREATED_DATE,
	SH.SPA_TYPE,
	SH.SPA_BACK_DATED,
	SL.ITEM_SOURCE,
	SL.PRIORITY ITEM_PRIORITY,
	SL.SPA_LINE_TYPE,
	SL.LINE_ITEM_NUMBER,
	SL.ITEM_NUMBER,
	SL.REBATE_ITEM_NUMBER,
	SL.MIN_QUANTITY,
	SL.REBATE_AMOUNT,
	SL.REBATE_TIER,
    SL.REBATE_TIER_MIN_QTY,
    SL.REBATE_TIER_MAX_QTY,
	SH.ATTRIBUTE_CONTEXT,
	SH.ATTRIBUTE1,
	SH.ATTRIBUTE2,
	SH.ATTRIBUTE3,
	SH.ATTRIBUTE4,
	SH.ATTRIBUTE5,
	SH.ATTRIBUTE6,
	SH.ATTRIBUTE7,
	SH.ATTRIBUTE8,
	SH.ATTRIBUTE9,
	SH.ATTRIBUTE10,
	SH.ATTRIBUTE11,
	SH.ATTRIBUTE12,
	SH.ATTRIBUTE13,
	SH.ATTRIBUTE14,
	SH.ATTRIBUTE15,
	SH.CREATED_BY,
	SH.CREATION_DATE,
	SH.LAST_UPDATED_BY,
	SH.LAST_UPDATED_DATE,
	SH.OPPORTUNITY_OWNER_ID,
	SH.ID,
	SH.SPA_OPPORTUNITY_ID,
	SH.NEW_RENEWAL,
	SH.DISTRIBUTOR_ACCOUNT_NAME,
	SH.DISTRIBUTOR_SFDC_ID,
	SH.DISTRIBUTOR_ORACLE_ACCOUNT_ID,
	SH.DISTRIBUTOR_SFDC_CUSTOMER_KEY,
	SH.SPA_CREATED_BY,
	SH.SPA_LAST_UPDATED_BY,
	SH.SPA_FINAL_APPROVAL_DATE_TIME
FROM 
	SH,
	SI,
	SL,
	SD,
	SG
WHERE
	SH.SPA_NUMBER=SI.SPA_NUMBER
AND SH.SPA_NUMBER=SL.SPA_NUMBER
AND SH.SPA_NUMBER=SD.SPA_NUMBER(+)
AND SH.SPA_NUMBER=SG.SPA_NUMBER
;
