--------------------------------------------------------
--  DDL for View CHM_MSI_CLAIM_BATCH_EXCEPTIONS_V
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_CLAIM_BATCH_EXCEPTIONS_V" ("EXCEPTION_ID", "BATCH_ID", "LINE_ID", "RUN_ID", "CURRENT_FLAG", "ERROR_TYPE", "ERROR_CODE", "ERROR_MESSAGE", "START_DATE", "END_DATE", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT "EXCEPTION_ID","BATCH_ID","LINE_ID","RUN_ID","CURRENT_FLAG","ERROR_TYPE","ERROR_CODE","ERROR_MESSAGE","START_DATE","END_DATE","ATTRIBUTE_CONTEXT","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4","ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9","ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14","ATTRIBUTE15","CREATED_BY","CREATION_DATE","LAST_UPDATED_BY","LAST_UPDATED_DATE","SOURCE_APP_ID","ENTERPRISE_ID","IP_ADDRESS","USER_AGENT" FROM CHM_MSI_CLAIM_BATCH_EXCEPTIONS
;
