--------------------------------------------------------
--  DDL for View CHM_MSI_SPA_GEO_DETAILS_V
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_SPA_GEO_DETAILS_V" ("SPA_NUMBER", "CHM_MSI_SPA_GEO_DETAIL_ID", "ID", "COUNTRY", "STATE", "ZIP", "STATUS", "SFDC_CREATED_DATE", "SFDC_LAST_UPDATE_DATE", "SFDC_CREATED_BY", "SFDC_LAST_UPDATED_BY", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT", "OIC_INSTANCE_ID", "IS_DELETED", "NAME", "CURRENCY_ISO_CODE", "SYSTEM_MOD_STAMP", "LAST_VIEWED_DATE", "LAST_REFERENCED_DATE", "SPA", "LAST_ACTIVITY_DATE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT S.SPA_NUMBER, I."CHM_MSI_SPA_GEO_DETAIL_ID",I."ID",I."COUNTRY",I."STATE",I."ZIP",I."STATUS",I."SFDC_CREATED_DATE",I."SFDC_LAST_UPDATE_DATE",I."SFDC_CREATED_BY",I."SFDC_LAST_UPDATED_BY",I."ATTRIBUTE_CONTEXT",I."ATTRIBUTE1",I."ATTRIBUTE2",I."ATTRIBUTE3",I."ATTRIBUTE4",I."ATTRIBUTE5",I."ATTRIBUTE6",I."ATTRIBUTE7",I."ATTRIBUTE8",I."ATTRIBUTE9",I."ATTRIBUTE10",I."ATTRIBUTE11",I."ATTRIBUTE12",I."ATTRIBUTE13",I."ATTRIBUTE14",I."ATTRIBUTE15",I."CREATED_BY",I."CREATION_DATE",I."LAST_UPDATED_BY",I."LAST_UPDATED_DATE",I."SOURCE_APP_ID",I."ENTERPRISE_ID",I."IP_ADDRESS",I."USER_AGENT",I."OIC_INSTANCE_ID",I."IS_DELETED",I."NAME",I."CURRENCY_ISO_CODE",I."SYSTEM_MOD_STAMP",I."LAST_VIEWED_DATE",I."LAST_REFERENCED_DATE",I."SPA",I."LAST_ACTIVITY_DATE" FROM CHM_MSI_SPA_GEO_DETAILS I,
    CHM_MSI_SPA_HEADER S
    WHERE I.SPA=S.ID(+)
;
