--------------------------------------------------------
--  DDL for View CHM_MSI_CLAIM_REJECT_REASONS_V
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_CLAIM_REJECT_REASONS_V" ("REASON_ID", "REASON_TYPE", "BATCH_ID", "CLAIM_LINE_ID", "REASON_CODE", "REASON_DESCRIPTION", "REASON_COMMENT", "ATTRIBUTE_TYPE", "ATTRIBUTE_VALUE", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select "REASON_ID","REASON_TYPE","BATCH_ID","CLAIM_LINE_ID","REASON_CODE","REASON_DESCRIPTION","REASON_COMMENT","ATTRIBUTE_TYPE","ATTRIBUTE_VALUE","ATTRIBUTE_CONTEXT","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4","ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9","ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14","ATTRIBUTE15","CREATED_BY","CREATION_DATE","LAST_UPDATED_BY","LAST_UPDATED_DATE","SOURCE_APP_ID","ENTERPRISE_ID","IP_ADDRESS","USER_AGENT" from
CHM_MSI_CLAIM_REJECT_REASONS
;
