--------------------------------------------------------
--  DDL for View CHM_MSI_CLAIM_LOGS_V
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_CLAIM_LOGS_V" ("REPORT_REQUEST_ID", "BATCH_LOG_ID", "FILE_ID", "BATCH_ID", "LINE_ID", "RUN_ID", "LOG_TYPE", "LOG_STATUS", "LOG_CODE", "LOG_MSG", "CURRENT_FLAG", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT "REPORT_REQUEST_ID", "BATCH_LOG_ID","FILE_ID","BATCH_ID","LINE_ID","RUN_ID",
  "LOG_TYPE","LOG_STATUS","LOG_CODE","LOG_MSG","CURRENT_FLAG",
  "ATTRIBUTE_CONTEXT","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4",
  "ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9",
  "ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14",
  "ATTRIBUTE15","CREATED_BY","CREATION_DATE","LAST_UPDATED_BY",
  "LAST_UPDATED_DATE","SOURCE_APP_ID","ENTERPRISE_ID","IP_ADDRESS","USER_AGENT" FROM CHM_MSI_CLAIM_LOGS
;
