--------------------------------------------------------
--  DDL for View CHM_MSI_CLAIM_BATCH_HEADER_AV
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_CLAIM_BATCH_HEADER_AV" ("BATCH_ID", "FILE_ID", "PAYEE_ID", "PAYEE_TYPE", "BATCH_STATUS", "BATCH_START_DATE", "BATCH_END_DATE", "BATCH_SOURCE", "CLAIM_TYPE", "BATCH_REFERENCE", "RUN_ID", "REPORT_REQUEST_ID", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
		cb.BATCH_ID, cb.FILE_ID, cb.PAYEE_ID, cb.PAYEE_TYPE, cb.BATCH_STATUS, cb.BATCH_START_DATE, cb.BATCH_END_DATE, cb.BATCH_SOURCE, cb.CLAIM_TYPE
		, cb.BATCH_REFERENCE, 
    cb.RUN_ID, cb.REPORT_REQUEST_ID, cb.ATTRIBUTE_CONTEXT, cb.ATTRIBUTE1, cb.ATTRIBUTE2, cb.ATTRIBUTE3, cb.ATTRIBUTE4
		, cb.ATTRIBUTE5, cb.ATTRIBUTE6, cb.ATTRIBUTE7, cb.ATTRIBUTE8, cb.ATTRIBUTE9, cb.ATTRIBUTE10, cb.ATTRIBUTE11, cb.ATTRIBUTE12, cb.ATTRIBUTE13
		, cb.ATTRIBUTE14, cb.ATTRIBUTE15, cb.CREATED_BY, cb.CREATION_DATE, cb.LAST_UPDATED_BY, cb.LAST_UPDATED_DATE, cb.SOURCE_APP_ID, cb.ENTERPRISE_ID
		, cb.IP_ADDRESS, cb.USER_AGENT
	FROM
		CHM_MSI_CLAIM_BATCH cb
;
