--------------------------------------------------------
--  DDL for View CHM_MSI_SYS_SIZE_INCENTIVE_V1
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_SYS_SIZE_INCENTIVE_V1" ("CHM_MSI_SPA_SYS_SIZE_ID", "ID", "STATUS", "SFDC_CREATED_DATE", "SFDC_LAST_UPDATE_DATE", "SFDC_CREATED_BY", "SFDC_LAST_UPDATED_BY", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT", "OIC_INSTANCE_ID", "IS_DELETED", "NAME", "CURRENCY_ISO_CODE", "SYSTEM_MOD_STAMP", "LAST_ACTIVITY_DATE", "LAST_VIEWED_DATE", "LAST_REFERENCED_DATE", "SPA", "UNIQUE_KEY", "PRODUCT", "TIER_NAME", "MIN_QTY", "MAX_QTY", "REBATE_AMOUNT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT 
csi.CHM_MSI_SPA_SYS_SIZE_ID,
csi.ID,
csi.STATUS,
csi.SFDC_CREATED_DATE,
csi.SFDC_LAST_UPDATE_DATE,
csi.SFDC_CREATED_BY,
csi.SFDC_LAST_UPDATED_BY,
csi.ATTRIBUTE_CONTEXT,
csi.ATTRIBUTE1,
csi.ATTRIBUTE2,
csi.ATTRIBUTE3,
csi.ATTRIBUTE4,
csi.ATTRIBUTE5,
csi.ATTRIBUTE6,
csi.ATTRIBUTE7,
csi.ATTRIBUTE8,
csi.ATTRIBUTE9,
csi.ATTRIBUTE10,
csi.ATTRIBUTE11,
csi.ATTRIBUTE12,
csi.ATTRIBUTE13,
csi.ATTRIBUTE14,
csi.ATTRIBUTE15,
csi.CREATED_BY,
csi.CREATION_DATE,
csi.LAST_UPDATED_BY,
csi.LAST_UPDATED_DATE,
csi.SOURCE_APP_ID,
csi.ENTERPRISE_ID,
csi.IP_ADDRESS,
csi.USER_AGENT,
csi.OIC_INSTANCE_ID,
csi.IS_DELETED,
csi.NAME,
csi.CURRENCY_ISO_CODE,
csi.SYSTEM_MOD_STAMP,
csi.LAST_ACTIVITY_DATE,
csi.LAST_VIEWED_DATE,
csi.LAST_REFERENCED_DATE,
csi.SPA,
csi.UNIQUE_KEY,
csi.PRODUCT,
DECODE(SUBSTR(csi.TIER_NAME,1,5),'TIER1','Tier 1','TIER2','Tier 2','TIER3','Tier 3','TIER4','Tier 4','TIER5','Tier 5',TIER_NAME) tier_name,
DECODE(SUBSTR(csi.TIER_NAME,1,5),'TIER1',csh.tier1_min,'TIER2',csh.tier2_min,'TIER3',csh.tier3_min,'TIER4',csh.tier4_min,'TIER5',csh.tier5_min,99999999) min_qty,
DECODE(SUBSTR(csi.TIER_NAME,1,5),'TIER1',csh.tier1_max,'TIER2',csh.tier2_max,'TIER3',csh.tier3_max,'TIER4',csh.tier4_max,'TIER5',csh.tier5_max,99999999) max_qty,
NVL(csi.REBATE_AMOUNT,0) REBATE_AMOUNT
FROM (select * from CHM_MSI_SYS_SIZE_INCENTIVE
      unpivot include nulls ( 
      rebate_amount for tier_name in (tier1_rebate_amount, tier2_rebate_amount, 
      tier3_rebate_amount, tier4_rebate_amount, tier5_rebate_amount))
      ) csi,
CHM_MSI_SPA_HEADER csh
WHERE csi.spa=csh.id
;
