--------------------------------------------------------
--  DDL for View CHM_MSI_CLAIM_BATCH_LINES_AV
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_CLAIM_BATCH_LINES_AV" ("LINE_ID", "BATCH_ID", "FILE_RECORD_ID", "LINE_STATUS", "APPROVAL_STATUS", "DUPLICATE_LINE_ID", "CLAIM_DATE", "CLAIM_TYPE", "SPA_NUMBER", "SPA_START_DATE", "SPA_EXPIRATION_DATE", "CHM_ENLIGHTEN_DEVICE_ID", "DEVICE_ITEM_NUMBER", "SERIAL_NUMBER", "HW_PART_NUMBER", "DEVICE_CREATED_DATE", "QTY_SOLD", "UOM", "REBATE_ITEM_NUMBER", "PRODUCT_TYPE", "PRODUCT_FAMILY", "REBATE_TYPE", "REBATE_TIER", "UNIT_CLAIM_AMOUNT", "EXTENDED_CLAIM_AMOUNT", "USER_UNIT_CLAIM_AMOUNT", "USER_EXTENDED_CLAIM_AMOUNT", "CURRENCY", "CHM_ENLIGHTEN_SITE_ID", "SITE_ID", "SITE_FIRST_INTERVAL_END_DATE", "SITE_STAGE", "SITE_TYPE", "SITE_NAME", "SITE_ADDRESS_ID", "SITE_ADDRESS1", "SITE_ADDRESS2", "SITE_CITY", "SITE_STATE", "SITE_ZIP", "SITE_COUNTRY", "PAYEE_ID", "PAYEE_TYPE", "PAYEE_SFDC_CUSTOMER_KEY", "PAYEE_SFDC_ACCOUNT_NAME", "PAYEE_ENLIGHTEN_INSTALLER_ID", "INSTALLER_ID", "INSTALLER_SFDC_CUSTOMER_KEY", "INSTALLER_SFDC_ACCOUNT_NAME", "INSTALLER_ENLIGHTEN_INSTALLER_ID", "ORACLE_ORDER_TYPE", "ORACLE_DISTI_ID", "ORACLE_DISTI_ACCOUNT_NUMBER", "ORACLE_DISTI_NAME", "REASON_CODE", "IS_OVERRIDDEN", "PARTNER_CLAIM_NUMBER", "PARTNER_CLAIM_LINE_NUMBER", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT", "RUN_ID", "CHM_DEVICE_REBATE_ID", "STAGE_3_STATUS_DATE", "ORACLE_AP_INVOICE_NUMBER", "ORACLE_AP_INVOICE_ID", "AP_INVOICE_REQUEST_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
cbl.line_id,
cbl.batch_id,
cbl.file_record_id,
cbl.line_status,  --Lookup type CHM_MSI_CLAIM_BATCH_LINE_STATUS
cbl.approval_status,
cbl.duplicate_line_id,
cbl.claim_date,
cbl.claim_type,	--Lookup Type CHM_MSI_CLAIM_TYPE
cbl.spa_number,
TRUNC(cmsh.spa_start_date) spa_start_date,
TRUNC(cmsh.spa_expiration_date) spa_expiration_date,
cbl.chm_enlighten_device_id,
cbl.device_item_number,
cbl.serial_number,
cbl.hw_part_number,
cbl.device_created_date,
cbl.qty_sold,
cbl.uom,
cbl.rebate_item_number,
cbl.product_type,
cbl.product_family,
cbl.rebate_type,  --Lookup Type CHM_MSI_REBATE_TYPE
cbl.rebate_tier,
cbl.unit_claim_amount,
cbl.extended_claim_amount,
cbl.user_unit_claim_amount,
cbl.user_extended_claim_amount,
cbl.currency,
cbl.chm_enlighten_site_id,
cbl.site_id,
cbl.site_first_interval_end_date,
cbl.site_stage,
cbl.site_type,
cbl.site_name,
cbl.site_address_id,
cbl.site_address1,
cbl.site_address2,
cbl.site_city,
cbl.site_state,
cbl.site_zip,
cbl.site_country,
cbl.payee_id,
cbl.payee_type,
csam.customer_key payee_sfdc_customer_key,
csam.account_name payee_sfdc_account_name,
csam.enlighten_installer_id payee_enlighten_installer_id,
cbl.installer_id,
installer.customer_key installer_sfdc_customer_key,
installer.account_name installer_sfdc_account_name,
installer.enlighten_installer_id installer_enlighten_installer_id,
cbl.oracle_order_type,
cbl.oracle_disti_id,
cbl.oracle_disti_account_number,
cda.party_name oracle_disti_name,
cbl.reason_code,
cbl.is_overridden,
cbl.partner_claim_number,
cbl.partner_claim_line_number,
cbl.attribute_context,
cbl.attribute1,
cbl.attribute2,
cbl.attribute3,
cbl.attribute4,
cbl.attribute5,
cbl.attribute6,
cbl.attribute7,
cbl.attribute8,
cbl.attribute9,
cbl.attribute10,
cbl.attribute11,
cbl.attribute12,
cbl.attribute13,
cbl.attribute14,
cbl.attribute15,
cbl.created_by,
cbl.creation_date,
cbl.last_updated_by,
cbl.last_updated_date,
cbl.source_app_id,
cbl.enterprise_id,
cbl.ip_address,
cbl.user_agent,
cbl.run_id,
cbl.chm_device_rebate_id,
cbl.stage_3_status_date,
cbl.oracle_ap_invoice_number,
cbl.oracle_ap_invoice_id,
cbl.ap_invoice_request_id
FROM
	chm_msi_claim_batch_lines cbl,
	chm_sfdc_account_master csam,
	chm_sfdc_account_master installer,
	chm_dist_accounts cda,
  chm_msi_spa_header cmsh
WHERE 
	cbl.payee_id=csam.chm_account_id(+)
AND cbl.installer_id=installer.chm_account_id(+)
AND cbl.oracle_disti_account_number=cda.account_number(+)
AND cbl.spa_number=cmsh.spa_number(+)
;
