CREATE OR REPLACE FORCE EDITIONABLE VIEW "CHM"."CHM_MSI_DEVICE_REBATES_V1" ("CHM_DEVICE_REBATE_ID", "CHM_ENLIGHTEN_SITE_ID", "CHM_ENLIGHTEN_DEVICE_ID", "SPA_NUMBER", "SPA_LINE_ID", "SERIAL_NUMBER", "HW_PART_NUM", "DEVICE_CREATED_DATE", "DEVICE_FIRST_INTERVAL_END_DATE", "PRODUCT_TYPE", "PRODUCT_FAMILY", "DEVICE_ITEM_NUMBER", "REBATE_ITEM_NUMBER", "REBATE_TYPE", "REBATE_TIER", "SPA_ORIGINAL_AMOUNT", "CLAIM_DATE", "REBATE_CURRENCY", "REBATE_AMOUNT", "REBATE_SOURCE", "REBATE_STATUS", "CLAIM_BATCH_ID", "CLAIM_LINE_ID", "ORACLE_AP_INVOICE_NUMBER", "ORACLE_AP_INVOICE_ID", "REBATE_PAYEE_TYPE", "REBATE_PAYEE_ID", "REBATE_PAYEE_NAME", "REBATE_PAYEE_CUSTOMER_KEY", "REBATE_PAYEE_COUNTRY", "REBATE_PAYEE_GEOGRAPHY", "REBATE_PAYEE_ACCOUNT_OWNER", "REBATE_PAYEE_ENLIGHTEN_INSTALLER_ID", "DISTI_ORACLE_ACCOUNT_NUMBER", "DISTI_SFDC_KEY", "DISTI_ORACLE_NAME", "ORACLE_ORDER_TYPE", "ENLIGHTEN_SITE_ID", "ENLIGHTEN_SITE_NAME", "ENLIGHTEN_SITE_TYPE", "OWNER_ID", "INSTALLER_ID", "MAINTAINER_ID", "SITE_FIRST_INTERVAL_END_DATE", "PCU_CHANNEL_COUNT", "ENVOY_COUNT", "ACB_COUNT", "NSR_COUNT", "ENCHARGE_COUNT", "ENPOWER_COUNT", "PCU_TYPES", "STATUS_CODE", "AC_VOLTAGE", "SITE_CREATED_DATE", "MEASURED_ACV", "IS_LEASE", "PARTNER_ID", "SYSTEM_HOST_ID", "ENLIGHTEN_SITE_URL", "SITE_CURRENT_STAGE", "STAGE_3_STATUS_DATE", "SYSTEM_START_DATE", "ZERO_TOUCH", "ALLOW_API_ACCESS", "LOCATION_ACCESS", "RATE_SCHEDULE", "DESCRIPTION", "OPERATIONAL", "INTERCONNECT_DATE", "INTERNET_CONNECTION_TYPE", "PCU_ATTACHMENT_TYPE", "CONNECTION_TYPE", "SFDC_DRIP_CAMPAIGN_FLAG", "IQEVC_COUNT", "CONSUMPTION_CT", "HEMS", "ADDRESS_ID", "ADDRESS_1", "ADDRESS_2", "ADDRESS_CITY", "ADDRESS_STATE", "ADDRESS_ZIP", "ADDRESS_COUNTRY") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
		cedr.chm_device_rebate_id,
        cedr.chm_enlighten_site_id,
		cedr.chm_enlighten_device_id,
        cedr.spa_number,
        cedr.spa_line_id,
		cedd.serial_num serial_number,
		cedd.HW_PART_NUM,
		cedd.created_date device_created_date,
		cedd.first_interval_end_date	device_first_interval_end_date,
		ceda.product_type,
		ceda.product_family,		
        cedr.device_item_number,
        cedr.rebate_item_number,
        cedr.rebate_type,
        cedr.rebate_tier,
        cedr.spa_original_amount,
        cedr.claim_date,
        cedr.rebate_currency,
        cedr.rebate_amount,
        cedr.rebate_source,
        cedr.rebate_status,
        cedr.claim_batch_id,
        cedr.claim_line_id,
        cedr.oracle_ap_invoice_number,
        cedr.oracle_ap_invoice_id,
        cedr.rebate_payee_type,
        cedr.rebate_payee_id,
		csam.account_name rebate_payee_name,
		csam.customer_key rebate_payee_customer_key,
		csam.country rebate_payee_country,
		csam.geography rebate_payee_geography,
		csam.account_owner rebate_payee_account_owner,
		csam.enlighten_installer_id rebate_payee_enlighten_installer_id,
		ceda.disti_oracle_account_number,
		ceda.disti_sfdc_key,
		cda.party_name disti_oracle_name,
		ceda.oracle_order_type,		
        cesm.id enlighten_site_id,
        cesm.name enlighten_site_name,
        cesm.type enlighten_site_type,
        cesm.owner_id,
        cesm.installer_id,
        cesm.maintainer_id,
        cesm.first_interval_end_date site_first_interval_end_date,
        cesm.pcu_channel_count,
        cesm.envoy_count,
        cesm.acb_count,
        cesm.nsr_count,
        cesm.encharge_count,
        cesm.enpower_count,
        cesm.pcu_types,
        cesm.status_code,
        cesm.ac_voltage,
        cesm.created_date site_created_date,
        cesm.measured_acv,
        cesm.is_lease,
        cesm.partner_id,
        cesm.system_host_id,
        cesm.enlighten_site_url,
        cesm.stage site_current_stage,
		cesm.stage_3_status_date,
        cesm.system_start_date,
        cesm.zero_touch,
        cesm.allow_api_access,
        cesm.location_access,
        cesm.rate_schedule,
        cesm.description,
        cesm.operational,
        cesm.interconnect_date,
        cesm.internet_connection_type,
        cesm.pcu_attachment_type,
        cesm.connection_type,
        cesm.sfdc_drip_campaign_flag,
        cesm.iqevc_count,
        cesm.consumption_ct,
        cesm.hems,
        cesm.address_id,
        cesm.address_1,
        cesm.address_2,
        cesm.address_city,
        cesm.address_state,
        cesm.address_zip,
        cesm.address_country
    FROM
        chm_enlighten_device_rebates cedr,
        chm_enlighten_site_master    cesm,
		chm_enlighten_device_details cedd,
		chm_enlighten_device_attributes ceda,
		chm_dist_accounts cda,
		chm_sfdc_account_master csam
    WHERE
            cedr.chm_enlighten_site_id = cesm.chm_enlighten_site_id
		AND cedr.chm_enlighten_device_id = cedd.chm_enlighten_device_id
		AND cedr.rebate_payee_id=csam.chm_account_id
		AND cedd.chm_enlighten_device_id= ceda.chm_enlighten_device_id(+)
		AND ceda.disti_oracle_account_number=cda.account_number(+);