--------------------------------------------------------
--  DDL for View CHM_MSI_CLAIM_FILES_V
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_MSI_CLAIM_FILES_V" ("FILE_ID", "FILE_TYPE", "FILE_NAME", "FILE_PATH", "FILE_CONTENT", "SHEET_NAME", "FILE_STATUS", "CLAIM_TYPE", "BATCH_REFERENCE", "ATTRIBUTE_CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SOURCE_APP_ID", "ENTERPRISE_ID", "IP_ADDRESS", "USER_AGENT", "FILE_BLOB") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select FILE_ID, FILE_TYPE, FILE_NAME, FILE_PATH, FILE_CONTENT, 
  SHEET_NAME, FILE_STATUS, CLAIM_TYPE, BATCH_REFERENCE, 
  ATTRIBUTE_CONTEXT, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4,
  ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, 
  ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, 
  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, 
  SOURCE_APP_ID, ENTERPRISE_ID, IP_ADDRESS, USER_AGENT, FILE_BLOB
from CHM_MSI_CLAIM_FILES
;
