--------------------------------------------------------
--  DDL for View CHM_ENLIGHTEN_SITE_DEVICE_ATTRIBUTES_V1
--------------------------------------------------------

  CREATE OR REPLACE VIEW "CHM_ENLIGHTEN_SITE_DEVICE_ATTRIBUTES_V1" ("CHM_ENLIGHTEN_DEVICE_ID", "SITE_ID", "ENLIGHTEN_INSTALLER_ID", "INSTALLER_ID", "ENLIGHTEN_MAINTAINER_ID", "INSTALLER_SFDC_CUSTOMER_KEY", "INSTALLER_CHM_ACCOUNT_ID", "INSTALLER_SFDC_ACCOUNT_ID", "INSTALLER_SFDC_ACCOUNT_NAME", "INSTALLER_SFDC_ACCOUNT_TYPE", "INSTALLER_SFDC_PARENT_ACCOUNT_NAME", "INSTALLER_SFDC_PARENT_ACCOUNT_ID", "BANK_DETAILS_FLAG", "SERIAL_NUM", "TYPE", "HW_PART_NUM", "SKU", "RETIRED", "DEVICE_CREATED_DATE", "DEVICE_FIRST_INTERVAL_END_DATE", "STAGE_3_STATUS_DATE", "PARENT_SERIAL_NUM", "PV_MODULE_MANUFACTURER_NAME", "PV_MODULE_MODEL_NAME", "PV_MODULE_DCW", "PV_MODULE_CELL_COUNT", "SW_VERSION", "BATCH_ID", "LAST_BATCH_ID", "BATCH_PROCESS_COUNT", "CHM_DEVICE_ATTRIBUTE_ID", "DISTI_ORACLE_ACCOUNT_NUMBER", "DISTI_ORACLE_ACCOUNT_ID", "DISTI_SFDC_KEY", "ORACLE_ORDER_TYPE", "ITEM_NUMBER", "UNIT_ACTIVATION_REBATE_ITEM_NUMBER", "SYSTEM_ATTACHMENT_REBATE_ITEM_NUMBER", "SYSTEM_SIZE_REBATE_ITEM_NUMBER", "PRODUCT_FAMILY", "PRODUCT_TYPE", "REBATE_EFFECTIVE_DATE", "DEVICE_QUANTITY", "MSI_REBATE_ELIGIBLE", "MSI_REBATE_ELIGIBILE_REASON", "MSI_REBATE_ELIGIBILITY_DERIVED_DATE", "UNIT_ACTIVATION_SPA_NUMBER", "SYSTEM_ATTACHMENT_SPA_NUMBER", "SYSTEM_SIZE_SPA_NUMBER", "UNIT_ACTIVATION_SPA_LINE_ID", "SYSTEM_ATTACHMENT_SPA_LINE_ID", "SYSTEM_SIZE_SPA_LINE_ID", "UNIT_ACTIVATION_REBATE_AMOUNT", "SYSTEM_ATTACHMENT_REBATE_AMOUNT", "UNIT_ACTIVATION_PAYEE_TYPE", "UNIT_ACTIVATION_PAYEE_ID", "SYSTEM_ATTACHMENT_PAYEE_TYPE", "SYSTEM_ATTACHMENT_PAYEE_ID", "SYSTEM_SIZE_PAYEE_TYPE", "SYSTEM_SIZE_PAYEE_ID", "SYSTEM_SIZE_TIER_CALC_BATCH_ID", "SYSTEM_SIZE_TIER_CALC_PROCESS_COUNT", "SYSTEM_SIZE_TIER_CALC_LAST_BATCH_ID", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATE_DATE", "IP_ADDRESS", "USER_AGENT", "CHM_ENLIGHTEN_SITE_ID", "NAME", "SITE_TYPE", "OWNER_ID", "MAINTAINER_ID", "SITE_FIRST_INTERVAL_END_DATE", "PCU_CHANNEL_COUNT", "ENVOY_COUNT", "ACB_COUNT", "NSR_COUNT", "ENCHARGE_COUNT", "ENPOWER_COUNT", "PCU_TYPES", "STATUS_CODE", "AC_VOLTAGE", "SITE_CREATED_DATE", "MEASURED_ACV", "IS_LEASE", "PARTNER_ID", "SYSTEM_HOST_ID", "ENLIGHTEN_SITE_URL", "STAGE", "SYSTEM_START_DATE", "ZERO_TOUCH", "ALLOW_API_ACCESS", "LOCATION_ACCESS", "RATE_SCHEDULE", "DESCRIPTION", "OPERATIONAL", "INTERCONNECT_DATE", "INTERNET_CONNECTION_TYPE", "PCU_ATTACHMENT_TYPE", "CONNECTION_TYPE", "SFDC_DRIP_CAMPAIGN_FLAG", "IQEVC_COUNT", "CONSUMPTION_CT", "HEMS", "ADDRESS_ID", "ADDRESS_1", "ADDRESS_2", "ADDRESS_CITY", "ADDRESS_STATE", "ADDRESS_ZIP", "ADDRESS_COUNTRY", "ADDRESS_TIMEZONE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT 	chmdd.chm_enlighten_device_id,
			chmdd.site_id,
			chms.installer_id enlighten_installer_id,
			csam.chm_account_id installer_id,
			chms.maintainer_id enlighten_maintainer_id,
			csam.customer_key installer_sfdc_customer_key,
			csam.chm_account_id installer_chm_account_id,
			csam.sfdc_account_id installer_sfdc_account_id,		
			csam.account_name installer_sfdc_account_name,
			csam.account_type installer_sfdc_account_type,
			csam.parent_account installer_sfdc_parent_account_name,
			csam.parent_account_id installer_sfdc_parent_account_id,
			NVL(csam.bank_details_flag ,'N') bank_details_flag,
			chmdd.serial_num,
			chmdd.type,
			chmdd.hw_part_num,
			chmdd.sku,
			chmdd.retired,
			chmdd.created_date device_created_date,
			chmdd.first_interval_end_date device_first_interval_end_date,
			chms.stage_3_status_date,				
			chmdd.parent_serial_num,
			chmdd.pv_module_manufacturer_name,
			chmdd.pv_module_model_name,
			chmdd.pv_module_dcw,
			chmdd.pv_module_cell_count,
			chmdd.sw_version,
			--chmda.attribute2 batch_id, --Raj 3/28/2025
			chmda.batch_id,
			chmda.last_batch_id,
			chmda.batch_process_count,			
			chmda.chm_device_attribute_id,
			chmda.disti_oracle_account_number,
			chmda.disti_oracle_account_id,
			chmda.disti_sfdc_key,
			chmda.oracle_order_type,
			chmda.item_number,
			chmda.unit_activation_rebate_item_number,
			chmda.system_attachment_rebate_item_number,
			chmda.system_size_rebate_item_number,
			chmda.product_family,
			chmda.product_type,
			chmda.rebate_effective_date,
			chmda.device_quantity,
			chmda.msi_rebate_eligible,
			chmda.msi_rebate_eligibile_reason,
			chmda.msi_rebate_eligibility_derived_date,
			chmda.unit_activation_spa_number,
			chmda.system_attachment_spa_number,
			chmda.system_size_spa_number,
			chmda.unit_activation_spa_line_id,
			chmda.system_attachment_spa_line_id,
			chmda.system_size_spa_line_id,
			chmda.unit_activation_rebate_amount,
			chmda.system_attachment_rebate_amount,			
			chmda.unit_activation_payee_type ,
			chmda.unit_activation_payee_id ,
			chmda.system_attachment_payee_type ,
			chmda.system_attachment_payee_id ,	
			chmda.system_size_payee_type ,
			chmda.system_size_payee_id ,
			chmda.system_size_tier_calc_batch_id,
			chmda.system_size_tier_calc_process_count,
			chmda.system_size_tier_calc_last_batch_id,		
			chmda.attribute1,
			chmda.attribute2,
			chmda.attribute3,
			chmda.attribute4,
			chmda.attribute5,
			chmda.attribute6,
			chmda.attribute7,
			chmda.attribute8,
			chmda.attribute9,
			chmda.attribute10,
			chmda.attribute11,
			chmda.attribute12,
			chmda.attribute13,
			chmda.attribute14,
			chmda.attribute15,
			chmda.created_by,
			chmda.creation_date,
			chmda.last_updated_by,
			chmda.last_update_date,
			chmda.ip_address,
			chmda.user_agent,
			chms.chm_enlighten_site_id,
			chms.name,
			chms.type site_type,
			chms.owner_id,
			--chms.installer_id,
			chms.maintainer_id,
			chms.first_interval_end_date site_first_interval_end_date,
			chms.pcu_channel_count,
			chms.envoy_count,
			chms.acb_count,
			chms.nsr_count,
			chms.encharge_count,
			chms.enpower_count,
			chms.pcu_types,
			chms.status_code,
			chms.ac_voltage,
			chms.created_date site_created_date,
			chms.measured_acv,
			chms.is_lease,
			chms.partner_id,
			chms.system_host_id,
			chms.enlighten_site_url,
			chms.stage,
			chms.system_start_date,
			chms.zero_touch,
			chms.allow_api_access,
			chms.location_access,
			chms.rate_schedule,
			chms.description,
			chms.operational,
			chms.interconnect_date,
			chms.internet_connection_type,
			chms.pcu_attachment_type,
			chms.connection_type,
			chms.sfdc_drip_campaign_flag,
			chms.iqevc_count,
			chms.consumption_ct,
			chms.hems,
			chms.address_id,
			chms.address_1,
			chms.address_2,
			chms.address_city,
			chms.address_state,
			chms.address_zip,
			chms.address_country,
			chms.address_timezone

	FROM 
			chm_enlighten_site_master chms,
			chm_enlighten_device_details chmdd,
			chm_enlighten_device_attributes chmda,
			chm_sfdc_account_master csam
	WHERE 	
			chms.id=chmdd.site_id
	AND		chmdd.chm_enlighten_device_id = chmda.chm_enlighten_device_id(+)
	AND		chms.installer_id=csam.enlighten_installer_id(+)
;
