alter table CHM_SFDC_ACCOUNT_MASTER ADD CHM_C varchar2(4000);
alter table CHM_SFDC_ACCOUNT_MASTER ADD MERGE_ID_C varchar2(4000);
alter table CHM_SFDC_ACCOUNT_MASTER ADD ENLIGHTEN_COMPANY_DUP_KEY_C varchar2(4000);
