BEGIN
	INSERT INTO CHM_LOOKUP_TYPES (CHM_SOURCE_SYSTEM_ID, SOURCE_APPLICATION_ID, LOOKUP_TYPE, MEANING, DESCRIPTION) VALUES ('1', '-1', 'CHM_ITEM_TYPE_RESTRICTION', 'Item Type Restriction for Item Master Sync ERP to CHM', 'Item Type Restriction for Item Master Sync ERP to CHM');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_ITEM_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'FG NON-SERIAL','FG NON-SERIAL', 'Finished Goods Non Serial');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_ITEM_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'FG SERIAL','FG SERIAL', 'Finished Goods Serial');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_ITEM_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'K','K', 'Kit');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_ITEM_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'M','M', 'Model');
    
    COMMIT;
END;
/
