/**********************************************************************************************************************************
* Type                           : SQL Script                                                                                     *
* Purpose                        : SQL Script for inserting seed data                                                             *
* Created By                     : Gurpreet Singh                                                                                 *
* Created Date                   : 01-Aug-2023                                                                                    *     
***********************************************************************************************************************************
* Date          By                             Company Name                     Version          Details                          * 
* -----------   ---------------------------    ---------------------------      -------------    ---------------------------------*
* 01-Aug-2023   Gurpreet Singh                 Transform Edge                   1.0              Intial Version for POD1          * 
**********************************************************************************************************************************/

--CHM_SOURCE_SYSTEMS
BEGIN
    INSERT INTO CHM_SOURCE_SYSTEMS (SHORT_NAME, NAME, DESCRIPTION) VALUES ('CHM', 'Channel Management', 'Channel Management');
    INSERT INTO CHM_SOURCE_SYSTEMS (SHORT_NAME, NAME, DESCRIPTION) VALUES ('ENLIGHTEN', 'Enlighten', 'Enlighten');
    INSERT INTO CHM_SOURCE_SYSTEMS (SHORT_NAME, NAME, DESCRIPTION) VALUES ('ORACLE', 'Oracle Fusion', 'Oracle Fusion Cloud ERP');
    INSERT INTO CHM_SOURCE_SYSTEMS (SHORT_NAME, NAME, DESCRIPTION) VALUES ('OIC', 'Oracle Integration Cloud', 'Oracle Integration Cloud (OIC)');
    INSERT INTO CHM_SOURCE_SYSTEMS (SHORT_NAME, NAME, DESCRIPTION) VALUES ('SFDC', 'Salesforce', 'Salesforce');
        
    dbms_output.put_line('Data inserted for CHM_SOURCE_SYSTEMS');
END;
/

--CHM_SOURCE_APPLICATIONS
BEGIN
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (-1,1,'CHM','Channel Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (0,3,'FND','Oracle Middleware Extensions for Applications','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (1,3,'SYSADMIN','System Administration','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (2,3,'SETID','Reference Data Sharing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (3,3,'AU','Applications Utilities','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (101,3,'GL','General Ledger','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (140,3,'FA','Assets','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (177,3,'POS','Supplier Portal','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (200,3,'AP','Payables','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (201,3,'PO','Purchasing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (204,3,'XLE','Legal Entity Configurator','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (222,3,'AR','Receivables','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (235,3,'ZX','Tax','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (240,3,'PNL','Real Estate Leases','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (250,3,'QA','Quality Inspection Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (260,3,'CE','Cash Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (283,3,'CN','Incentive Compensation','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (396,3,'PON','Sourcing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (401,3,'INV','Inventory Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (435,3,'FUN','Financials Common Module','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (438,3,'GRA','GRC Application Access Controls Governor','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (440,3,'PJP','Project Portfolio Analysis','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (510,3,'OKC','Enterprise Contracts','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (542,3,'CSI','Installed Base','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (602,3,'XLA','Subledger Accounting','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (665,3,'WSH','Shipping','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (667,3,'QP','Pricing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (673,3,'IBY','Payments','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (695,3,'IEX','Advanced Collections','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (707,3,'CST','Cost Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (708,3,'CZ','Configurator','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (709,3,'EDR','E-Signatures and E-Records','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (724,3,'MSC','Planning Common','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (778,3,'JMF','Supply Chain Localizations','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (800,3,'PER','Global Human Resources','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (801,3,'PAY','Global Payroll','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (802,3,'FF','Fast Formula','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (805,3,'BEN','Benefits','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (808,3,'HXT','Time and Labor','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (821,3,'IRC','Recruiting','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (873,3,'CSE','Asset Tracking','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (7000,3,'JA','Financials for Asia/Pacific','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (7002,3,'JE','Financials for EMEA','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (7003,3,'JG','Financials for Regional Localizations','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (7004,3,'JL','Financials for the Americas','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (8402,3,'GMS','Grants Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (8403,3,'PSP','Labor Distribution','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (8404,3,'IGW','Grants Proposal','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (8901,3,'FV','U.S. Federal Financials','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10000,3,'ASK','Applications Functional Core','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10001,3,'ASM','Functional Setup Manager','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10002,3,'ATK','Application Toolkit','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10003,3,'CMP','Compensation','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10005,3,'CSO','Knowledge Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10006,3,'CSY','Service Request Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10007,3,'CTO','Configure To Order','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10008,3,'DOO','Distributed Order Orchestration','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10009,3,'EGI','Product Hub','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10010,3,'EGO','Product and Catalog Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10011,3,'EGP','Product Model','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10012,3,'EMC','E-Commerce','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10013,3,'EMK','Self Service Common CRM Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10014,3,'EMV','E-Service','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10015,3,'EWM','E-Mail and Web Marketing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10016,3,'EXM','Expenses','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10020,3,'HRA','Performance Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10021,3,'HRC','HCM Common Architecture','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10022,3,'HRT','Profile Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10023,3,'HRW','HCM Configuration Workbench','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10024,3,'HZ','Trading Community Model','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10028,3,'MCT','Multichannel Technologies','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10029,3,'MKL','Lead Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10031,3,'MKT','Marketing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10032,3,'MOO','Opportunity Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10033,3,'MOT','Territory Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10034,3,'MOW','Work Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10035,3,'PJB','Project Billing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10036,3,'PJC','Project Costing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10037,3,'PJF','Project Foundation','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10038,3,'PJL','Project Collaboration','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10039,3,'PJO','Project Control','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10040,3,'PJR','Project Resource Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10041,3,'PJS','Project Performance Reporting','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10042,3,'PJT','Project Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10044,3,'POZ','Supplier Model','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10048,3,'QSC','Sales Catalog','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10049,3,'RCV','Receiving','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10051,3,'WLM','Workforce Lifecycle Manager','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10052,3,'XCC','Budgetary Control','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10053,3,'ZBS','Sales','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10054,3,'ZCA','Common CRM','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10055,3,'ZCC','Contact Center Application','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10056,3,'ZCH','Trading Community Hub','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10057,3,'ZCP','Trading Community Policies','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10058,3,'ZCQ','Trading Community Data Quality','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10059,3,'ZFS','Field Service Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10061,3,'ZMC','Marketing Common Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10062,3,'ZMM','Applications Common Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10063,3,'ZOC','Order Capture Common Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10064,3,'ZOE','CRM for Microsoft Outlook','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10065,3,'ZON','Contact Center Common Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10066,3,'ZSF','Sales Forecasting','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10067,3,'ZVC','CRM Infrastructure Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10068,3,'YPD','Demand Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10069,3,'HTS','Workforce Scheduling','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10070,3,'MOP','Promotions and Deal Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10071,3,'POR','Self Service Procurement','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10076,3,'HRX','HCM Country and Vertical Extensions','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10077,3,'MSP','Global Order Promising','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10082,3,'MSS','Production Scheduling','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10083,3,'YPA','Sales and Operations Planning','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10086,3,'HRS','Social Connection','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10088,3,'XLH','Accounting Hub','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10089,3,'ZMF','Disconnected Mobile Client','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10090,3,'ZMS','Mobile Sales','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10091,3,'ZSP','Sales Prediction Engine','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10092,3,'ZST','State Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10094,3,'ZCM','Customer Center','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10095,3,'ZCX','CRM Application Composer','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10096,3,'CMR','Receipt Accounting','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10097,3,'HRG','Goal Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10098,3,'HRR','Talent Review','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10099,3,'CMS','Total Compensation Statement','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10101,3,'HMO','Workforce Modeling','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10103,3,'HWP','Workforce Predictions','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10105,3,'ACR','Application Common Resources','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10106,3,'FBI','Transactional Business Intelligence','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10107,3,'HRL','Workforce Directory Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10108,3,'RCS','Supply Chain Management Common Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10109,3,'ACT','Advanced Constraint Technology','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10110,3,'ANC','Absence Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10111,3,'ZPM','Partner Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10112,3,'ATM','Topology Manager','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10114,3,'DOS','Supply Chain Orchestration','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10115,3,'FOS','Supply Chain Financial Orchestration Foundation','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10116,3,'FOD','SaaS Enablement','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10119,3,'ACE','Product Lifecycle Portfolio Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10120,3,'ACN','Product Requirements and Ideation Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10121,3,'ACD','Product Concept Design','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10124,3,'ACA','Product Development','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10125,3,'PJG','Project Integration Gateway','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10126,3,'AFH','Help Portal Content','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10127,3,'ZSO','Activity Stream for CRM','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10128,3,'ZMG','Migration for Siebel CRM','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10129,3,'POQ','Supplier Qualification','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10130,3,'GTG','Risks and Controls','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10131,3,'CCC','GRC Configuration Controls Governor','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10132,3,'GRP','GRC Audit Controls Composer','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10134,3,'ACH','Common Search','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10135,3,'ACL','Common Analytics','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10136,3,'ACJ','Common Java Authorization','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10144,3,'MGH','Migration for PeopleSoft HCM','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10145,3,'MGF','Migration for PeopleSoft FSCM','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10446,3,'HWM','Workforce Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10447,3,'MCO','Migration for E-Business Common Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10448,3,'MFI','Migration for E-Business Financials','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10449,3,'HRQ','Questionnaire','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10450,3,'CML','Landed Cost Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10452,3,'MPJ','Migration for E-Business Projects','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10453,3,'MSM','Migration for E-Business SCM','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10454,3,'MTC','Migration for E-Business TCA','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10455,3,'VRM','Revenue Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10456,3,'HRM','Succession Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10457,3,'MHC','Migration for E-Business HCM','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10458,3,'MIC','Migration for E-Business IC','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10459,3,'MPR','Migration for E-Business Procurement','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10460,3,'ACM','CRM Analytics','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10462,3,'PJE','Project Management Control','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10463,3,'ISM','Social Media and Intelligence','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10464,3,'YPC','Planning Collaboration','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10466,3,'YPS','Supply Planning','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10468,3,'YPB','Planning Central','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10469,3,'FTA','Tap for Oracle Applications','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10470,3,'HNS','Workforce Health and Safety Incidents','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10471,3,'MKW','Web Marketing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10472,3,'GRC','Enterprise Governance, Risk, and Compliance Manager','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10473,3,'PNP','Real Estate Portfolio Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10474,3,'PNR','Real Estate Accounting','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10475,3,'ARB','Bill Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10476,3,'ZMH','Upgrade Assistant for Oracle CRM On Demand','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10477,3,'CMF','Fiscal Document Capture','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10478,3,'CMK','Collaboration Messaging Framework','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10479,3,'GTI','Applications Integration for Oracle Global Trade Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10480,3,'MTI','Applications Integration for Oracle Transportation Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10481,3,'HWR','Workforce Reputation Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10483,3,'HRD','Career Development','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10484,3,'EVI','Enterprise Visualization','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10485,3,'EVN','Visual Information Navigator','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10486,3,'ASE','Applications Security','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10487,3,'EGS','Product Hub Portal','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10488,3,'VFA','Voice for Oracle Cloud Applications','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10491,3,'MSA','Mobilytics','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10492,3,'WIP','Discrete Manufacturing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10493,3,'WIE','Common Work Execution','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10494,3,'WIS','Common Work Setup','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10500,3,'FOM','Order Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10501,3,'EHW','Employee Wellness','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10502,3,'HRH','HCM Connect','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10503,3,'WLF','Work Life','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10504,3,'EVB','Visual Information Builder','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10505,3,'HEA','Advisement','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10506,3,'HEF','Financial Aid','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10507,3,'HEY','Campus Community','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10508,3,'HER','Student Records','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10509,3,'HES','Student Financials','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10511,3,'HRY','Global Payroll Interface','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10512,3,'AFS','Sales for Retail Banking','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10513,3,'ATC','Sales for Communications','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10514,3,'ACO','Sales for Consumer Goods Retail Execution','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10515,3,'AHT','Sales for High Tech Manufacturing','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10516,3,'SVC','Service','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10525,3,'VCS','Supply Chain Collaboration','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10526,3,'ZQW','Sales for Wealth Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10527,3,'ZQU','Sales for Utilities','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10528,3,'ZQP','Sales for Pharmaceuticals','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10529,3,'ZQA','Sales for Automotive','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10530,3,'ENQ','Quality Issue and Action Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10531,3,'MNT','Maintenance Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10532,3,'LOY','Loyalty','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10533,3,'HHR','Corporate Social Responsibility','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10534,3,'CXI','Customer Experience Integration Solution','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10535,3,'GTR','Risk Manager','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10536,3,'GTO','Business Intelligence for Risk Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10537,3,'ZPS_IBM','Sales Cloud for IBM Notes','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10538,3,'ZPS_365','Sales Cloud for Office 365','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10539,3,'ZPS_GM','Sales Cloud for Gmail','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10540,3,'CSS','Digital Customer Service','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10541,3,'AHE','Sales Cloud for Higher Education','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10542,3,'HQZ','Human Resources Advisor','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10543,3,'ZEM','CX Cloud Mobile','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10544,3,'HCM_CC','HCM Central Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10545,3,'HEX','HCM Extracts','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10546,3,'HCM_AND','Tap for Android','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10547,3,'HCM_IOS','Tap for iOS','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10548,3,'YPR','Replenishment Planning','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10549,3,'HEQ','Student Admissions','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10550,3,'CHK','Checklist','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10551,3,'POR_MB','Self Service Procurement Mobile','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10552,3,'PSC_PZ','Planning and Zoning','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10553,3,'PSC_PER','Permits','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10554,3,'PSC_CE','Code Enforcement','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10555,3,'PSC_BL','Business Licenses','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10556,3,'PSC_POL','Professional Licenses','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10557,3,'RCL','Service Logistics','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10558,3,'ZUP','Policy Automation Data Connector','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10559,3,'PSC_TS','Public Sector Tech Stack','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10560,3,'PSC_CC','Public Sector Common Components','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10561,3,'PSC_LCM','Public Sector Lifecycle Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10562,3,'PSC_OPS','Public Sector DevOps Internal','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10563,3,'OSS','Subscription Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10564,3,'MOB','HCM Cloud Mobile','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10565,3,'MSX','Backlog Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10566,3,'CJM','Channel Revenue Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10567,3,'ISP','Inspector','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10568,3,'JV','Joint Venture Management','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10569,3,'PSC','Public Sector Subledger','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10570,3,'CDA','Sales Assistant','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10571,3,'PSX','Oracle PSCR Subledger','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10572,3,'FLA','Lease Accounting','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10573,3,'CXM','CX Sales Mobile','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10574,3,'MCM','Oracle Municipal Code Officer','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10575,3,'ECC','Enterprise Catalog for Communications','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10576,3,'SCH','Supply Chain for Healthcare','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10577,3,'DXS','DX4C - Sales Experience','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10578,3,'DXL','DX4C - Launch Experience','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10579,3,'DXC','DX4C - Care Experience','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10580,3,'POI','Spend Classification','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10581,3,'UER','Customer Experience for Utilities','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10582,3,'CXO','Sales for Outlook','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10583,3,'HRE','Touchpoints','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10585,3,'CXZ','Sales for Zoom','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10586,3,'HCO','HCM Communicate','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10587,3,'FRB','Recruiting Booster','');
    INSERT INTO CHM_SOURCE_APPLICATIONS (SOURCE_APPLICATION_ID, CHM_SOURCE_SYSTEM_ID, SHORT_NAME, NAME, DESCRIPTION) VALUES (10588,3,'OIA','Intelligent Advisor','');
    
    dbms_output.put_line('Data inserted for CHM_SOURCE_SYSTEMS');
END;
/

--CHM_LOOKUP_TYPES    
BEGIN
	INSERT INTO CHM_LOOKUP_TYPES (CHM_SOURCE_SYSTEM_ID, SOURCE_APPLICATION_ID, LOOKUP_TYPE, MEANING, DESCRIPTION) VALUES ('1', '-1', 'CHM_YES_NO_FLAG', 'Yes or No Flag', 'Lookup Type for Yes No value');
	INSERT INTO CHM_LOOKUP_TYPES (CHM_SOURCE_SYSTEM_ID, SOURCE_APPLICATION_ID, LOOKUP_TYPE, MEANING, DESCRIPTION) VALUES ('1', '-1', 'CHM_INTEGRATION_FREQUENCY', 'Yes or No Flag', 'Lookup Type for Integration Frequency');
	INSERT INTO CHM_LOOKUP_TYPES (CHM_SOURCE_SYSTEM_ID, SOURCE_APPLICATION_ID, LOOKUP_TYPE, MEANING, DESCRIPTION) VALUES ('1', '-1', 'CHM_EXCH_RATE_SYNC_CONV_TYPE_RESTRICTION', 'Conversion Type Restriction for Exchange Rate Sync', 'Conversion Type Restriction for Exchange Rate Sync');
	INSERT INTO CHM_LOOKUP_TYPES (CHM_SOURCE_SYSTEM_ID, SOURCE_APPLICATION_ID, LOOKUP_TYPE, MEANING, DESCRIPTION) VALUES ('1', '-1', 'CHM_ITEM_SYNC_ORG_RESTRICTION', 'Organization Restriction for Item Master Sync', 'Organization Restriction for Item Master Sync');
	INSERT INTO CHM_LOOKUP_TYPES (CHM_SOURCE_SYSTEM_ID, SOURCE_APPLICATION_ID, LOOKUP_TYPE, MEANING, DESCRIPTION) VALUES ('1', '-1', 'CHM_PRICE_LIST_SYNC_ORG_RESTRICTION', 'Organization Restriction for Price List Master Sync', 'Organization Restriction for Price List Master Sync');
	INSERT INTO CHM_LOOKUP_TYPES (CHM_SOURCE_SYSTEM_ID, SOURCE_APPLICATION_ID, LOOKUP_TYPE, MEANING, DESCRIPTION) VALUES ('1', '-1', 'CHM_LOOKUP_SYNC_TYPE_RESTRICTION', 'Lookup Type Restriction for Lookups Sync', 'Lookup Type Restriction for Lookups Sync');

    dbms_output.put_line('Data inserted for CHM_LOOKUP_TYPES');
END;
/

--CHM_LOOKUP_VALUES
BEGIN
	INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_YES_NO_FLAG' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'Y','Yes', 'Lookup Value for Yes');
	INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_YES_NO_FLAG' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 2, 'N','No', 'Lookup Value for No');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_INTEGRATION_FREQUENCY' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'ADHOC','Ad Hoc / Manual', '');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_INTEGRATION_FREQUENCY' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 2, 'DAILY','Daily', '');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_INTEGRATION_FREQUENCY' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 3, 'WEEKLY','Weekly', '');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_INTEGRATION_FREQUENCY' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 3, 'MONTHLY','Monthly', '');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_EXCH_RATE_SYNC_CONV_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'Corporate','Corporate Exchange Rate', 'Corporate Exchange Rate');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_EXCH_RATE_SYNC_CONV_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 2, 'User','User Specified Rate', 'User Specified Rate');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_ITEM_SYNC_ORG_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'ENE ITEM MASTER ORGANIZATION','ENE ITEM MASTER ORGANIZATION', '');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_PRICE_LIST_SYNC_ORG_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'ENE USA Business Unit','ENE USA Business Unit', '');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_PRICE_LIST_SYNC_ORG_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 2, 'ENE IND Business Unit','ENE IND Business Unit', '');
    
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_LOOKUP_SYNC_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 1, 'YES_NO','Yes No Flag', 'Yes No Flag');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_LOOKUP_SYNC_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 2, 'CUSTOMER CLASS','CUSTOMER CLASS', 'CUSTOMER CLASS');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_LOOKUP_SYNC_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 3, 'CUSTOMER_CATEGORY','CUSTOMER_CATEGORY', 'CUSTOMER_CATEGORY');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_LOOKUP_SYNC_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 4, 'CUSTOMER_TYPE','CUSTOMER_TYPE', 'CUSTOMER_TYPE');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_LOOKUP_SYNC_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 5, 'CUSTOMER_STATUS','CUSTOMER_STATUS', 'CUSTOMER_STATUS');
    INSERT INTO CHM_LOOKUP_VALUES (CHM_LOOKUP_TYPE_ID, DISPLAY_SEQUENCE, LOOKUP_CODE, MEANING, DESCRIPTION) VALUES ((select CHM_LOOKUP_TYPE_ID from chm_lookup_types where LOOKUP_TYPE='CHM_LOOKUP_SYNC_TYPE_RESTRICTION' and CHM_SOURCE_SYSTEM_ID=1 and SOURCE_APPLICATION_ID=-1), 6, 'EGP_ITEM_TYPE','EGP_ITEM_TYPE', 'EGP_ITEM_TYPE');
    
	dbms_output.put_line('Data inserted for CHM_LOOKUP_VALUES');
END;
/

--CHM_INTEGRATIONS
BEGIN

    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMITEMCATEGORIESSYNCERPTOCHM', 'CHMItemCategoriesSyncERPtoCHM', 'Item Categories Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMITEMMASTERSYNCERPTOCHM', 'CHMItemMasterSyncERPtoCHM', 'Item Master Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMPRICELISTMASTERSYNCERPTOCHM', 'CHMPriceListMasterSyncERPtoCHM', 'Price List Master Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily', 'Y');
    Insert into CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) values ('CHMTICKETINGSERVICE','CHMTicketingService','Ticketing Service to create JIRA tickets for integation execptions',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc','Y');
    Insert into CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) values ('CHMDISTRIBUTORACCOUNTSYNCERPTOCH','CHMDistributorAccountSyncERPtoCHM','Distributor Account Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    Insert into CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) values ('CHMDISTRIBUTORSITESANDUSESSYNCER','CHMDistributorSitesAndUsesSyncERPtoCHM','Distributor Sites and Site Uses Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');

    dbms_output.put_line('Data inserted for CHM_INTEGRATIONS');
    
END;
/


COMMIT;