--CHM_INTEGRATIONS
BEGIN
   
INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMINSTALLERMASTERSYNCSFDCTOCHM','CHMInstallerMasterSyncSFDCtoCHM','Installer Master Sync from Sales force to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='SFDC'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMSPAMASTERHDRLINESYNCSFDCTOCHM','CHMSPAMasterHDRLinesSyncSFDCtoCHM','SPA Master Header and Lines Sync from Sales force to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='SFDC'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMSPAMASTERDISTSYNCSFDCTOCHM','CHMSPAMasterDistributorSyncSFDCtoCHM','SPA Master Distributor Sync from Sales force to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='SFDC'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
dbms_output.put_line('Data inserted for CHM_INTEGRATIONS');
    
END;
/


COMMIT;
