--CHM_INTEGRATIONS
BEGIN

    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMEXCHANGERATESSYNCERPTOCHM', 'CHMExchangeRatesSyncERPtoCHM', 'Exchange Rates Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMLOOKUPSSYNCERPTOCHM', 'CHMLookupsSyncERPtoCHM', 'Lookups Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMLEDGERSSYNCERPTOCHM', 'CHMLedgersSyncERPtoCHM', 'Ledgers Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMBUSINESSUNITSSYNCERPTOCHM', 'CHMBusinessUnitsSyncERPtoCHM', 'Business Units Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMCALENDARSSYNCERPTOCHM', 'CHMCalendarsSyncERPtoCHM', 'Calendars Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMCURRENCIESSYNCERPTOCHM', 'CHMCurrenciesSyncERPtoCHM', 'Currencies Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMCOUNTRIESSYNCERPTOCHM', 'CHMCountriesSyncERPtoCHM', 'Countries Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMARTRXTYPESSYNCERPTOCHM', 'CHMARTransactionTypesSyncERPtoCHM', 'AR Transaction Types Sync from Oracle Fusion Cloud ERP to CHM', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc', 'Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMVALUESETSSYNCERPTOCHM','CHMVALUESETSSYNCERPTOCHM','Value Sets Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc','Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMACCOUNTINGPERIODSSYNCERPTOCHM','CHMAccountingPeriodsSyncERPtoCHM','Accounting Periods Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc','Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMSTATEPROVINCESYNCERPTOCHM','CHMStateProvinceSyncERPtoCHM','State Province Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc','Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMMASTERUOMSYNCERPTOCHM','CHMMasterUOMSyncERPtoCHM','Master UOM Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Ad hoc','Y');

    dbms_output.put_line('Data inserted for CHM_INTEGRATIONS');
    
END;
/

COMMIT;

