--CHM_INTEGRATIONS
BEGIN
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMSHIPMENTDETAILSYNCERPTOCHM','CHMShipmentDetailSyncERPtoCHM','Shipment Detail Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    dbms_output.put_line('Data inserted for CHM_INTEGRATIONS');
    
END;
/

COMMIT;
