--CHM_INTEGRATIONS
BEGIN
    -- POD 3 Seed Data
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMITEMCATEGORIESSETSSYNERPTOCHM','CHMItemCategoriesSetsSyncERPtoCHM','Item Categories Sets Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMITEMCATASSIGNMENTSSYNERPTOCHM','CHMItemCategoryAssignmentsSyncERPtoCHM','Item Category Assignments Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMPRICELISTITEMSYNCERPTOCHM','CHMPriceListItemSyncERPToCHM','Price List Items Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    dbms_output.put_line('Data inserted for CHM_INTEGRATIONS');
    
END;
/

COMMIT;
