INSERT INTO CHM_SOURCE_SYSTEMS (SHORT_NAME, NAME, DESCRIPTION) VALUES ('INCORTA', 'Incorta', 'Incorta');
    
INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED)
 VALUES ('CHMSHIPMENTSYNCINCORTATOCHM', 'CHMShipmentDetailSyncIncortaToCHM', 'Shipment Detail Sync from Incorta to CHM
', (SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='INCORTA') ,(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily', 'Y');
    
commit;    

