--Drop Sequences
DROP SEQUENCE CHM_VALUE_SETS_SEQ;
DROP SEQUENCE CHM_ACCOUNTING_PERIODS_SEQ;
DROP SEQUENCE CHM_STATE_PROVINCE_SEQ;
DROP SEQUENCE CHM_UOM_SEQ;
DROP SEQUENCE CHM_AR_TRX_TYPE_SEQ;
DROP SEQUENCE CHM_CALENDAR_SEQ;
DROP SEQUENCE CHM_CURRENCY_SEQ;
DROP SEQUENCE CHM_EXCHANGE_RATE_SEQ;
DROP SEQUENCE CHM_LEDGER_SEQ;
DROP SEQUENCE CHM_ORGANIZATION_UNIT_SEQ;
DROP SEQUENCE CHM_TERRITORY_SEQ;

--Drop Tables:
DROP TABLE CHM_VALUE_SETS;
DROP TABLE CHM_ACCOUNTING_PERIODS;
DROP TABLE CHM_STATE_PROVINCE;
DROP TABLE CHM_UOM_MASTER;
DROP TABLE CHM_AR_TRX_TYPES;
DROP TABLE CHM_CALENDARS;
DROP TABLE CHM_CURRENCIES;
DROP TABLE CHM_EXCHANGE_RATES;
DROP TABLE CHM_LEDGERS;
DROP TABLE CHM_ORGANIZATION_UNITS;
DROP TABLE CHM_TERRITORIES;


--DROP Packages
DROP PACKAGE CHM_VALUE_SETS_PKG;
DROP PACKAGE CHM_ACCOUNTING_PERIODS_PKG;
DROP PACKAGE CHM_STATE_PROVINCE_PKG;
DROP PACKAGE CHM_UOM_MASTER_PKG;
DROP PACKAGE CHM_AR_TRX_TYPE_PKG;
DROP PACKAGE CHM_CALENDAR_PKG;
DROP PACKAGE CHM_COUNTRY_PKG;
DROP PACKAGE CHM_CURRENCY_PKG;
DROP PACKAGE CHM_EXCHANGE_RATE_PKG;
DROP PACKAGE CHM_LEDGER_PKG;
DROP PACKAGE CHM_ORGANIZATION_UNIT_PKG;


