--Drop Sequences
DROP SEQUENCE CHM_SOURCE_SYSTEM_SEQ  ;
DROP SEQUENCE CHM_SOURCE_APPLICATION_SEQ  ;
DROP SEQUENCE CHM_INTEGRATION_SEQ    ;
DROP SEQUENCE CHM_ITEM_CATEGORY_SEQ  ;
DROP SEQUENCE CHM_ITEM_SEQ           ;
DROP SEQUENCE CHM_PRICE_LIST_SEQ     ;
DROP SEQUENCE CHM_DIST_ACCOUNTS_ID   ;
DROP SEQUENCE CHM_DIST_SITE_USES_ID  ;
DROP SEQUENCE CHM_LOOKUP_TYPE_SEQ    ;
DROP SEQUENCE CHM_LOOKUP_VALUE_SEQ   ;

--Drop Tables:
DROP TABLE CHM_SOURCE_SYSTEMS;
DROP TABLE CHM_SOURCE_APPLICATIONS;
DROP TABLE CHM_INTEGRATIONS;
DROP TABLE CHM_INTEGRATION_RUNS;
DROP TABLE CHM_LOOKUP_TYPES;
DROP TABLE CHM_LOOKUP_VALUES;
DROP TABLE CHM_ITEM_CATEGORIES;
DROP TABLE CHM_ITEMS;
DROP TABLE CHM_PRICE_LISTS;
DROP TABLE CHM_DIST_ACCOUNTS;
DROP TABLE CHM_DIST_SITE_USES;

--DROP Packages
DROP PACKAGE CHM_INTEGRATIONS_PKG;
DROP PACKAGE CHM_LOOKUP_PKG;
DROP PACKAGE CHM_ITEM_CATEGORY_PKG;
DROP PACKAGE CHM_ITEM_PKG;
DROP PACKAGE CHM_PRICE_LIST_PKG;
DROP PACKAGE CHM_DIST_ACCOUNTS_PKG;
DROP PACKAGE CHM_DIST_SITE_USES_PKG;
