--Drop Sequences
DROP SEQUENCE CHM_ITEM_CATEGORY_SET_SEQ  ;
DROP SEQUENCE CHM_ITEM_CATEGORY_ASSIGNMENTS_SEQ  ;
DROP SEQUENCE CHM_PRICE_LIST_ITEM_SEQ;

--Drop Tables:
DROP TABLE CHM_ITEM_CATEGORY_SETS;
DROP TABLE CHM_ITEM_CATEGORY_ASSIGNMENTS;
DROP TABLE CHM_PRICE_LIST_ITEMS;

--DROP Packages
DROP PACKAGE CHM_ITEM_CATEGORY_SETS_PKG;
DROP PACKAGE CHM_ITEM_CATEGORY_ASSIGNMENTS_PKG;
DROP PACKAGE CHM_PRICE_LIST_ITEM_PKG;
