--CHM_INTEGRATIONS
BEGIN
    BEGIN
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMMSISHIPMENTDETAILSYNCERPTOCHM','CHMMsiShipmentDetailSyncERPtoCHM','MSI Shipment Detail Sync from Oracle Fusion Cloud ERP to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    EXCEPTION WHEN OTHERS THEN dbms_output.put_line('Exception 1: '||sqlerrm); END;
        
    BEGIN
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMMSISPADISTIINSTALLERSYNCSFDCT','CHMMSISpaDistiInstallerSyncSFDCtoCHM','MSI SPA Distributor, Installer and Geo Restriction Sync from Sales force to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='SFDC'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    EXCEPTION WHEN OTHERS THEN dbms_output.put_line('Exception 2: '||sqlerrm); END;
    
    BEGIN
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMMSISPACONTACTSYNCSFDCTOCHM','CHMMSISpaContactSyncSFDCtoCHM','MSI SPA Contact Sync from Sales force to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='SFDC'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    EXCEPTION WHEN OTHERS THEN dbms_output.put_line('Exception 3: '||sqlerrm); END;
    
    BEGIN
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMMSISPASYNCSFDCTOCHM','CHMMSISpaHeaderSyncSFDCtoCHM','MSI SPA Header Sync from Sales force to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='SFDC'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    EXCEPTION WHEN OTHERS THEN dbms_output.put_line('Exception 4: '||sqlerrm); END;
    
    BEGIN
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMMSISPASYSOBJECTSSYNCSFDCTOCHM','CHMMSISpaSystemObjectsSyncSFDCtoCHM','MSI SPA SystemAttachment,UnitActivation,SysSizeInc,SysSizeIncChm Sync from Sales force to CHM',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='SFDC'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    EXCEPTION WHEN OTHERS THEN dbms_output.put_line('Exception 5: '||sqlerrm); END;
    
    BEGIN
    INSERT INTO CHM_INTEGRATIONS (IDENTIFIER, NAME, DESCRIPTION, SOURCE, TARGET, FREQUENCY, IS_SEEDED) VALUES ('CHMMSIAPINVOICESYNCCHMTOERP','CHMMSIAPInvoiceSyncCHMToERP','CHM MSI AP INVOICE Sync CHM To ERP',(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='ORACLE'),(SELECT NAME FROM CHM_SOURCE_SYSTEMS WHERE SHORT_NAME='CHM'),'Daily','Y');
    EXCEPTION WHEN OTHERS THEN dbms_output.put_line('Exception 6: '||sqlerrm); END;
    
    dbms_output.put_line('Data inserted for CHM_INTEGRATIONS');
    
	
    COMMIT;
    
END;
/

